/* Isolated browser acceptance: does not use the user's normal browser profile. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),url=p=>pathToFileURL(path.join(root,p)).href,KEY='meiye.complaint.unified.v1',out=process.env.AFTERCARE_QA_DIR||'/tmp/complaint-aftercare-qa';
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 fs.mkdirSync(out,{recursive:true});const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
 const page=await context.newPage();page.setDefaultTimeout(10000);await page.goto(url('index.html')+'#complaint-tickets');const f=page.frameLocator('#page-complaint-tickets iframe');await f.locator('.tickets-table').waitFor();
 const read=()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY),before=await read();
 const fixtures=await f.locator('body').evaluate(()=>{const s=ComplaintStore.load(),result={};for(const mode of ['main','disabled','recall']){const t=Engine.create(s,'chen',{name:'林女士',phone:'13800001002',order:'O2',store:'上海徐汇店',channel:'400电话',title:'售后办理验收 · '+mode,description:'客户申请退款'});Engine.follow(s,t,t.owner,{connected:true,content:'已核实客户情况，继续售后处理'});if(mode==='disabled')t.flow.config.ticketFlow.nodes[0].actions={transfer:false,store:false,suspend:false};result[mode]=t.id;}ComplaintStore.save(s);return result;});
 const get=async key=>(await read()).tickets.find(t=>t.id===fixtures[key]);await page.reload();await f.locator('.tickets-table').waitFor();
 async function open(key){await f.locator('#filter-form [name=q]').fill(fixtures[key]);await f.locator('#filter-form [type=submit]').click();await f.locator('[data-action=detail][data-id="'+fixtures[key]+'"]').click();await f.locator('.ticket-drawer').waitFor();}
 async function more(surface,action){await surface.locator('.ticket-more-menu summary').click();await surface.locator('[data-action='+action+']').click();return surface.locator('[data-form='+action+']');}
 async function submit(form){const revision=await form.evaluate(()=>JSON.parse(localStorage.getItem('meiye.complaint.unified.v1'))._revision);await form.locator('[type=submit]').click();await form.waitFor({state:'detached'});await page.waitForFunction(({key,revision})=>JSON.parse(localStorage.getItem(key))._revision>revision,{key:KEY,revision});}
 const original=await get('main');await open('main');let form=await more(f,'transferAftercare');const candidates=await form.locator('[name=person] option').evaluateAll(rows=>rows.map(r=>r.value));assert(candidates.includes('chen'));for(const id of ['aftercare','finance','store2','callback','intake'])assert(!candidates.includes(id));await form.locator('[name=person]').selectOption('chen');await form.locator('[name=note]').fill(' ');await form.locator('[type=submit]').click();await form.locator('.error-inline').waitFor();assert((await form.locator('.error-slot').innerText()).includes('转派原因'));assert.equal((await get('main')).owner,original.owner);await form.locator('[name=note]').fill('客户后续由陈悦继续联系，已线下交接。');await page.screenshot({path:out+'/pc-handoff.png'});await submit(form);
 let t=await get('main');assert.equal(t.owner,'chen');assert.equal(t.currentAssignee,'chen');assert.equal(t.taskDeadline,original.taskDeadline);assert.equal(t.deadline,original.deadline);assert.equal(t.handoffs.length,1);
 form=await more(f,'requestStoreAssistance');assert((await form.innerText()).includes('上海徐汇店'));assert((await form.innerText()).includes('陈悦'));await form.locator('[name=note]').fill('请核实客户到店服务次数，并补充当日服务记录。');await form.locator('[name=files]').setInputFiles({name:'待核实事项.txt',mimeType:'text/plain',buffer:Buffer.from('核对服务日期与次数')});await page.screenshot({path:out+'/pc-store-assistance.png'});await submit(form);await f.locator('[data-action=finishStoreAssistance]').waitFor();t=await get('main');assert.equal(t.phase,'待门店协同');assert.equal(t.state,'处理中');assert.equal(t.owner,'chen');assert.equal(t.currentAssignee,'store2');assert.equal(t.taskDeadline,original.taskDeadline);assert.equal(t.deadline,original.deadline);assert.equal(await f.locator('[data-action=proposal]').count(),0);await page.screenshot({path:out+'/pc-assistance-context.png'});
 const mobile=await context.newPage();mobile.setDefaultTimeout(10000);await mobile.setViewportSize({width:390,height:844});await mobile.goto(url('complaint-prototype/workflow/index.html')+'?view=h5#/mobile/'+fixtures.main);await mobile.locator('[data-action=finishStoreAssistance]').click();form=mobile.locator('[data-form=finishStoreAssistance]');await form.locator('[name=result]').selectOption('需售后继续协调');await form.locator('[name=note]').fill('已核实服务次数，相关记录已补齐，请售后继续沟通处理。');await form.locator('[name=files]').setInputFiles({name:'门店核实记录.txt',mimeType:'text/plain',buffer:Buffer.from('服务记录已核实')});await mobile.screenshot({path:out+'/h5-store-feedback.png'});assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await submit(form);await mobile.locator('[data-action=proposal]').waitFor();t=await get('main');assert.equal(t.phase,'处理中');assert.equal(t.currentAssignee,'chen');assert.equal(t.execution,undefined);assert.equal(t.taskDeadline,original.taskDeadline);assert.equal(t.storeAssistanceHistory[0].status,'已反馈');assert.equal(t.storeAssistanceHistory[0].files.length,1);assert.equal(t.storeAssistanceHistory[0].resultFiles.length,1);
 form=await more(mobile,'suspendTicket');assert((await form.innerText()).includes('整单继续计时'));await form.locator('[name=reasonType]').selectOption('materials');await form.locator('[name=evidenceId]').selectOption({index:1});await form.locator('[name=note]').fill('等待客户补充支付记录，约定后续再联系。');await form.locator('[name=expectedAt]').fill(new Date(Date.now()+86400000).toISOString().slice(0,16));await mobile.screenshot({path:out+'/h5-suspend-form.png'});await submit(form);await mobile.locator('[data-action=resumeTicket]').waitFor();t=await get('main');assert.equal(t.phase,'已挂起');assert.equal(t.taskDeadline,null);assert.equal(t.deadline,original.deadline);assert.equal(t.suspension.clock,'node');assert.equal(await mobile.locator('[data-action=proposal]').count(),0);assert.equal(await mobile.locator('.ticket-more-menu').count(),0);await mobile.reload();await mobile.locator('[data-action=resumeTicket]').waitFor();assert((await mobile.locator('.aftercare-context').innerText()).includes('节点计时已暂停，整单继续计时'));await mobile.screenshot({path:out+'/h5-suspended.png',fullPage:true});assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await mobile.locator('[data-action=resumeTicket]').click();form=mobile.locator('[data-form=resumeTicket]');await form.locator('[name=note]').fill('支付资料已补齐，继续联系客户确认处理事项。');await submit(form);await mobile.locator('[data-action=proposal]').waitFor();t=await get('main');assert.equal(t.phase,'处理中');assert.equal(t.owner,'chen');assert.equal(t.currentAssignee,'chen');assert.equal(t.suspension,undefined);assert.equal(t.taskDeadline,original.taskDeadline+t.suspensionHistory[0].duration);assert.equal(t.deadline,original.deadline);assert(t.suspensionHistory[0].duration>0);
 await mobile.locator('[data-action=proposal]').click();form=mobile.locator('[data-form=proposal]');await form.locator('[name=type]').selectOption('service');await form.locator('[name=content]').fill('已线下核实并协调完成，无需退赔。');await submit(form);await mobile.locator('[data-action=closeTicket]').waitFor();assert.equal((await get('main')).phase,'待结案');assert.equal((await get('main')).currentAssignee,'chen');await mobile.close();
 await page.reload();await f.locator('.tickets-table').waitFor();await open('disabled');for(const action of ['transferAftercare','requestStoreAssistance','suspendTicket'])assert.equal(await f.locator('[data-action='+action+']').count(),0);assert.equal(await f.locator('[data-action=proposal]').count(),1);await f.getByRole('button',{name:'关闭详情',exact:true}).click();
 await open('recall');form=await more(f,'requestStoreAssistance');await form.locator('[name=note]').fill('请门店核实服务日期。');await submit(form);await f.locator('[data-action=finishStoreAssistance]').waitFor();await f.locator('body').evaluate((body,id)=>{S.actor=ticket(id).owner;renderDrawer(id);},fixtures.recall);form=await more(f,'cancelStoreAssistance');await form.locator('[name=note]').fill('资料已通过其他渠道补齐，无需继续协同。');await page.screenshot({path:out+'/pc-recall-assistance.png'});await submit(form);await f.locator('[data-action=proposal]').waitFor();t=await get('recall');assert.equal(t.phase,'处理中');assert.equal(t.storeAssistanceHistory[0].status,'已撤回');assert.equal(t.currentAssignee,t.owner);
 await page.reload();await f.locator('.tickets-table').waitFor();const end=await read();assert.deepEqual(end.tickets.filter(t=>before.tickets.some(old=>old.id===t.id)),before.tickets);assert.deepEqual(end.configuration,before.configuration);assert.equal(end.tickets.length,before.tickets.length+3);assert.deepEqual(errors,[]);
 console.log('PASS PC/H5: same-department handoff, reason validation, ticket-store assistance and attachments, H5 feedback returns to original owner, suspension pauses node only, reload/resume preserves remaining node time and whole deadline, continued solution flow, node permissions hide disabled actions, owner recalls assistance, existing tickets/configuration unchanged, no script errors or mobile overflow.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
