'use strict';
const assert=require('node:assert/strict'),E=require('./engine.js'),R=E.Rules,F=R.Flow;
const NOW=Date.parse('2026-09-29T10:00:00+08:00');let count=0;
function test(name,fn){fn();count++;console.log('通过：'+name);}
const scene=s=>F.prepare(R.sceneList(s)[0]);
const fin=()=>({...F.node(),title:'财务审核',source:'duty',duty:'财务审核'});
function setup(mode='all'){
 let s=E.seed(NOW),d=scene(s),n=F.node();n.hierarchy.level=2;n.mode=mode;d.config.approval.flow=[n,fin()];d.config.routing.sceneMode='manager';s.organization=F.organization(s);s.organization.departments.find(d=>d.id==='operations').leaders=['store1','quality'];s=R.saveScene(s,'manager',d,0,NOW);
 const c=E.apply(s,'intake',{type:'create',data:{sceneId:d.id,sceneRevision:s.sceneRevision,customerId:'customer1',store:E.STORES[0],title:'组织审批验证',description:'原型测试'}},NOW);s=c.state;const id=c.caseId;
 const act=(type,data={},who)=>{const current=s.cases.find(c=>c.id===id),t=E.pending(current).find(t=>!who||t.assigneeId===who);s=E.apply(s,who||t.assigneeId,{type,caseId:id,taskId:t.id,expectedRevision:current.revision,data},NOW+60000).state;return s;};
 act('accept');act('contact',{result:'connected',content:'已核实'});act('plan',{planType:'refund',orderId:'order-r1',refundAmount:'600',refundReason:'未消费',summary:'按原路退回',deadline:NOW+E.HOUR*24});return {get state(){return s;},get c(){return s.cases.find(c=>c.id===id);},act};
}
test('同一部门负责人规则按工单门店匹配不同员工',()=>{const s=E.seed(NOW),org=F.organization(s),n=F.node();assert.deepEqual(F.resolveSource(org,n,{store:E.STORES[0],applicantId:'intake'}),[['store1']]);assert.deepEqual(F.resolveSource(org,n,{store:E.STORES[1],applicantId:'intake'}),[['store2']]);});
test('连续层级从当前门店逐级向上，支持从最高层计数',()=>{const org=F.organization({}),n=F.node();n.hierarchy.mode='continuous';n.hierarchy.level=3;assert.deepEqual(F.resolveSource(org,n,{store:E.STORES[0]}),[['store1'],['manager'],['director']]);n.hierarchy.mode='single';n.hierarchy.origin='top';n.hierarchy.level=1;assert.deepEqual(F.resolveSource(org,n,{store:E.STORES[0]}),[['director']]);});
test('直属上级从申请人任职匹配，不按门店负责人猜测',()=>{const n=F.node();n.source='manager';n.hierarchy.base='applicant';n.hierarchy.mode='continuous';n.hierarchy.level=2;assert.deepEqual(F.resolveSource(F.organization({}),n,{applicantId:'aftercare'}),[['manager'],['director']]);});
test('指定上级按所选起点匹配，连续上级沿同一起点逐级查找',()=>{const org=F.organization({}),n=F.node();n.source='manager';const ctx={store:E.STORES[0],applicantId:'finance'};n.hierarchy.base='business';assert.deepEqual(F.resolveSource(org,n,ctx),[['manager']]);n.hierarchy.mode='continuous';n.hierarchy.level=2;assert.deepEqual(F.resolveSource(org,n,ctx),[['manager'],['director']]);n.hierarchy.origin='top';n.hierarchy.mode='single';n.hierarchy.level=1;assert.deepEqual(F.resolveSource(org,n,ctx),[['director']]);n.hierarchy.origin='bottom';n.hierarchy.base='applicant';assert.deepEqual(F.resolveSource(org,n,ctx),[['director']]);assert.ok(F.sourceLabel({...n,hierarchy:{...n.hierarchy,base:'business'}}).includes('工单客户所属门店'));});
test('指定上级起始门店无人时走节点兜底，循环链仍拒绝匹配',()=>{const s=E.seed(NOW),r=R.prepareScene(R.sceneList(s)[0]).config,org=F.organization(s),n={...F.node(),source:'manager',handling:{hours:4,overdue:'supervisor',emptyAssigneeId:'director'}},ctx={store:E.STORES[0],applicantId:'intake'};org.departments.find(d=>d.store===E.STORES[0]).leaders=[];assert.deepEqual(F.resolveApprovers(r,org,n,ctx),[['director']]);org.departments.find(d=>d.store===E.STORES[0]).leaders=['store1'];org.appointments.find(a=>a.personId==='manager').managerId='store1';assert.throws(()=>F.resolveSource(org,n,ctx),/循环/);});
test('接待老师起点按老师任职部门匹配，缺少老师时走空节点承接人',()=>{const s=E.seed(NOW),r=R.prepareScene(R.sceneList(s)[0]).config,org=F.organization(s),n={...F.node(),hierarchy:{base:'receptionist',mode:'continuous',origin:'bottom',level:2,empty:'block'},handling:{hours:4,overdue:'supervisor',emptyAssigneeId:'director'}};F.validNode(n);assert.deepEqual(F.resolveSource(org,n,{store:E.STORES[0],applicantId:'intake',receptionistId:'finance'}),[['finance'],['director']]);assert.deepEqual(F.resolveApprovers(r,org,n,{applicantId:'intake'}),[['director']]);});
test('审批路径从工单客户读取接待老师，不使用门店负责人替代',()=>{const s=E.seed(NOW),r=R.prepareScene(R.sceneList(s)[0]).config;s.customers.find(c=>c.id==='customer1').receptionistId='quality';r.approval.flow=[{...F.node(),title:'接待部门审核',hierarchy:{base:'receptionist',mode:'single',origin:'bottom',level:1,empty:'block'}},{...F.node(),source:'duty',duty:'财务审核'}];assert.deepEqual(F.plan(r,s,{customerId:'customer1',store:E.STORES[0],applicantId:'intake'},600).steps[0].members,['quality']);});
test('缺失层级和循环组织阻止提交，空负责人可按配置向上找',()=>{const org=F.organization({}),n=F.node();n.hierarchy.level=9;assert.throws(()=>F.resolveSource(org,n,{store:E.STORES[0]}),/不存在/);n.hierarchy.level=1;org.departments.find(d=>d.id==='store1').leaders=[];assert.throws(()=>F.resolveSource(org,n,{store:E.STORES[0]}),/负责人/);n.hierarchy.empty='parent';assert.deepEqual(F.resolveSource(org,n,{store:E.STORES[0]}),[['manager']]);org.departments.find(d=>d.id==='operations').parent='store1';assert.throws(()=>F.resolveSource(org,n,{store:E.STORES[0]}),/循环/);});
test('公司职责从部门岗位任职重算，人员停用即失效',()=>{const s={organization:F.organization({})};s.organization.appointments.find(a=>a.personId==='finance').active=false;assert.throws(()=>F.resolveSource(F.organization(s),{source:'duty',duty:'财务审核'},{}),/有效人员/);});
test('旧金额条件迁移为默认分支，不改写原配置',()=>{const s=E.seed(NOW),d=R.sceneList(s)[0],before=JSON.stringify(d),prepared=F.prepare(d);assert.equal(JSON.stringify(d),before);assert.equal(prepared.config.approval.flow[0].type,'branch');assert.deepEqual(F.plan(prepared.config,s,{store:E.STORES[0],applicantId:'store1'},500).steps.map(x=>x.members),[['finance']]);assert.deepEqual(F.plan(prepared.config,s,{store:E.STORES[0],applicantId:'store1'},500.01).steps.map(x=>x.members),[['manager'],['finance']]);});
test('重叠条件按优先级匹配，默认条件只在未命中时选择',()=>{const s=E.seed(NOW),d=scene(s),g=d.config.approval.flow[0],b=F.condition();b.conditions=[{op:'gte',value:100}];b.title='优先小额';b.nodes=[{...F.node(),source:'duty',duty:'品控复核'}];g.branches.unshift(b);assert.equal(F.plan(d.config,s,{store:E.STORES[0],applicantId:'intake'},600).path[0].title,'优先小额');assert.equal(F.plan(d.config,s,{store:E.STORES[0],applicantId:'intake'},50).path[0].title,'默认条件');});
test('同人审批使用独立职责代审，代审仍为本人时阻止',()=>{const s=E.seed(NOW),d=scene(s);assert.equal(F.plan(d.config,s,{store:E.STORES[0],applicantId:'manager'},600).steps[0].members[0],'director');d.config.approval.delegateDuty='客诉主管';assert.throws(()=>F.plan(d.config,s,{store:E.STORES[0],applicantId:'manager'},600),/代审/);});
test('复制分支生成全新标识，重复标识与缺失财务结尾拒绝保存',()=>{const d=scene(E.seed(NOW)),flow=d.config.approval.flow,copied=F.duplicate(flow[0]);assert.notEqual(copied.id,flow[0].id);assert.notEqual(copied.branches[0].nodes[0].id,flow[0].branches[0].nodes[0].id);assert.throws(()=>F.validate([flow[0],flow[0],fin()]),/重复/);assert.throws(()=>F.validate([flow[0]]),/财务审核/);});
test('会签实际派发两人，全部通过后才生成财务待办',()=>{const run=setup();assert.deepEqual(E.pending(run.c).map(t=>t.assigneeId),['store1','quality']);run.act('refundApproval',{decision:'approve',content:'通过'},'store1');assert.deepEqual(E.pending(run.c).map(t=>t.assigneeId),['quality']);run.act('refundApproval',{decision:'approve',content:'通过'},'quality');assert.deepEqual(E.pending(run.c).map(t=>t.assigneeId),['finance']);});
test('或签一人通过后取消同组待办，审批完成可进入客户意见',()=>{const run=setup('any');run.act('refundApproval',{decision:'approve',content:'通过'},'quality');assert.equal(run.c.plans.at(-1).approvals.find(a=>a.assigneeId==='store1').status,'skipped');assert.deepEqual(E.pending(run.c).map(t=>t.assigneeId),['finance']);run.act('refundApproval',{decision:'approve',content:'通过'},'finance');assert.equal(run.c.stage,'confirm');run.act('confirm',{version:1,decision:'agree',method:'电话记录',evidence:'客户确认同意'});assert.equal(run.c.stage,'refund');});
test('任一会签人驳回取消同组任务及后续审批，释放退款占用',()=>{const run=setup();run.act('refundApproval',{decision:'reject',content:'补充材料'},'quality');assert.equal(run.c.stage,'plan');assert.equal(E.pending(run.c).some(t=>t.kind==='refundApproval'),false);assert.notEqual(run.c.plans.at(-1).refund.reservation,'held');});
test('依次审批逐人生成待办，前一人未审后一个人不能抢审',()=>{const run=setup('sequential');assert.deepEqual(E.pending(run.c).map(t=>t.assigneeId),['store1']);run.act('refundApproval',{decision:'approve',content:'通过'},'store1');assert.deepEqual(E.pending(run.c).map(t=>t.assigneeId),['quality']);});
test('抄送在到达节点时通知一次，不生成审批阻塞',()=>{let s=E.seed(NOW),d=scene(s);d.config.approval.flow=[{...F.node('cc'),source:'duty',duty:'品控复核'},fin()];d.config.routing.sceneMode='manager';s=R.saveScene(s,'manager',d,0,NOW);let made=E.apply(s,'intake',{type:'create',data:{sceneId:d.id,customerId:'customer1',store:E.STORES[0],title:'抄送验收',description:'测试'}},NOW);s=made.state;function act(type,data){const c=s.cases[0],t=E.pending(c)[0];s=E.apply(s,t.assigneeId,{type,caseId:c.id,taskId:t.id,expectedRevision:c.revision,data},NOW+60000).state;}act('accept',{});act('contact',{result:'connected',content:'核实'});act('plan',{planType:'refund',orderId:'order-r1',refundAmount:'100',refundReason:'未消费',summary:'退款',deadline:NOW+E.HOUR*24});assert.equal(s.notices.filter(n=>n.event==='approvalCC').length,1);act('refundApproval',{decision:'approve',content:'通过'});assert.equal(s.notices.filter(n=>n.event==='approvalCC').length,1);assert.equal(s.cases[0].stage,'confirm');});
test('审批快照保留已匹配人员，后续组织更新不篡改在途任务',()=>{const run=setup(),before=JSON.stringify(run.c.plans.at(-1).flowPlan);run.state.organization.departments.find(d=>d.id==='operations').leaders=['director'];assert.equal(JSON.stringify(run.c.plans.at(-1).flowPlan),before);assert.deepEqual(E.pending(run.c).map(t=>t.assigneeId),['store1','quality']);});
console.log(`完成 ${count} 项组织审批验证。`);
