'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const errors=[],url=file=>pathToFileURL(path.resolve(__dirname,file)).href;
 const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Shanghai'}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(12000);
 await page.goto(url('approvals.html')+'#records',{waitUntil:'domcontentloaded'});
 const drawer=page.locator('.approval-drawer'),action=(name)=>drawer.getByRole('button',{name,exact:true}),read=()=>page.evaluate(()=>ComplaintStore.load());
 await page.getByLabel('搜索审批记录',{exact:true}).fill('KS20261007-D12');await page.getByRole('button',{name:'查询',exact:true}).click();await page.getByRole('button',{name:'查看详情',exact:true}).click();
 const before=await read(),old=before.approvalRecords.find(r=>r.ticketId.endsWith('-D12')),ticket=before.tickets.find(t=>t.id.endsWith('-D12'));
 assert.match(await drawer.innerText(),/发起失败/);assert.equal(await action('在钉钉查看').count(),0);await action('重新发起').click();await drawer.locator('#approval-error').filter({hasText:'工单编号'}).waitFor();assert.deepEqual((await read()).approvalRecords,before.approvalRecords);
 await action('编辑模板').click();await drawer.getByLabel('工单编号关联字段',{exact:true}).selectOption('ticket.id');await page.screenshot({path:'/tmp/complaint-recovery-template-fix.png'});await action('保存').click();await drawer.getByRole('heading',{name:'审批详情',exact:true}).waitFor();assert.equal(await action('编辑模板').count(),0);
 await action('重新发起').click();await drawer.locator('.approval-status.running').waitFor();assert.match(await drawer.innerText(),/第 2 次/);assert.match(await drawer.innerText(),/门店付款申请 · V2/);assert.equal(await drawer.locator('.approval-detail-table tbody tr').count(),2);await page.screenshot({path:'/tmp/complaint-recovery-new-round.png'});
 const after=await read(),current=after.tickets.find(t=>t.id===ticket.id);assert.deepEqual(after.approvalRecords.find(r=>r.id===old.id),old);assert.equal(current.taskDeadline,ticket.taskDeadline);assert.deepEqual(current.proposal,ticket.proposal);assert.deepEqual(current.payments,ticket.payments);
 await action('关闭').click();assert.equal(await page.locator('.approval-table tbody tr').count(),2);const failed=page.locator('.approval-table tbody tr').filter({hasText:'发起失败'});await failed.getByRole('button',{name:'查看详情',exact:true}).click();assert.equal(await action('重新发起').count(),0);await action('查看最新审批').click();await drawer.locator('.approval-status.running').waitFor();
 await action('关闭').click();await page.getByRole('button',{name:'钉钉配置',exact:true}).click();assert.equal(await action('测试连接').count(),0);assert.doesNotMatch(await drawer.innerText(),/未连接|应用凭据/);await drawer.getByLabel('企业 ID（CorpId）',{exact:true}).fill('ding-prototype');await drawer.getByLabel('应用标识（AppKey）',{exact:true}).fill('app-complaint');await drawer.getByLabel('应用 ID（AgentId）',{exact:true}).fill('1001');await page.screenshot({path:'/tmp/complaint-recovery-configuration.png'});await action('保存').click();await drawer.waitFor({state:'detached'});await page.reload({waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'钉钉配置',exact:true}).click();assert.equal(await drawer.getByLabel('企业 ID（CorpId）',{exact:true}).inputValue(),'ding-prototype');await action('取消').click();
 await context.close();
 for(const mobile of [false,true]){
  const c=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},timezoneId:'Asia/Shanghai'}),p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(12000);
  await p.goto(url('workflow/index.html')+(mobile?'?view=h5#/mobile/':'#/tickets/')+'KS20261007-D13',{waitUntil:'domcontentloaded'});const detail=p.locator('.external-approval-detail'),flow=p.locator('[aria-current=step]');await flow.locator('[data-action=externalApproval]').click();await detail.waitFor();assert.match(await detail.innerText(),/收款账号/);assert.equal(await detail.getByRole('link',{name:'在钉钉查看',exact:true}).count(),0);
  const initial=await p.evaluate(()=>{const s=ComplaintStore.load(),t=s.tickets.find(t=>t.id.endsWith('-D13'));return {record:Engine.externalApprovalRecord(s,t),t};});
  await detail.locator('[data-action=approvalCorrect]').click();const form=p.locator('[data-form=proposal]');await form.waitFor();assert.equal(await form.locator('[name=payoutAccount]').inputValue(),'');assert.equal(await form.locator('.refund-item').count(),2);if(mobile)assert.equal(await form.locator('table').count(),0);
  await form.locator('[name=payoutAccount]').fill('customer_alipay');await form.locator('[name=content]').fill('已补充客户收款账号，退款与置换事项保持不变。');await p.screenshot({path:'/tmp/complaint-recovery-'+(mobile?'h5':'pc')+'-solution.png'});await form.locator('[type=submit]').click();await form.waitFor({state:'detached'});assert.match(await flow.innerText(),/付款审批/);
  const saved=await p.evaluate(()=>{const s=ComplaintStore.load(),t=s.tickets.find(t=>t.id.endsWith('-D13'));return {record:Engine.externalApprovalRecord(s,t),records:s.approvalRecords,t};});assert.equal(saved.record.status,'running');assert.equal(saved.record.proposalVersion,2);assert.deepEqual(saved.records.find(r=>r.id===initial.record.id),initial.record);assert.equal(saved.t.proposal.refund,initial.t.proposal.refund);assert.deepEqual(saved.t.proposal.exchangeItems.map(r=>[r.productId,r.quantity]),initial.t.proposal.exchangeItems.map(r=>[r.productId,r.quantity]));
  await flow.locator('[data-action=externalApproval]').click();await detail.waitFor();assert.match(await detail.innerText(),/customer_alipay/);assert.equal(await detail.locator('[data-action=approvalCorrect]').count(),0);await p.screenshot({path:'/tmp/complaint-recovery-'+(mobile?'h5':'pc')+'-approval.png'});if(mobile){await p.setViewportSize({width:320,height:700});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
  await c.close();
 }
 assert.deepEqual(errors,[]);console.log('PASS approval recovery: current template repair, new rounds with immutable failed evidence, preserved clocks, parameter-only configuration persistence, no empty external links, PC/H5 solution correction, full refund/product details and 320px layout.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
