'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Shanghai'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(12000);
 await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href+'#complaint-approvals',{waitUntil:'domcontentloaded'});
 const f=page.frameLocator('#page-complaint-approvals iframe'),drawer=f.locator('.approval-drawer'),table=f.locator('.approval-table');await table.waitFor();
 const action=(name,where=f)=>where.getByRole('button',{name,exact:true}),shot=async name=>page.screenshot({path:'/tmp/complaint-approval-'+name+'.png'}),read=()=>f.locator('body').evaluate(()=>ComplaintStore.load());
 assert.equal(await table.locator('tbody tr').count(),3);await shot('templates');const before=await read();
 await action('编辑',table.locator('tbody tr').first()).click();await drawer.waitFor();assert.equal(await drawer.locator('.approval-mapping tbody tr').count(),19);assert.match(await drawer.innerText(),/退款明细/);await shot('mapping');
 await action('预览审批单',drawer).click();assert.equal(await drawer.locator('.approval-detail-table tbody tr').count(),2);assert.match(await drawer.innerText(),/¥500.00/);await shot('payment-preview');
 await drawer.locator('#preview-ticket').selectOption('KS20261007-P40');assert.match(await drawer.innerText(),/¥600.00/);await action('返回配置',drawer).click();assert.equal(await drawer.locator('[name=name]').inputValue(),'付款申请');
 await drawer.getByLabel('工单编号关联字段',{exact:true}).selectOption('');await action('保存',drawer).click();await drawer.locator('#approval-error').filter({hasText:'工单编号'}).waitFor();assert.match(await drawer.locator('#approval-error').innerText(),/工单编号/);await drawer.getByLabel('工单编号关联字段',{exact:true}).selectOption('ticket.id');
 await drawer.getByLabel('处理方案取值方式',{exact:true}).selectOption('constant');await drawer.getByLabel('处理方案固定值',{exact:true}).fill('方案已线下确认');await action('保存',drawer).click();await drawer.waitFor({state:'detached'});assert.equal((await read()).configuration.approvalIntegration.templates[0].mappings.reason.value,'方案已线下确认');
 await action('编辑',table.locator('tbody tr').nth(1)).click();await action('预览审批单',drawer).click();assert.equal(await drawer.locator('.approval-detail-table tbody tr').count(),2);assert.match(await drawer.innerText(),/¥480.00/);await shot('purchase-preview');await action('返回配置',drawer).click();await action('取消',drawer).click();
 await action('＋ 新增模板').click();await drawer.locator('[name=name]').fill('采购补充申请');await drawer.getByLabel('搜索钉钉审批模板',{exact:true}).fill('客诉商品采购申请');await drawer.getByLabel('搜索钉钉审批模板',{exact:true}).press('Tab');assert.equal(await drawer.locator('[name=processCode]').inputValue(),'PROC-COMPLAINT-PURCHASE');await action('同步字段',drawer).click();assert.equal(await drawer.locator('.approval-mapping tbody tr').count(),10);await drawer.locator('[name=enabled]').check();await action('保存',drawer).click();await drawer.waitFor({state:'detached'});assert.equal(await table.locator('tbody tr').count(),4);
 await f.getByLabel('搜索模板',{exact:true}).fill('采购补充');await action('查询').click();assert.equal(await table.locator('tbody tr').count(),1);await action('停用',table).click();await action('启用',table).waitFor();assert.match(await table.innerText(),/停用/);await action('启用',table).click();await action('停用',table).waitFor();await action('重置').click();
 await f.getByRole('tab',{name:'审批记录',exact:true}).click();await f.locator('.approval-table th').filter({hasText:'当前审批人'}).waitFor();assert((await table.locator('tbody tr').count())>=11);await shot('records');await f.getByLabel('搜索审批记录',{exact:true}).fill('KS20261007-D04');await action('查询').click();await action('查看详情',table.locator('tbody tr').first()).click();assert.match(await drawer.innerText(),/已拒绝/);assert.match(await drawer.innerText(),/项目依据/);assert.equal(await drawer.locator('.approval-detail-table tbody tr').count(),2);assert.equal(await action('在钉钉查看',drawer).count(),0);await shot('record-detail');await action('同步状态',drawer).click();await f.locator('#toast').filter({hasText:'审批状态已刷新'}).waitFor();await action('关闭',drawer).click();
 await action('钉钉配置').click();assert.equal(await drawer.getByText('未连接',{exact:true}).count(),0);assert.equal(await action('测试连接',drawer).count(),0);assert.equal(await drawer.getByText('应用凭据',{exact:true}).count(),0);await drawer.getByLabel('企业 ID（CorpId）',{exact:true}).fill('ding-config-review');await drawer.getByRole('tab',{name:'人员对应',exact:true}).click();await drawer.locator('[data-identity=aftercare][data-key=userId]').fill('user-aftercare');await drawer.locator('[data-identity=aftercare][data-key=deptId]').fill('101');await shot('identities');await action('保存',drawer).click();await drawer.waitFor({state:'detached'});const connected=await read();assert.equal(connected.configuration.approvalIntegration.connection.status,'disconnected');assert.equal(connected.configuration.approvalIntegration.connection.corpId,'ding-config-review');assert(!JSON.stringify(connected.configuration.approvalIntegration.connection).includes('secret'));
 await page.locator('#complaint-nav .nav-item').filter({hasText:'规则配置'}).click();const rules=page.frameLocator('#page-complaint-rules iframe');await rules.locator('[data-scene-action=edit]').first().click();await rules.locator('.ac-node-approval .ac-node-body').first().click();const nd=rules.getByRole('dialog',{name:'设置审批节点'});await nd.waitFor();assert.equal(await nd.locator('input,select').count(),3);assert.doesNotMatch(await nd.innerText(),/审批人来源|会签|部门负责人/);await nd.getByLabel('节点名称',{exact:true}).fill('付款审批');await nd.getByLabel('办理时效（小时）',{exact:true}).fill('18');await nd.getByLabel('关联审批模板',{exact:true}).selectOption('approval-payment');await shot('node');await nd.getByRole('button',{name:'确定',exact:true}).click();assert.match(await rules.locator('.ac-node-approval').first().innerText(),/付款申请 · 18 小时/);await rules.getByRole('button',{name:'保存配置',exact:true}).click();await rules.locator('[data-scene-action=edit]').first().waitFor();
 await page.locator('#complaint-nav .nav-item').filter({hasText:'审批管理'}).click();await f.getByRole('tab',{name:'审批模板',exact:true}).click();await f.locator('.approval-table th').filter({hasText:'钉钉审批模板'}).waitFor();await action('停用',table.locator('tbody tr').first()).click();await f.locator('#toast').filter({hasText:'启用规则引用'}).waitFor();assert.match(await f.locator('#toast').innerText(),/启用规则引用/);await table.locator('tbody tr').first().getByRole('button',{name:'5 个规则',exact:true}).click();assert.match(await drawer.innerText(),/付款审批/);await action('关闭',drawer).click();
 const after=await read();assert.deepEqual(after.tickets,before.tickets);assert.deepEqual(after.approvalRecords.map(r=>r.snapshot),before.approvalRecords.map(r=>r.snapshot));
 for(const [w,h] of [[1280,900],[1024,800]]){await page.setViewportSize({width:w,height:h});await action('编辑',table.locator('tbody tr').first()).click();assert(await drawer.evaluate(el=>el.scrollWidth<=el.clientWidth+1));assert(await action('保存',drawer).isVisible());await shot('width-'+w);await action('取消',drawer).click();}
 await page.reload({waitUntil:'domcontentloaded'});await table.waitFor();assert.equal((await read()).configuration.approvalIntegration.templates.length,4);assert.deepEqual(errors,[]);
 console.log('PASS approval templates: host menu, CRUD, search/status filters, schema fields, required/type validation, fixed value mapping, multi-row refund/purchase preview, record snapshots/reasons, configuration-only drawer, identities, exactly three approval-node fields, saved template reference/disable guard, old tickets preserved, reload persistence, 1024/1280/1440 layouts.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
