(function(){
'use strict';
const T=window.ApprovalTemplates,Store=window.ComplaintStore,E=window.Engine,C=window.CaseEngine,$=s=>document.querySelector(s),params=new URLSearchParams(location.search),actor=params.get('actor')||'manager';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Date(v).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).replaceAll('/','-'):'—';
const money=v=>'¥'+Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const opts=(rows,val)=>rows.map(([v,n])=>`<option value="${esc(v)}" ${v===val?'selected':''}>${esc(n)}</option>`).join('');
const button=(label,action,extra='',style='')=>`<button type="button" class="btn ${style}" data-approval-action="${action}" ${extra}>${label}</button>`;
const badge=(status,label)=>`<span class="approval-status ${status}">${esc(label||T.STATUS[status]||status)}</span>`;
const input=(label,name,val,extra='')=>`<label class="field"><span class="field-title">${label}</span><input name="${name}" aria-label="${label}" value="${esc(val)}" ${extra}></label>`;
let state,tab='templates',modal=null,lastFocus,timer,page=1;
let filters={q:'',status:'',templateId:'',from:'',to:''};
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function load(){state=Store.load();return state;}
function render(){
 document.body.classList.toggle('embedded',params.get('embed')==='1');
 const tabs=`<section class="panel"><nav class="tabs" role="tablist" aria-label="审批管理">${[['templates','审批模板'],['records','审批记录']].map(([id,label])=>`<button role="tab" aria-selected="${tab===id}" class="${tab===id?'active':''}" data-approval-action="tab" data-id="${id}">${label}</button>`).join('')}</nav></section>`;
 $('#application').innerHTML=`<div class="pc-shell"><aside class="side"><div class="brand"><span class="brand-mark">✦</span><div><strong>美业AI平台</strong><small>SERVICE OPERATIONS</small></div></div><div class="side-label">客诉管理</div><a class="nav" href="workflow/index.html#/tickets">▤ 客诉工单</a><a class="nav" href="index.html?page=rules#rules">▤ 规则配置</a><a class="nav" href="schedule.html">▤ 售后排班</a><a class="nav active" href="#templates">▤ 审批管理</a></aside><main class="main"><header class="pc-header"><span>客诉管理 / 审批管理</span><div class="row"><span>林岚 · 售后主管</span><span class="avatar">林</span></div></header><div class="page-body approval-page">${actor!=='manager'?'<div class="empty"><h3>暂无配置权限</h3></div>':`<div class="page-heading"><h1>审批管理</h1><div class="approval-toolbar">${button('钉钉配置','connection')}${tab==='templates'?button('＋ 新增模板','new','','primary'):''}</div></div>${tabs}<section class="panel"><form id="approval-filters" class="filters"><input name="q" aria-label="${tab==='templates'?'搜索模板':'搜索审批记录'}" placeholder="${tab==='templates'?'模板名称 / 钉钉模板':'工单编号 / 审批名称 / 客户'}" value="${esc(filters.q)}">${tab==='records'?`<select name="templateId" aria-label="审批模板">${opts([['','全部模板'],...T.list(state).map(t=>[t.id,t.name])],filters.templateId)}</select>`:''}<select name="status" aria-label="状态">${opts([['','全部状态'],...(tab==='templates'?[['enabled','启用'],['disabled','停用'],['draft','草稿'],['invalid','配置异常']]:Object.entries(T.STATUS))],filters.status)}</select>${tab==='records'?`<input type="date" name="from" aria-label="开始日期" value="${esc(filters.from)}"><span class="muted">至</span><input type="date" name="to" aria-label="结束日期" value="${esc(filters.to)}">`:''}<button class="btn" type="submit">查询</button>${button('重置','reset','','quiet')}</form></section>${tab==='templates'?templateList():recordList()}`}</div></main></div>`;
}
function templateState(t){return T.issues(t).length?(t.enabled?'invalid':'draft'):t.enabled?'enabled':'disabled';}
function templateList(){const rows=T.list(state).filter(t=>(!filters.q||(t.name+' '+t.dingName+' '+t.processCode).includes(filters.q))&&(!filters.status||templateState(t)===filters.status));
 return `<section class="panel"><div class="table-wrap"><table class="approval-table"><thead><tr><th>模板名称</th><th>钉钉审批模板</th><th>状态</th><th>引用规则</th><th>最近同步</th><th>操作</th></tr></thead><tbody>${rows.map(t=>{const kind=templateState(t),refs=T.references(state,t.id),count=new Set(refs.map(r=>r.sceneId)).size;return `<tr><td><strong>${esc(t.name)}</strong><div class="sub">V${t.version}</div></td><td>${esc(t.dingName||'未关联')}<div class="code" title="${esc(t.processCode)}">${esc(t.processCode||'—')}</div></td><td><span class="state-dot ${kind}"></span>${({enabled:'启用',disabled:'停用',draft:'草稿',invalid:'配置异常'})[kind]}</td><td>${count?`<button class="approval-link" data-approval-action="references" data-id="${esc(t.id)}">${count} 个规则</button>`:'—'}</td><td class="nowrap muted small">${date(t.syncedAt)}</td><td class="nowrap">${button('编辑','edit',`data-id="${esc(t.id)}"`,'quiet compact blue')}${button(t.enabled?'停用':'启用','toggle',`data-id="${esc(t.id)}"`,'quiet compact')}</td></tr>`;}).join('')||'<tr><td colspan="6"><div class="empty">暂无符合条件的模板</div></td></tr>'}</tbody></table></div><div class="table-foot">共 ${rows.length} 个模板</div></section>`;
}
function recordList(){const rows=(state.approvalRecords||[]).filter(r=>(!filters.q||(r.ticketId+' '+r.name+' '+r.customer).includes(filters.q))&&(!filters.status||r.status===filters.status)&&(!filters.templateId||r.templateId===filters.templateId)&&(!filters.from||r.at>=new Date(filters.from+'T00:00:00+08:00').getTime())&&(!filters.to||r.at<new Date(filters.to+'T00:00:00+08:00').getTime()+86400000)).sort((a,b)=>b.at-a.at);const max=Math.max(1,Math.ceil(rows.length/20));page=Math.min(page,max);
 return `<section class="panel"><div class="table-wrap"><table class="approval-table"><thead><tr><th>关联工单</th><th>审批名称</th><th>审批状态</th><th>当前审批人</th><th>发起人</th><th>发起时间</th><th>操作</th></tr></thead><tbody>${rows.slice((page-1)*20,page*20).map(r=>`<tr><td><button class="approval-link" data-approval-action="ticket" data-id="${esc(r.ticketId)}">${esc(r.ticketId)}</button><div class="sub">${esc(r.customer)}</div></td><td><strong>${esc(r.name)}</strong><div class="sub">${esc(r.templateName)} · 第 ${r.round} 次</div></td><td>${badge(r.status)}${r.syncStatus==='pending'?'<span class="approval-sync-warning">状态待同步</span>':''}</td><td>${esc(r.people.join('、')||'—')}</td><td>${esc(r.initiator)}</td><td class="nowrap muted small">${date(r.at)}</td><td>${button('查看详情','record',`data-id="${esc(r.id)}"`,'quiet compact blue')}</td></tr>`).join('')||'<tr><td colspan="7"><div class="empty">暂无符合条件的审批记录</div></td></tr>'}</tbody></table></div><div class="table-foot"><span>共 ${rows.length} 条记录</span>${max>1?`<div class="row">${button('上一页','prev',page<=1?'disabled':'','compact')}<span>${page} / ${max}</span>${button('下一页','next',page>=max?'disabled':'','compact')}</div>`:''}</div></section>`;
}
function openShell(title,content,footer){
 $('#modal-root').innerHTML=`<div class="overlay"><section class="drawer approval-drawer" role="dialog" aria-modal="true" aria-label="${esc(title)}"><header class="drawer-head"><h2>${esc(title)}</h2>${button('×','close','aria-label="关闭抽屉"','close')}</header><form id="approval-drawer-form" novalidate><div class="drawer-scroll"><div class="callout error form-error" id="approval-error" role="alert"></div>${content}</div><footer class="form-actions">${footer}</footer></form></section></div>`;
 document.body.style.overflow='hidden';$('#modal-root').querySelector('input:not(:disabled),select,button')?.focus();
}
function close(){modal=null;$('#modal-root').innerHTML='';document.body.style.overflow='';lastFocus?.focus();}
function error(message){const el=$('#approval-error');if(el){el.textContent=message;el.scrollIntoView({block:'nearest'});}else toast(message);}
function openTemplate(id,returnRecordId){load();lastFocus=document.activeElement;modal={type:'template',draft:T.clone(id?T.get(state,id):T.newTemplate()),revision:T.integration(state).revision,returnRecordId,dirty:false};drawTemplate();}
function readTemplate(){if(modal?.type!=='template')return;const f=$('#approval-drawer-form'),t=modal.draft;if(!f?.elements.name)return;t.name=f.elements.name.value;t.processCode=f.elements.processCode.value.trim();t.enabled=f.elements.enabled.checked;
 f.querySelectorAll('[data-map]').forEach(el=>{const path=el.dataset.map.split('/');let m=t.mappings;for(let i=0;i<path.length;i++){m[path[i]]??={mode:'field',source:''};if(i===path.length-1){m[path[i]][el.dataset.key]=el.value;return;}m=m[path[i]].children??={};}});
}
function mappingRow(f,m,path,parentSource){m??={mode:'field',source:''};const choices=T.optionsFor(f,parentSource),mode=m.mode||'field';const source=mode==='skip'?'<span class="approval-subtle">不传入</span>':mode==='constant'?(f.type==='select'?`<select data-map="${path}" data-key="value" aria-label="${esc(f.label)}固定值">${opts([['','请选择'],...(f.options||[]).map(x=>[x,x])],m.value)}</select>`:`<input data-map="${path}" data-key="value" aria-label="${esc(f.label)}固定值" value="${esc(m.value||'')}" ${['money','number'].includes(f.type)?'type="number" step="0.01"':''} placeholder="${f.type==='money'?'金额（元）':'填写固定值'}">`):`<select data-map="${path}" data-key="source" aria-label="${esc(f.label)}关联字段">${opts([['','请选择系统字段'],...choices.map(s=>[s.key,s.label])],m.source)}</select>`;
 return `<tr><td class="${parentSource?'approval-child-field':''}"><div class="approval-field-name">${esc(f.label)}${f.required?'<span class="approval-required">*</span>':''}</div><div class="approval-field-type">${T.TYPE_LABELS[f.type]||'不支持的控件'}</div></td><td><select data-map="${path}" data-key="mode" aria-label="${esc(f.label)}取值方式">${opts([['field','系统字段'],['constant','固定值'],...(!f.required?[['skip','不传入']]:[])],mode)}</select></td><td>${source}</td></tr>`;
}
function mappings(t){if(!t.fields.length)return '<div class="approval-empty">选择钉钉审批模板后，同步表单字段</div>';
 const scalar=t.fields.filter(f=>f.type!=='table'),tables=t.fields.filter(f=>f.type==='table');
 const header='<thead><tr><th>钉钉字段</th><th>取值方式</th><th>关联内容</th></tr></thead>';
 return `<div class="approval-mapping-wrap"><table class="approval-mapping">${header}<tbody>${scalar.map(f=>mappingRow(f,t.mappings[f.id],f.id)).join('')}</tbody></table></div>${tables.map(f=>{const m=t.mappings[f.id]||{source:'',children:{}};return `<div class="approval-detail-group"><div class="approval-section-head"><h3>${esc(f.label)}${f.required?'<span class="approval-required">*</span>':''}</h3><label>明细来源<select data-map="${f.id}" data-key="source" aria-label="${esc(f.label)}明细来源">${opts([['','请选择明细'],...T.SOURCES.filter(s=>s.type==='table').map(s=>[s.key,s.label])],m.source)}</select></label></div><div class="approval-mapping-wrap"><table class="approval-mapping">${header}<tbody>${f.children.map(child=>mappingRow(child,m.children?.[child.id],f.id+'/'+child.id,m.source)).join('')}</tbody></table></div></div>`;}).join('')}`;
}
function drawTemplate(){const t=modal.draft;openShell(t.id?'编辑审批模板':'新增审批模板',`<section class="approval-section"><div class="approval-section-head"><h3>基本信息</h3><span class="approval-subtle">${t.id?'V'+t.version:''}</span></div><div class="approval-fields">${input('模板名称','name',t.name,'maxlength="40" placeholder="例如：付款申请" required')}<label class="field"><span class="field-title">状态</span><span class="approval-enabled"><input name="enabled" type="checkbox" ${t.enabled?'checked':''}>启用模板</span></label><label class="field"><span class="field-title">钉钉审批模板</span><input list="approval-catalog" name="catalog" aria-label="搜索钉钉审批模板" value="${esc(t.dingName)}" placeholder="搜索模板名称"><datalist id="approval-catalog">${T.CATALOG.map(x=>`<option value="${esc(x.name)}">${esc(x.processCode)}</option>`).join('')}</datalist></label>${input('模板编码','processCode',t.processCode,'placeholder="输入 processCode"')}</div></section><section class="approval-section"><div class="approval-section-head"><h3>字段关联</h3>${button('同步字段','schema','','compact')}</div>${mappings(t)}</section>`,`${button('预览审批单','preview',t.fields.length?'':'disabled','approval-footer-left')}${button(modal.returnRecordId?'返回审批详情':'取消','close')}<button class="btn primary" type="submit">保存</button>`);}
function valuesMarkup(snapshot){const scalar=snapshot.fields.filter(f=>f.type!=='table'),tables=snapshot.fields.filter(f=>f.type==='table');return `<dl class="approval-values">${scalar.map(f=>`<div class="${f.type==='textarea'?'full':f.type==='money'?'money':''}"><dt>${esc(f.label)}</dt><dd>${f.value===''?'<span class="muted">—</span>':esc(f.type==='money'?money(f.value):f.value)}</dd></div>`).join('')}</dl>${tables.map(f=>`<div class="approval-detail-group"><div class="approval-section-head"><h3>${esc(f.label)}</h3><small>${f.rows.length} 项</small></div><div class="approval-detail-table"><table><thead><tr>${f.columns.map(c=>`<th class="${['money','number'].includes(c.type)?'number':''}">${esc(c.label)}</th>`).join('')}</tr></thead><tbody>${f.rows.map(row=>`<tr>${f.columns.map(c=>{const cell=row.find(x=>x.id===c.id);return `<td class="${['money','number'].includes(c.type)?'number':''}">${cell?.value==null||cell.value===''?'—':esc(c.type==='money'?money(cell.value):cell.value)}</td>`;}).join('')}</tr>`).join('')||`<tr><td colspan="${f.columns.length}" class="muted">无对应明细</td></tr>`}</tbody></table></div></div>`).join('')}`;}
function preview(){readTemplate();const errors=T.issues(modal.draft);if(errors.length)return error(errors[0]);modal.type='preview';modal.ticketId=modal.ticketId||(state.tickets.find(t=>t.id==='KS20261007-P41')||state.tickets.find(t=>t.proposal))?.id;drawPreview();}
function drawPreview(){const t=state.tickets.find(t=>t.id===modal.ticketId),snapshot=t?T.preview(modal.draft,t):null;openShell('预览审批单',`<div class="approval-preview-picker"><label for="preview-ticket">选择工单</label><select id="preview-ticket" aria-label="预览工单">${opts(state.tickets.filter(t=>t.proposal).map(t=>[t.id,t.id+' · '+t.name+' · '+t.proposal.type]),modal.ticketId)}</select></div><section class="approval-section"><div class="approval-section-head"><h3>${esc(modal.draft.name)}</h3><span class="approval-subtle">方案 V${snapshot?.proposalVersion||1}</span></div>${snapshot?.missing.length?`<div class="callout error mb">缺少必填数据：${esc(snapshot.missing.join('、'))}</div>`:''}${snapshot?valuesMarkup(snapshot):'<div class="approval-empty">暂无可预览的工单</div>'}</section>`,button('返回配置','preview-back'));
}
function summaryItem(k,v){return `<div><dt>${k}</dt><dd>${v}</dd></div>`;}
function openRecord(id){load();const r=state.approvalRecords.find(r=>r.id===id);if(!r)return toast('审批记录不存在');const t=state.tickets.find(t=>t.id===r.ticketId),recovery=E.approvalRecovery(state,t,r),latest=state.approvalRecords.filter(x=>x.ticketId===r.ticketId&&x.nodeId===r.nodeId).at(-1);lastFocus=document.activeElement;modal={type:'record',id};openShell('审批详情',`<section class="approval-section"><div class="approval-record-heading"><h3>${esc(r.name)}</h3>${badge(r.status)}</div><dl class="approval-summary">${summaryItem('关联工单',`<button type="button" class="approval-link" data-approval-action="ticket" data-id="${esc(r.ticketId)}">${esc(r.ticketId)}</button>`)}${summaryItem('审批模板',esc(r.templateName)+' · V'+r.templateVersion)}${summaryItem('申请轮次','第 '+r.round+' 次')}${summaryItem('发起人',esc(r.initiator))}${summaryItem('发起时间',date(r.at))}${summaryItem('完成时间',date(r.finishedAt))}${summaryItem('当前审批人',esc(r.people.join('、')||'—'))}${summaryItem('审批编号',esc(r.instanceId||'尚未生成'))}${summaryItem('最近同步',r.syncStatus==='pending'?'<span class="orange">状态待同步</span>':date(r.syncedAt))}</dl>${r.reason||r.error?`<div class="approval-record-reason">${esc(r.reason||r.error)}</div>`:''}</section>${r.snapshot.fields.length?`<section class="approval-section"><div class="approval-section-head"><h3>申请内容</h3><small>方案 V${r.proposalVersion}</small></div>${valuesMarkup(r.snapshot)}</section>`:''}<section class="approval-section"><div class="approval-section-head"><h3>审批过程</h3></div><ol class="approval-events">${r.events.map(e=>`<li class="approval-event ${e.status==='审批中'?'current':''}"><strong>${esc(e.title)}</strong><span class="actor">${esc(e.actor)}</span><time>${date(e.at)}</time>${e.status?`<p class="blue">${esc(e.status)}</p>`:''}${e.note?`<p>${esc(e.note)}</p>`:''}</li>`).join('')}</ol></section>`,`${recovery.failed?`${recovery.issues.length&&recovery.templateId?button('编辑模板','repair-template',`data-id="${esc(recovery.templateId)}"`,'approval-footer-left'):''}${!recovery.issues.length&&recovery.missing.length?button('查看工单','ticket',`data-id="${esc(r.ticketId)}"`,'approval-footer-left'):''}${button('重新发起','record-retry','','primary')}`:r.status!=='failed'?button('同步状态','record-sync','','approval-footer-left'):''}${latest&&latest.id!==r.id?button('查看最新审批','record',`data-id="${esc(latest.id)}"`):''}${button('关闭','close')}${E.approvalSafeURL(r.url)?button('在钉钉查看','ding-open','','primary'):''}`);}
function openConnection(){load();lastFocus=document.activeElement;modal={type:'connection',revision:T.integration(state).revision,draft:T.clone(T.integration(state).connection),section:'base',dirty:false};drawConnection();}
function readConnection(){if(modal?.type!=='connection')return;const f=$('#approval-drawer-form');if(modal.section==='base'){for(const name of ['corpId','appKey','agentId'])modal.draft[name]=f.elements[name]?.value.trim()||'';}else{modal.draft.identities??={};f.querySelectorAll('[data-identity]').forEach(el=>{modal.draft.identities[el.dataset.identity]??={};modal.draft.identities[el.dataset.identity][el.dataset.key]=el.value.trim();});}}
function drawConnection(){const d=modal.draft;const people=C.STAFF.filter(p=>['售后专员','售后主管'].includes(p.role));openShell('钉钉配置',`<div class="approval-tab-panel"><nav class="tabs" role="tablist" aria-label="钉钉配置">${[['base','应用参数'],['people','人员对应']].map(([key,label])=>`<button type="button" role="tab" aria-selected="${modal.section===key}" class="${modal.section===key?'active':''}" data-approval-action="connection-tab" data-id="${key}">${label}</button>`).join('')}</nav>${modal.section==='base'?`<div class="approval-fields">${input('企业 ID（CorpId）','corpId',d.corpId,'placeholder="ding…"')}${input('应用标识（AppKey）','appKey',d.appKey,'placeholder="填写应用标识"')}${input('应用 ID（AgentId）','agentId',d.agentId,'placeholder="填写应用 ID"')}</div>`:`<div class="approval-mapping-wrap"><table class="approval-bindings"><thead><tr><th>系统人员</th><th>钉钉 UserId</th><th>发起部门 ID</th></tr></thead><tbody>${people.map(p=>`<tr><td>${esc(p.name)}<div class="sub">${esc(p.role)}</div></td><td><input data-identity="${p.id}" data-key="userId" aria-label="${esc(p.name)}钉钉 UserId" value="${esc(d.identities?.[p.id]?.userId||'')}" placeholder="填写 UserId"></td><td><input data-identity="${p.id}" data-key="deptId" aria-label="${esc(p.name)}发起部门 ID" value="${esc(d.identities?.[p.id]?.deptId||'')}" placeholder="填写部门 ID"></td></tr>`).join('')}</tbody></table></div>`}</div>`,`${button('取消','close')}<button type="submit" class="btn primary">保存</button>`);}
function navigate(type,id){if(params.get('embed')==='1'){parent.postMessage({type:'complaint-approval-navigate',target:type,id},'*');close();}else location.href=type==='ticket'?'workflow/index.html#/tickets/'+encodeURIComponent(id):'index.html?page=rules#rules/'+encodeURIComponent(id)+'/flow';}
async function action(a,b){if(actor!=='manager')return;
 if(a==='close'){const back=modal?.returnRecordId;return back?openRecord(back):close();}if(a==='tab'){filters={q:'',status:'',templateId:'',from:'',to:''};page=1;location.hash=b.dataset.id;return;}
 if(a==='reset'){filters={q:'',status:'',templateId:'',from:'',to:''};page=1;render();return;}
 if(a==='new'||a==='edit')return openTemplate(b.dataset.id);
 if(a==='connection')return openConnection();
 if(a==='connection-tab'){readConnection();modal.section=b.dataset.id;drawConnection();return;}
 if(a==='schema'){readTemplate();const code=modal.draft.processCode,item=T.CATALOG.find(x=>x.processCode===code);if(!item)return error('请选择列表中的审批模板');T.loadSchema(modal.draft,item);modal.dirty=true;drawTemplate();toast('模板字段已更新');return;}
 if(a==='preview')return preview();if(a==='preview-back'){modal.type='template';drawTemplate();return;}
 if(a==='toggle'){const t=T.clone(T.get(state,b.dataset.id)),revision=T.integration(state).revision;t.enabled=!t.enabled;await Store.exclusive(()=>{const fresh=Store.load();T.saveTemplate(fresh,actor,t,revision);Store.save(fresh);});load();render();toast(t.enabled?'模板已启用':'模板已停用');return;}
 if(a==='record')return openRecord(b.dataset.id);
 if(a==='repair-template')return openTemplate(b.dataset.id,modal.id);
 if(a==='record-sync'||a==='record-retry'){const id=modal.id;let nextId=id;await Store.exclusive(()=>{const fresh=Store.load();if(a==='record-retry'){const r=E.externalRecord(fresh,id);nextId=E.retryExternalApproval(fresh,fresh.tickets.find(t=>t.id===r.ticketId),actor,id).id;}else E.syncExternalApproval(fresh,id,actor);Store.save(fresh);});load();render();openRecord(nextId);toast(a==='record-retry'?'审批已重新发起':'审批状态已刷新');return;}
 if(a==='ding-open'){const r=state.approvalRecords.find(r=>r.id===modal.id);if(E.approvalSafeURL(r?.url))window.open(r.url,'_blank','noopener,noreferrer');return;}
 if(a==='ticket')return navigate('ticket',b.dataset.id);if(a==='rule')return navigate('rule',b.dataset.id);
 if(a==='references'){const refs=T.references(state,b.dataset.id);lastFocus=document.activeElement;modal={type:'references'};openShell('引用规则',`<ul class="approval-reference-list">${refs.map(r=>`<li><span>${esc(r.name)}<small class="muted"> · ${esc(r.node)}</small></span>${button('流程配置','rule',`data-id="${esc(r.sceneId)}"`,'compact quiet blue')}</li>`).join('')}</ul>`,button('关闭','close'));return;}
 if(a==='prev'||a==='next'){page+=a==='next'?1:-1;render();}
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-approval-action]');if(b)Promise.resolve(action(b.dataset.approvalAction,b)).catch(err=>error(err.message));});
document.addEventListener('input',e=>{if(e.target.closest('#approval-drawer-form')&&modal)modal.dirty=true;});
document.addEventListener('change',e=>{try{
 if(modal?.type==='template'){
  if(e.target.name==='catalog'){readTemplate();const item=T.CATALOG.find(x=>x.name===e.target.value||x.processCode===e.target.value);if(item){const t=modal.draft;if(t.processCode!==item.processCode){t.processCode=item.processCode;t.dingName=item.name;t.fields=[];t.mappings={};t.syncedAt=null;if(!t.name)t.name=item.name;}drawTemplate();}return;}
  if(e.target.name==='processCode'){readTemplate();const t=modal.draft;if(!T.CATALOG.some(x=>x.processCode===t.processCode&&x.name===t.dingName)){t.fields=[];t.mappings={};t.dingName='';t.syncedAt=null;drawTemplate();}return;}
  if(e.target.dataset.map&&(e.target.dataset.key==='mode'||modal.draft.fields.some(f=>f.type==='table'&&f.id===e.target.dataset.map))){const scroll=$('.drawer-scroll').scrollTop;readTemplate();drawTemplate();$('.drawer-scroll').scrollTop=scroll;}
 }
 if(modal?.type==='preview'&&e.target.id==='preview-ticket'){modal.ticketId=e.target.value;drawPreview();}
 }catch(err){error(err.message);}});
document.addEventListener('submit',async e=>{if(!['approval-filters','approval-drawer-form'].includes(e.target.id))return;e.preventDefault();if(actor!=='manager')return;
 if(e.target.id==='approval-filters'){const data=Object.fromEntries(new FormData(e.target));if(data.from&&data.to&&data.from>data.to)return toast('开始日期不能晚于结束日期');filters={...filters,...data,q:data.q.trim()};page=1;render();return;}
 const submit=e.target.querySelector('[type=submit]');try{if(submit)submit.disabled=true;
  if(modal.type==='template'){readTemplate();const ctx=modal;await Store.exclusive(()=>{const fresh=Store.load();T.saveTemplate(fresh,actor,ctx.draft,ctx.revision);Store.save(fresh);});}
  else if(modal.type==='connection'){readConnection();const ctx=modal;await Store.exclusive(()=>{const fresh=Store.load(),i=T.integration(fresh);if(i.revision!==ctx.revision)throw Error('审批配置已更新，请重新打开后保存');i.connection={corpId:ctx.draft.corpId,appKey:ctx.draft.appKey,agentId:ctx.draft.agentId,identities:ctx.draft.identities||{},status:'disconnected',eventStatus:'disconnected'};i.revision++;Store.save(fresh);});}
  else return;
  const connection=modal.type==='connection',back=modal.returnRecordId;close();load();render();if(back)openRecord(back);toast(connection?'钉钉配置已保存':'审批模板已保存');
 }catch(err){error(err.message);if(submit)submit.disabled=false;}
});
document.addEventListener('keydown',e=>{if(!modal)return;if(e.key==='Escape'){e.preventDefault();if(modal.type==='preview'){modal.type='template';drawTemplate();}else if(modal.returnRecordId)openRecord(modal.returnRecordId);else close();}if(e.key==='Tab'){const els=[...$('#modal-root').querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),a[href]')].filter(x=>x.offsetParent!==null);if(e.shiftKey&&document.activeElement===els[0]){e.preventDefault();els.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===els.at(-1)){e.preventDefault();els[0]?.focus();}}});
window.addEventListener('beforeunload',e=>{if(modal?.dirty){e.preventDefault();e.returnValue='';}});
window.addEventListener('hashchange',()=>{tab=location.hash==='#records'?'records':'templates';load();render();});
window.addEventListener('storage',e=>{if(e.key!==Store.KEY)return;if(modal)toast('其他页面已更新数据，保存时将校验最新版本');else{load();render();}});
try{load();tab=location.hash==='#records'?'records':'templates';render();}catch(e){$('#application').innerHTML=`<div class="page-body"><div class="callout error">${esc(e.message)}</div></div>`;console.error(e);}
})();
