(function(){
'use strict';
const B=window.ComplaintBI,$=s=>document.querySelector(s),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=n=>n==null?'—':new Intl.NumberFormat('zh-CN',{maximumFractionDigits:0}).format(n),fixed=(n,d=1)=>n==null?'—':n.toFixed(d),percent=n=>n==null?'—':fixed(n)+'%',money=n=>'¥'+number(n),ts=n=>new Date(n).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
const icons={chart:'<path d="M4 20V4M4 20h17M8 16v-5m5 5V6m5 10v-8"/>',download:'<path d="M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5"/>',book:'<path d="M12 5v16M3 4h5a4 4 0 0 1 4 2 4 4 0 0 1 4-2h5v15h-5a4 4 0 0 0-4 2 4 4 0 0 0-4-2H3z"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.chart}</svg>`;
const params=new URLSearchParams(location.search);
const state={tab:['efficiency','customer'].includes(params.get('tab'))?params.get('tab'):'efficiency',start:'2026-09-08',end:'2026-10-07',period:'30',district:'',region:'',store:'',level:'',source:'',dimension:'district',effDimension:['stage','department','person','ticket'].includes(params.get('effDimension'))?params.get('effDimension'):'stage',ticketSearch:'',page:1,effPage:1};
for(const k of ['district','region','store','level','source'])if(params.get(k))state[k]=params.get(k);
if(params.get('start')&&params.get('end')&&B.parse(params.get('start'))>=B.parse('2026-08-25')&&B.parse(params.get('end'))<=B.parse('2026-10-07')&&B.parse(params.get('start'))<=B.parse(params.get('end'))){state.start=params.get('start');state.end=params.get('end');state.period='custom';}
if(!B.stores.some(s=>s.district===state.district))state.district='';
if(!B.stores.some(s=>s.region===state.region&&(!state.district||s.district===state.district)))state.region='';
if(!B.stores.some(s=>s.id===state.store&&(!state.region||s.region===state.region)&&(!state.district||s.district===state.district)))state.store='';
if(!B.SOURCES.includes(state.source))state.source='';if(!['1','2','3','4','5'].includes(state.level))state.level='';
let summary,prior,groupRows=[],effRows=[],modal=null,returnFocus=null,toastTimer;
const act=(a,label,extra='',cls='link')=>`<button class="${cls}" data-action="${a}" ${extra}>${label}</button>`;
const opts=(list,value)=>list.map(x=>{const [v,l]=Array.isArray(x)?x:[x,x];return `<option value="${E(v)}" ${value===v?'selected':''}>${E(l)}</option>`;}).join('');
function select(key,list,value=state[key],label='',cls=''){return `<select data-filter="${key}" aria-label="${label||key}" class="${cls}">${opts(list,value)}</select>`;}
const seg=(key,items)=>`<div class="segmented ${items.length===4?'four-tabs':''}" role="group" aria-label="分析维度">${items.map(([v,l])=>act('segment',l,`data-key="${key}" data-value="${v}" aria-pressed="${state[key]===v}"`,state[key]===v?'active':'')).join('')}</div>`;
function delta(current,previous,type='percent',badUp=true){if(current==null||previous==null||B.parse(B.previous(state).start)<B.START)return '<span>上期暂无可比数据</span>';const diff=current-previous,val=type==='pp'?Math.abs(diff):previous?Math.abs(diff/previous*100):null;if(val==null)return '<span>上期为 0，暂不比较</span>';return `<span class="delta ${(diff>0)===badUp?'bad':'good'}">${diff>0?'↑':diff<0?'↓':'持平 '}${diff===0?'':fixed(val)+(type==='pp'?'pp':'%')}</span><span title="与前一个等长周期比较">较上期</span>`;}
function metric(label,value,unit,foot,sub,kind,featured=false){return `<button class="metric ${featured?'featured':''}" title="${E(sub)}" data-action="metric" data-kind="${kind}" aria-label="${label}，${E(value)}${unit}，查看明细"><div class="metric-label">${label}<span class="info">↗</span></div><div class="metric-value">${value}<span class="metric-unit">${unit}</span></div><div class="metric-foot">${foot}</div></button>`;}
function card(title,sub,body,actions='',classes=''){return `<section class="card ${classes}"><div class="card-head"><div><div class="card-title" title="${E(sub)}">${title}</div></div>${actions}</div>${body}</section>`;}
function scopeName(){return state.store?B.byStore[state.store].name:state.region||state.district||'全国';}
function filterUI(){const districts=[...new Set(B.stores.map(s=>s.district))],regions=[...new Set(B.stores.filter(s=>!state.district||s.district===state.district).map(s=>s.region))],stores=B.scopedStores({...state,store:''});return `<div class="filter-shell"><div class="filters"><div class="filter"><span>统计周期</span>${select('period',[['7','近 7 天'],['30','近 30 天'],['month','本月'],['last','上月'],['custom','自定义日期']],state.period,'统计周期')}<span class="date-range">${state.start.replaceAll('-','.')} — ${state.end.replaceAll('-','.')}</span></div><div class="filter"><span>组织</span>${select('district',[['','全部大区'],...districts],state.district,'大区')}${select('region',[['','全部区域'],...regions],state.region,'区域')}${select('store',[['','全部门店'],...stores.map(s=>[s.id,s.name])],state.store,'门店')}</div><div class="filter">${select('level',[['','全部等级'],...['1','2','3','4','5'].map(x=>[x,x+'级'])],state.level,'客诉等级','short')}${select('source',[['','全部来源'],...B.SOURCES],state.source,'工单来源','short')}</div>${act('reset','重置')}</div></div>`;}
function lineChart(){const rows=B.trend(state),w=640,h=205,left=33,right=43,top=13,bottom=32,cw=w-left-right,ch=h-top-bottom,max=Math.max(...rows.map(r=>r.count),1)*1.17,maxR=Math.max(...rows.map(r=>r.rate),1)*1.25,px=i=>left+i*cw/Math.max(1,rows.length-1),py=(n,m)=>top+ch-n/m*ch;const path=key=>rows.map((r,i)=>(i?'L':'M')+px(i)+','+py(r[key],key==='count'?max:maxR)).join(' ');return `<div class="card-body"><div class="legend"><span><i class="dot"></i>新增客诉（左轴 / 单）</span><span><i class="dot green"></i>每千服务人次客诉量（右轴 / 单）</span></div><div class="chart-wrap"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="本期新增客诉及每千服务人次客诉量趋势"><defs><linearGradient id="trend-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#3370ff" stop-opacity=".17"/><stop offset="1" stop-color="#3370ff" stop-opacity=".01"/></linearGradient></defs>${[0,1,2,3].map(i=>{const y=top+ch-i*ch/3;return `<path d="M${left},${y}H${w-right}" stroke="#edf1f6" stroke-dasharray="3 4"/><text x="${left-10}" y="${y+3}" text-anchor="end" font-size="9" fill="#9ba7b9">${Math.round(max*i/3)}</text><text x="${w-right+11}" y="${y+3}" font-size="9" fill="#9ba7b9">${fixed(maxR*i/3)}</text>`;}).join('')}<path d="${path('count')} L${px(rows.length-1)},${top+ch} L${left},${top+ch}Z" fill="url(#trend-fill)"/><path d="${path('count')}" stroke="#3370ff" stroke-width="2.2" stroke-linejoin="round" fill="none"/><path d="${path('rate')}" stroke="#35b4a5" stroke-width="1.8" stroke-dasharray="5 4" stroke-linejoin="round" fill="none"/>${rows.map((r,i)=>`<circle cx="${px(i)}" cy="${py(r.count,max)}" r="3.4" fill="#fff" stroke="#3370ff" stroke-width="1.7"><title>${r.full}：新增 ${r.count} 单，每千服务人次 ${fixed(r.rate)} 单</title></circle>${(rows.length<=11||i%2===0)?`<text x="${px(i)}" y="${h-9}" text-anchor="middle" font-size="9" fill="#9ba7b9">${r.label}</text>`:''}`).join('')}</svg></div></div>`;}
function regionalCards(){const dim=state.store?'store':state.region?'store':state.district?'region':'district',rows=B.groups(state,dim),max=Math.max(...rows.map(r=>r.cohort.length),1);return `<div class="card-body"><div class="region-cards">${rows.slice(0,4).map((r,i)=>`<button class="region-card" style="--region-color:${B.COLORS[i%4]}" data-action="drill" data-dimension="${dim}" data-key="${E(r.key)}"><div class="region-name">${E(r.name)} <span class="muted">↗</span></div><div class="region-stats"><span class="region-num">${number(r.cohort.length)}</span><span class="region-rate">单 · ${fixed(r.rate)} / 千人次</span></div><div class="region-bar"><span style="width:${r.cohort.length/max*100}%"></span></div><div class="region-foot"><span>按时结案 ${percent(r.closure)}</span><span class="${r.overdue.length?'red':''}">超时未结 ${r.overdue.length}</span></div></button>`).join('')}</div></div>`;}
function process(){const rows=B.efficiency(summary,'stage');return `<div class="process">${B.STAGES.map(stage=>{const r=rows.find(r=>r.key===stage);return `<button class="process-item ${r?.met===false?'hot':''}" data-action="stage" data-key="${stage}" title="本期到期任务的按时完成率；目标 ≥${B.EFFICIENCY_TARGET}%（演示）"><div class="process-title">${stage}</div><div class="process-value ${r?.met===false?'red':r?.met?'green':''}">${fixed(r?.timely)}<small>%</small></div><div class="process-foot">按时完成率<br><span class="${r?.overdue.length?'red':''}">超时未完成 ${number(r?.overdue.length||0)}</span></div></button>`;}).join('')}</div>`;}
function bars(rows,key,colors=['#3370ff']){const max=Math.max(...rows.map(r=>r.value),1),total=rows.reduce((v,r)=>v+r.value,0);return `<div class="bars">${rows.map((r,i)=>`<button class="bar-row" data-action="distribution" data-key="${E(key)}" data-value="${E(r.name)}"><span class="bar-label">${E(r.name)}</span><span class="bar-track"><i class="bar-fill" style="width:${r.value/max*100}%;background:${colors[i%colors.length]}"></i></span><span class="bar-number">${number(r.value)}<small>${fixed(r.value/total*100,0)}%</small></span></button>`).join('')||'<div class="empty">暂无匹配数据</div>'}</div>`;}
function aging(){const ranges=[[0,24,'24h 内'],[24,48,'24–48h'],[48,72,'48–72h'],[72,Infinity,'72h 以上']];return `<div class="card-body"><div class="aging" title="自然时长，含待派与挂起；超时按工单时限判断">${ranges.map(([min,max,label],i)=>{const n=summary.open.filter(t=>{const h=(summary.end-t.created)/B.H;return h>=min&&h<max;}).length;return `<button data-action="aging" data-min="${min}" data-max="${max}"><small>${label}</small><b class="${i===3?'red':''}">${number(n)}</b><small>单未结案</small></button>`;}).join('')}</div></div>`;}
const flowTime=n=>n==null?'—':new Date(n+8*B.H).toISOString().slice(0,19).replace('T',' ');
const flowHours=n=>fixed(n/B.H,2);
function flowColumns(flows){return B.STAGES.flatMap(stage=>{const count=Math.max(1,...flows.map(f=>f.nodes.filter(n=>n.stage===stage).length));return Array.from({length:count},(_,i)=>({stage,occurrence:i+1,label:(stage==='等待派单'?'分派':stage)+(count>1?` · 第 ${i+1} 次`:'')}));});}
function flowTable(flows,kind='default',layoutFlows=flows){
 const outcome=['paid','first','closure'].includes(kind),outcomeTitle={paid:'实际退赔',first:'首联耗时 / 时限',closure:'SLA 结果'}[kind],stages=flowColumns(layoutFlows);
 const fields=[['started','进入时间',170],['ended','结束时间',170],['elapsed','耗时 / h',90],['pause','挂起 / h',90],['effective','有效耗时 / h',110]];
 const widths=[190,140,170,110,110,...(outcome?[150]:[]),...stages.flatMap(()=>fields.map(f=>f[2])),170,120,120,140,90,110];
 const totalColumns=widths.length;
 const cell=(n,key)=>{if(!n)return '<span class="muted">—</span>';if(key==='started'||key==='ended')return `<time>${n[key]==null?'未结束':flowTime(n[key])}</time>`;if(key==='status')return `<span class="${n.overdue?'red':n.returned?'flow-returned':''}">${n.status}${n.overdue?' · 超时':''}</span>`;return `<span class="${(key==='elapsed'||key==='effective')&&n.overdue?'red':''}">${flowHours(n[key])}</span>`;};
 return `<div class="table-scroll flow-scroll" tabindex="0" aria-label="工单流转明细，可横向滚动"><table class="flow-table" style="width:${widths.reduce((a,b)=>a+b,0)}px"><colgroup>${widths.map(w=>`<col style="width:${w}px">`).join('')}</colgroup><thead><tr><th rowspan="2" class="flow-key">工单号</th><th rowspan="2" class="flow-store">门店</th><th rowspan="2">工单创建时间</th><th rowspan="2">期末状态</th><th rowspan="2" title="工单创建至结案或所选期末的自然耗时，包含挂起">总耗时 / h</th>${outcome?`<th rowspan="2">${outcomeTitle}</th>`:''}${stages.map(g=>`<th colspan="${fields.length}" class="flow-group">${g.label}</th>`).join('')}<th rowspan="2">工单结案时间</th><th rowspan="2">大区</th><th rowspan="2">区域</th><th rowspan="2">客户</th><th rowspan="2">客诉等级</th><th rowspan="2">来源</th></tr><tr>${stages.map(()=>fields.map(([key,label])=>`<th${key==='elapsed'?' title="自然耗时，包含挂起；未结束节点计算至所选期末"':''}>${label}</th>`).join('')).join('')}</tr></thead><tbody>${flows.map(flow=>{const t=flow.ticket,s=B.byStore[t.store];return `<tr data-flow-ticket="${t.id}"><td class="flow-key">${act('ticket',E(t.id),`data-id="${t.id}"`)}</td><td class="flow-store">${E(s.name)}</td><td title="${t.created<summary.start?'期初结转工单':'本期创建工单'}">${flowTime(flow.created)}</td><td>${E(flow.status)}</td><td>${flowHours(flow.elapsed)}</td>${outcome?`<td>${ticketOutcome(t,kind)}</td>`:''}${stages.map(g=>{const n=flow.nodes.find(n=>n.stage===g.stage&&n.occurrence===g.occurrence);return fields.map(([key])=>`<td title="${n?E(`第 ${n.sequence} 步 · ${n.person} · ${n.department}`):'截至所选期末未流经此节点'}">${cell(n,key)}</td>`).join('');}).join('')}<td>${flow.closed==null?'未结案':flowTime(flow.closed)}</td><td>${E(s.district)}</td><td>${E(s.region)}</td><td>${E(t.customer)}</td><td>${t.level}级</td><td>${E(t.channel)}</td></tr>`;}).join('')||`<tr><td colspan="${totalColumns}" class="empty">暂无匹配工单</td></tr>`}</tbody></table></div>`;
}
function ledgerRows(){const query=state.ticketSearch.trim().toLowerCase();return B.ticketFlows(summary).filter(f=>!query||[f.ticket.id,f.ticket.customer,B.byStore[f.ticket.store].name].some(v=>v.toLowerCase().includes(query)));}
function ledgerPage(){
 const rows=ledgerRows(),pages=Math.max(1,Math.ceil(rows.length/10));state.effPage=Math.min(state.effPage,pages);
 return `${flowTable(rows.slice((state.effPage-1)*10,state.effPage*10),'default',rows)}<div class="table-footer"><span>共 ${number(rows.length)} 张工单</span><span>${act('ledger-page','‹',`data-step="-1" ${state.effPage===1?'disabled':''}`)}　${state.effPage} / ${pages}　${act('ledger-page','›',`data-step="1" ${state.effPage===pages?'disabled':''}`)}</span></div>`;
}
function ledgerView(){return `<div class="ledger-toolbar"><input type="search" data-input="ledger-search" aria-label="搜索流转工单" placeholder="工单号 / 客户 / 门店" value="${E(state.ticketSearch)}"><span title="统计周期内有流转或期末未结的工单，含历史积压；展示截至所选期末已发生的完整链路。时间为北京时间，耗时单位为小时。">本期流转及未结工单 · 截至 ${state.end}</span></div><div id="ledger-table">${ledgerPage()}</div>`;}
function flowNodeTable(flow){return `<div class="table-scroll"><table class="flow-detail-table"><thead><tr><th>顺序</th><th>节点</th><th>次数</th><th>责任人</th><th>部门</th><th>进入时间</th><th>结束时间</th><th>耗时 / h</th><th>挂起 / h</th><th>有效耗时 / h</th><th>时限 / h</th><th>结果</th></tr></thead><tbody>${B.flowRecords(flow).map(n=>`<tr data-flow-node="${E(n.id)}"><td>${n.sequence}</td><td>${E(n.label)}</td><td>${n.occurrence}</td><td>${E(n.person||'—')}</td><td>${E(n.department||'—')}</td><td>${flowTime(n.started)}</td><td>${n.ended==null?'未结束':flowTime(n.ended)}</td><td>${flowHours(n.elapsed)}</td><td>${flowHours(n.pause)}</td><td>${flowHours(n.effective)}</td><td>${n.limit==null?'—':flowHours(n.limit)}</td><td class="${n.overdue?'red':''}">${E(nodeResult(n))}</td></tr>`).join('')}</tbody></table></div>`;}
function exportFlows(flows){
 const headers=['统计开始日期','统计结束日期','快照时间(北京时间)','数据类型','工单号','大区','区域','门店','客户','等级','来源','工单创建时间','首次分派时间','工单结案时间','期末状态','工单自然耗时h','记录类型','节点实例ID','流转顺序','节点','同环节第几次','责任人','部门','进入时间','结束时间','自然耗时h','挂起时长h','有效耗时h','节点时限h','节点状态','是否超时'];
 const rows=flows.flatMap(f=>{const t=f.ticket,s=B.byStore[t.store];return B.flowRecords(f).map(n=>[state.start,state.end,flowTime(f.cutoff),'全国虚构演示数据',t.id,s.district,s.region,s.name,t.customer,t.level,t.channel,flowTime(f.created),f.assigned==null?'':flowTime(f.assigned),f.closed==null?'':flowTime(f.closed),f.status,flowHours(f.elapsed),n.type,n.id,n.sequence,n.label,n.occurrence,n.person,n.department,flowTime(n.started),n.ended==null?'':flowTime(n.ended),flowHours(n.elapsed),flowHours(n.pause),flowHours(n.effective),n.limit==null?'':flowHours(n.limit),n.status,n.overdue?'是':'否']);});
 csv('工单节点明细_'+state.end,headers,rows);
}

function efficiencyMetrics(){
 const s=summary,p=prior,c=B.compliance(s.nodes.filter(n=>n.stage!=='等待派单'),s.start,s.end);
 return `<div class="metrics">${metric('首次联系及时率',fixed(s.first),'%',delta(s.first,p.first,'pp',false),`已首联或已到期 ${number(s.observed.length)} 单`,'first',true)}${metric('任务按时完成率',fixed(c.timely),'%',`<span class="${c.met===false?'red':c.met?'green':''}">目标 ≥${c.target}%（演示）</span>`,`本期应完成 ${number(c.due.length)} 次，按时完成 ${number(c.onTime.length)} 次；含到期未完成，排除自动派单`,'due-tasks')}${metric('审批平均有效耗时',fixed(s.approvalMean),'小时',delta(s.approvalMean,p.approvalMean),`本期已完成 ${number(s.approved.length)} 次 · 扣除有效挂起`,'approval')}${metric('审批退回率',fixed(B.pct(s.approved.filter(n=>n.returned).length,s.approved.length)),'%',`${number(s.approved.filter(n=>n.returned).length)} 次退回 / ${number(s.approved.length)} 次完成`,'每次审批独立计数 · 含重提','returned')}${metric('到期工单按时结案率',fixed(s.closure),'%',delta(s.closure,p.closure,'pp',false),`本期到期 ${number(s.due.length)} 单 · 含未结案`,'closure')}${metric('期末超时未结',number(s.overdue.length),'单',delta(s.overdue.length,p.overdue.length),`全部未结 ${number(s.open.length)} 单 · 含历史积压`,'overdue')}</div>`;
}
function efficiencyBrief(){
 const hot=B.efficiency(summary,'stage').sort((a,b)=>b.overdue.length-a.overdue.length)[0],pending=summary.pending.filter(n=>n.stage!=='等待派单'),overdue=pending.filter(n=>B.net(n,summary.end)>n.limit);
 return `<div class="brief"><span>在途任务 <strong>${pending.length}</strong></span><span>节点超时 <strong class="red">${overdue.length}</strong></span>${hot?.overdue.length?`<span>超时最多 <strong>${E(hot.name)}</strong><b class="red">${hot.overdue.length}</b></span>`:''}${act('metric','任务明细 →','data-kind="pending"','link')}</div>`;
}
function efficiencyRules(r){return r.rules.map(x=>`${x.stage} ≤${fixed(x.limit/B.H,0)} h`).join('；');}
function efficiencyLimit(r){return r.rules.length===1?`≤${fixed(r.rules[0].limit/B.H,0)} h`:'按任务规则';}
function efficiencyTable(){
 if(state.effDimension==='ticket')return ledgerView();
 effRows=B.efficiency(summary,state.effDimension).sort((a,b)=>b.overdue.length-a.overdue.length||(a.timely??101)-(b.timely??101));
 const pageCount=Math.max(1,Math.ceil(effRows.length/12));state.effPage=Math.min(state.effPage,pageCount);const shown=effRows.slice((state.effPage-1)*12,state.effPage*12),person=state.effDimension==='person';
 const drill=(r,kind,label,cls='link')=>act('eff-cohort',label,`data-key="${E(r.key)}" data-kind="${kind}"`,cls);
 return `<div class="table-scroll compliance-scroll" tabindex="0" aria-label="办理达标检核，可横向滚动"><table class="compliance-table"><thead><tr><th>${{stage:'处理环节',department:'责任部门',person:'实际办理人'}[state.effDimension]}</th>${person?'<th>所属门店 / 部门</th>':''}<th title="节点自己的时限，扣除有效挂起；混合环节逐任务判断">办理时限</th><th title="本期已完成任务的平均有效耗时，扣除有效挂起；点击查看完成任务">实际平均耗时 / h</th><th title="原型演示目标，正式上线使用业务确认的目标">目标按时完成率</th><th title="本期到期且按时完成的任务 ÷ 本期应完成任务；点击查看按时完成任务">实际按时完成率</th><th title="本期到期的超时完成与超时未完成任务 ÷ 本期应完成任务；点击查看超时任务">超时率</th><th title="规定期限在本期、截至期末已完成或已超时的任务；未到期不纳入">本期应完成 / 次</th><th title="截至所选期末仍未完成且已超时的任务，包含历史积压">超时未完成 / 次</th><th title="所选期末未完成任务中，超过自身时限最多的有效小时数；已扣有效挂起">最长超时 / h</th></tr></thead><tbody>${shown.map(r=>`<tr data-eff-key="${E(r.key)}"><td>${act('eff-detail',E(r.name),`data-key="${E(r.key)}" title="查看本期应完成任务"`,'table-name')}</td>${person?`<td>${E(r.store||r.department)}</td>`:''}<td title="${E(efficiencyRules(r))}">${efficiencyLimit(r)}</td><td data-eff-field="mean">${drill(r,'done',fixed(r.mean),'cell-link')}</td><td class="muted">≥${r.target}%</td><td data-eff-field="timely">${drill(r,'onTime',percent(r.timely),`cell-link compliance-rate ${r.met===false?'red':r.met?'green':''}`)}</td><td data-eff-field="lateRate">${drill(r,'late',percent(r.lateRate),`cell-link ${r.late.length?'red':''}`)}</td><td data-eff-field="due">${drill(r,'due',number(r.due.length),'cell-link')}</td><td data-eff-field="overdue">${drill(r,'overdue',number(r.overdue.length),`cell-link ${r.overdue.length?'red':'muted'}`)}</td><td data-eff-field="longestOverdue">${drill(r,'longest',fixed(r.longestOverdue),`cell-link ${r.overdue.length?'red':'muted'}`)}</td></tr>`).join('')||`<tr><td colspan="${person?10:9}" class="empty">当前条件没有匹配任务</td></tr>`}</tbody></table></div><div class="table-footer"><span>${effRows.length} 个${{stage:'环节',department:'部门',person:'人员'}[state.effDimension]}</span><span>${act('eff-page','‹',`data-step="-1" ${state.effPage===1?'disabled':''}`)}　${state.effPage} / ${pageCount}　${act('eff-page','›',`data-step="1" ${state.effPage===pageCount?'disabled':''}`)}</span></div>`;
}
function showEfficiencyCohort(r,kind='due'){
 const labels={due:'本期应完成任务',onTime:'本期按时完成任务',late:'本期超时任务',done:'本期已完成任务',overdue:'超时未完成任务',longest:'超时最久的未完成任务'};
 const descriptions={due:'本期到期，含超时未完成；按任务各自时限判断',onTime:`本期应完成 ${r.due.length} 次，其中按时完成 ${r.onTime.length} 次`,late:`本期应完成 ${r.due.length} 次，其中超时 ${r.late.length} 次；含超时完成与超时未完成`,done:'按完成时间统计；实际平均耗时扣除有效挂起',overdue:'截至所选期末仍未完成且超过时限，包含历史积压',longest:'截至所选期末，有效耗时超过任务时限最多的未完成任务'};
 showNodes(r.name+' · '+labels[kind],r[kind],descriptions[kind]);
}
function efficiency(){
 return `${efficiencyMetrics()}${efficiencyBrief()}
 ${card('各环节按时完成率','本期到期任务，含超时未完成；目标 ≥95%（演示）。自动派单仅在环节视角展示。',process())}
 <section class="card analysis-card"><div class="analysis-head"><h2>${state.effDimension==='ticket'?'工单流转明细':'办理达标检核'}</h2>${seg('effDimension',[['stage','按环节'],['department','按部门'],['person','按个人'],['ticket','按工单']])}</div><div id="eff-table">${efficiencyTable()}</div></section>
 
 <div class="grid equal">${card('未结工单等待时长',`截至 ${state.end} · 共 ${summary.open.length} 单，含期初结转`,aging(),act('metric','全部未结 →','data-kind="open"'))}
 ${card('派单等待与挂起','识别节点时效之外的等待因素',`<div class="mini-stats"><div><span>派单平均等待</span><b>${fixed(B.mean(summary.completed.filter(n=>n.stage==='等待派单').map(n=>B.net(n)/B.H)))}<span> 小时</span></b></div><div><span>期末待派</span><b>${summary.pending.filter(n=>n.stage==='等待派单').length}<span> 单</span></b></div><div><span>期末挂起</span><b>${summary.pending.filter(n=>B.pauseAt(n,summary.end)>0&&summary.end<n.pauseStart+n.pause).length}<span> 单</span></b></div></div><div class="card-body"><div class="note">已完成任务挂起 ${fixed(summary.completed.reduce((v,n)=>v+n.pause/B.H,0))} 小时</div></div>`,act('metric','查看久等工单 →','data-kind="longwait"'))}</div>`;
}
function customerMetrics(){const s=summary,p=prior;return `<div class="metrics">${metric('新增客诉',number(s.cohort.length),'单',delta(s.cohort.length,p.cohort.length),'按发生门店归属 · 工单去重','new',true)}${metric('每千服务人次客诉量',fixed(s.rate),'单',delta(s.rate,p.rate),`同期服务 ${number(s.volume)} 人次`,'rate')}${metric('重复投诉占比',fixed(s.repeat),'%',delta(s.repeat,p.repeat,'pp'),`本期重复标记 ${s.cohort.filter(t=>t.repeat).length} 单`,'repeat')}${metric('四 / 五级客诉',number(s.cohort.filter(t=>t.level>=4).length),'单',`占新增 ${percent(B.pct(s.cohort.filter(t=>t.level>=4).length,s.cohort.length))}`,'按客诉等级 · 优先跟进','high')}${metric('实际退赔支出',fixed((s.refund+s.compensation)/10000),'万元',delta(s.refund+s.compensation,p.refund+p.compensation),'按成功付款日 · 退款 + 赔偿','paid')}${metric('客户平均结案耗时',fixed(s.elapsedMean),'小时',delta(s.elapsedMean,p.elapsedMean),`本期结案 ${s.closed.length} 单 · 完整自然时长`,'closed')}</div>`;}
function rankRows(){return B.groups(state,state.dimension).sort((a,b)=>(b.rate??-1)-(a.rate??-1));}
function customerTable(){groupRows=rankRows();const pageCount=Math.max(1,Math.ceil(groupRows.length/10));state.page=Math.min(state.page,pageCount);const rows=groupRows.slice((state.page-1)*10,state.page*10);return `<div class="table-scroll"><table><thead><tr><th>${{district:'大区',region:'区域',store:'门店'}[state.dimension]}</th><th>新增客诉</th><th>服务人次</th><th>每千人次客诉量</th><th>较前周期 / 单</th><th>重复投诉占比</th><th>四 / 五级</th><th>超时未结</th><th>按时结案率</th><th>操作</th></tr></thead><tbody>${rows.map((r,i)=>{const p=B.summarize({...B.previous(state),[state.dimension]:r.key});const d=r.rate==null||p.rate==null||B.parse(B.previous(state).start)<B.START?null:r.rate-p.rate;return `<tr><td><span class="rank ${i<3&&state.page===1?'top':''}">${(state.page-1)*10+i+1}</span><button class="table-name" data-action="drill" data-dimension="${state.dimension}" data-key="${E(r.key)}">${E(r.name)}</button>${state.dimension==='store'?`<small style="padding-left:28px">${E(B.byStore[r.key].region)}</small>`:''}</td><td>${number(r.cohort.length)}</td><td class="muted">${number(r.volume)}</td><td><div class="progress-cell"><i><b style="width:${Math.min(100,(r.rate||0)/Math.max(...groupRows.map(x=>x.rate||0),1)*100)}%"></b></i><strong>${fixed(r.rate)}</strong></div></td><td class="${d>0?'red':'green'}">${d==null?'—':(d>0?'↑ ':d<0?'↓ ':'')+fixed(Math.abs(d))}</td><td>${percent(r.repeat)}</td><td>${r.cohort.filter(t=>t.level>=4).length}</td><td>${act('org-overdue',number(r.overdue.length),`data-key="${E(r.key)}"`,r.overdue.length?'red':'muted')}</td><td>${percent(r.closure)}</td><td>${act('drill',state.dimension==='store'?'工单 →':'下钻 →',`data-dimension="${state.dimension}" data-key="${E(r.key)}"`)}</td></tr>`;}).join('')||'<tr><td class="empty" colspan="10">没有匹配的组织，请调整筛选条件。</td></tr>'}</tbody></table></div><div class="table-footer"><span>共 ${groupRows.length} 个组织</span><span>${act('page','‹',`data-step="-1" ${state.page===1?'disabled':''}`)}　${state.page} / ${pageCount}　${act('page','›',`data-step="1" ${state.page===pageCount?'disabled':''}`)}</span></div>`;}
function donut(){const rows=B.distribution(summary.cohort,'level').sort((a,b)=>a.name-b.name),colors=['#75a4f0','#9abcf3','#7ac6c1','#e6b86e','#d98683'],total=summary.cohort.length;let running=0;const stops=rows.map(r=>{const from=running;running+=total?r.value/total*100:0;return `${colors[r.name-1]} ${from}% ${running}%`;}).join(',');return `<div class="card-body"><div class="donut-layout"><div class="donut" style="background:${total?'conic-gradient('+stops+')':'#eef2f7'}"><div class="donut-hole"><b>${number(total)}</b><small>本期新增客诉</small></div></div><div class="donut-legend">${rows.map(r=>`<button data-action="distribution" data-key="level" data-value="${r.name}"><i class="dot" style="background:${colors[r.name-1]}"></i>${r.name}级<strong>${r.value}</strong><span>${fixed(r.value/total*100,0)}%</span></button>`).join('')||'<span class="muted">暂无数据</span>'}</div></div></div>`;}
function customer(){return `${customerMetrics()}<div class="grid">${card('客诉发生趋势','观察规模变化，同时校正服务量的影响',lineChart())}${card(state.district?'组织客诉对比':'四大区客诉对比','按发生门店归属 · 点击下钻查看区域或门店',regionalCards())}</div><section class="card analysis-card"><div class="analysis-head"><h2>全国组织对比</h2>${seg('dimension',[['district','大区'],['region','区域'],['store','门店']])}</div><div id="org-table">${customerTable()}</div></section><div class="grid triple">${card('客诉原因分布','每单一个主原因 · 按新增工单统计',`<div class="card-body">${bars(B.distribution(summary.cohort,'reason'),'reason')}</div>`)}${card('来源渠道','按首次受理来源归类',`<div class="card-body">${bars(B.distribution(summary.cohort,'channel'),'channel',['#35b4a5'])}</div>`)}${card('客诉等级结构','沿用工单等级 · 四 / 五级重点跟进',donut())}</div><div class="grid equal">${card('项目客诉分布','按工单关联主项目 · 不作为项目客诉率',`<div class="card-body">${bars(B.distribution(summary.cohort,'project'),'project')}</div>`)}${card('实际支出与闭环','按成功付款日统计 · 不是方案申请金额',`<div class="mini-stats"><div><span>实际退款</span><b>${money(summary.refund)}</b></div><div><span>实际赔偿</span><b>${money(summary.compensation)}</b></div></div><div class="card-body"><div class="note">成功付款 ${summary.paid.length} 单</div></div>`,act('metric','付款明细 →','data-kind="paid"'))}</div>`;}
function render(){summary=B.summarize(state);prior=B.summarize(B.previous(state));const scroll=window.scrollY;$('#app').innerHTML=`<main class="page"><header class="header"><div class="head-left"><div class="brand-mark">${icon('chart')}</div><div><h1>全国客诉分析</h1></div></div><div class="header-actions"><span class="badge">全国演示数据</span>${act('definitions',icon('book')+'指标说明','','btn')}${act('export',icon('download')+(state.tab==='efficiency'&&state.effDimension==='ticket'?'导出节点明细':'导出当前分析'),'','btn')}</div></header>${filterUI()}<section class="dashboard"><div class="primary-tabs"><nav class="tabs" aria-label="分析视角">${[['efficiency','员工效能分析'],['customer','客诉情况分析']].map(([key,label])=>act('tab',label,`data-tab="${key}" aria-current="${state.tab===key?'page':'false'}"`,'tab '+(state.tab===key?'active':''))).join('')}</nav></div><div class="dashboard-content" aria-label="${state.tab==='efficiency'?'员工效能分析':'客诉情况分析'}内容">${state.tab==='efficiency'?efficiency():customer()}</div></section></main>`;const u=new URL(location.href);for(const k of ['tab','start','end','district','region','store','level','source','effDimension'])state[k]?u.searchParams.set(k,state[k]):u.searchParams.delete(k);history.replaceState(null,'',u);window.scrollTo(0,scroll);}
function openModal(title,sub,body,wide=false){if(!modal)returnFocus=document.activeElement;$('#modal-root').innerHTML=`<div class="modal-backdrop" data-backdrop="1"><section class="drawer ${wide?'wide':''}" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><header class="drawer-header"><div><h2 id="dialog-title">${title}</h2><p>${sub}</p></div>${act('close','×','aria-label="关闭"','close')}</header><div class="drawer-content">${body}</div></section></div>`;document.body.style.overflow='hidden';$('.drawer .close').focus();}
function close(){const was=modal;modal=null;$('#modal-root').innerHTML='';document.body.style.overflow='';returnFocus?.isConnected&&returnFocus.focus();returnFocus=null;return was;}
function definitions(){openModal('指标口径与数据边界','统一时间、分母与责任归属，才能公平比较大区、门店和员工。',`<div class="note">本原型使用固定的全国虚构数据，截止 2026.10.07 23:59。所有卡片、趋势、排名、明细由同一份样本计算；浏览原型不会修改现有工单、审批、排班或规则。</div><h3>三种时间口径</h3><dl class="definition"><dt>当期发生</dt><dd>新增、原因、渠道、等级、重复投诉均按工单创建时间归属。以工单 ID 去重；同一工单的跟进、重提和审批记录不增加客诉量。</dd><dt>当期完成</dt><dd>完成办理任务按节点完成时间；审批退回也算一次已完成审批。客户结案耗时按结案时间，实际退赔按成功付款时间。均可包含以前创建的工单。</dd><dt>期末积压</dt><dd>创建时间不晚于期末，且期末尚未结案的全部工单。含以前月份积压；历史周期重放当时期末状态。</dd></dl><h3>关键指标与计算</h3><dl class="definition"><dt>每千服务人次客诉量</dt><dd>本期新增客诉工单数 ÷ 同期同组织已履约服务人次 × 1,000。是强度指标，不是百分比，也不等于“当次服务客诉率”。等级／来源筛选只缩小分子，分母仍为该组织全部服务人次。零分母显示“—”。</dd><dt>首联及时率</dt><dd>本期首次派单且在节点首联时限内有效联系的工单数 ÷ 本期首次派单、且已联系或首联时限已到的工单数。未接通不算首联；排班待派计入客户等待，不计为个人首联耗时。转售后后的再次首联应另列事件。</dd><dt>到期工单按时结案率</dt><dd>本期整单 SLA 到期且在该截止时间前结案的工单数 ÷ 本期整单 SLA 到期工单数。已超时但尚未结案也进入分母，不用“仅已结案”的样本美化及时率。整单从创建连续计时，不扣挂起。</dd><dt>实际平均耗时</dt><dd>本期完成节点的有效耗时 = 结束 − 进入 − 有效挂起。按完成时间取样并计算算术平均；与按到期时间统计的达标率分开取样。未完成任务单列积压，退回重提按独立节点实例计数。</dd><dt>办理时限 / 按时率目标</dt><dd>办理时限沿用每条节点实例的规则快照，不混算不同环节的时限。部门、个人涉及多种规则时展示“按任务规则”。按时完成率目标暂设 ≥95%，仅为原型演示值，正式目标需按业务规则配置。</dd><dt>本期应完成任务</dt><dd>规定期限在本期、截至期末已经完成或已经超时的任务实例。有效挂起按当时已发生的时长顺延期限；已超时后的挂起不会改写首次超时所属周期。未到期任务不进入分母，即使已提前完成；自动派单不计入员工总指标、部门和个人评价。</dd><dt>按时完成率 / 超时率</dt><dd>实际按时完成率 = 本期应完成任务中按时完成数 ÷ 本期应完成数。超时率 = 同一批任务中（超时完成数 + 超时未完成数）÷ 本期应完成数。二者相加为 100%（显示可能有四舍五入差异）。到期样本为零时显示“—”。实际按时完成率按未舍入的值与目标比较，颜色提示是否达到目标。</dd><dt>超时未完成 / 最长超时</dt><dd>均为所选期末快照，包含以前周期的历史积压。最长超时 = 未完成任务中 max（有效耗时 − 自身办理时限），不是工单总等待时间。无超时积压时最长超时显示“—”。点击数字可查看对应任务，点击最长超时只显示最长的任务（并列保留）。</dd><dt>工单流转明细</dt><dd>按所选周期内有流转或期末未结的工单统计，含历史积压；按工单创建时间倒序。展示截至期末已发生的全部节点，退回重提分别记录，未流经节点不补零。分派耗时为创建至首次分派的等待时长。工单总耗时包含挂起；节点另列自然、挂起和有效耗时。穿透工单表沿用来源指标的工单范围，节点明细导出一行一个节点实例或创建、结案里程碑。</dd><dt>实际办理人 / 部门</dt><dd>归属节点发生时的责任人员与部门，不把整单全部耗时归给当前售后负责人。会签的个人任务分别分析，部门实例单独去重；原型使用串行单人任务样本。</dd><dt>重复投诉占比</dt><dd>本期标记重复投诉的新工单数 ÷ 本期全部新增客诉数；沿用现有 repeat 标记。不是客户复诉率。生产环境需统一客户、问题和时间窗口的重复判定。</dd><dt>退款 / 赔偿</dt><dd>仅计成功付款，分别汇总实际退款和赔偿；不计失败流水、申请额、审批金额或商品置换价值。生产接口金额单位为分，展示时除以 100。</dd><dt>比较周期 / 缺失值</dt><dd>比较紧邻当前周期、天数相等的前一周期。百分率变化用百分点 pp；客诉强度表格用“单 / 千人次”的绝对差。缺分母或无样本显示“—”，不显示为零。评估人员时需结合本期应完成任务量，避免单凭少量任务的百分比判断。</dd></dl><h3>现有代码可承接的数据</h3><dl class="definition"><dt>工单与组织</dt><dd><code>shared-store.js → tickets</code><br>现有 store、channel、level、repeat、created、closed、deadline 可用。需补齐稳定门店 ID、大区 / 区域 ID 及历史归属快照。</dd><dt>节点与审批</dt><dd><code>solution-flow.js / external-approvals.js</code><br>可使用执行节点开始 / 完成、节点负责人、审批事件和结果；需要把多轮审批及多人员任务转换成统一的节点实例 / 个人任务事实表。外部审批个体任务时间缺失时不能估算个人效率。</dd><dt>等待与挂起</dt><dd><code>aftercare-schedule.js / suspension-control.js</code><br>已有实际分派、有效首联、节点计时历史及有效挂起信息。需要补充历史转派责任分段、异常期间、营业 / 自然时间基准的统一字段。</dd><dt>实际付款</dt><dd><code>ticket-operations.js / solution-flow.js</code><br>成功支付与方案版本关联，避免多次付款或失败重试重复累计。退款、赔偿应与支付事实逐笔核对。</dd></dl><h3>上线前必须补齐</h3><p>① 全国三级组织维表及历史归属；② 门店每日已履约服务人次；③ 标准化一级 / 二级客诉原因和主项目；④ 节点 / 审批 / 转派事件事实表；⑤ 付款分类核对及数据完整性监控。</p><p>全国、区域和门店权限应由服务端授权。已结案不代表客户满意；本原型不展示没有采集依据的满意度、流失率或挽回收入。演示门店及大区划分用于讨论信息架构。</p>`);modal={type:'definitions'};}
function metricDetail(kind){const s=summary;const map={new:['本期新增客诉',s.cohort,'按创建日期统计 · 一行一张工单'],rate:['每千服务人次客诉量 · 分子明细',s.cohort,`新增 ${s.cohort.length} 单 ÷ 服务 ${number(s.volume)} 人次 × 1,000 = ${fixed(s.rate)} 单 / 千人次`],first:['首联时效样本',s.observed,'本期首次派单且已有效联系或首联时限已到；未到期未联系不纳入'],closure:['本期整单到期工单',s.due,'分母包含到期未结工单；是否按时结案按整单时限快照判断'],overdue:['期末超时未结工单',s.overdue,'按整单 SLA 判断 · 包含以前周期积压'],open:['期末全部未结工单',s.open,'期末快照 · 含历史积压'],longwait:['客户等待超过 72 小时',s.open.filter(t=>s.end-t.created>=72*B.H),'自然时间连续计时 · 不扣挂起'],closed:['本期已结案工单',s.closed,'按结案日期统计 · 可包含以前创建工单'],repeat:['本期重复投诉',s.cohort.filter(t=>t.repeat),'按新工单的重复投诉标记'],high:['本期四 / 五级客诉',s.cohort.filter(t=>t.level>=4),'按创建日期与客诉等级统计'],paid:['本期实际退赔工单',s.paid,'按成功付款日期统计 · 仅现金退款与赔偿']};if(kind==='approval')return showNodes('本期已完成审批',s.approved,'按审批实例完成日期统计 · 退回重提独立计数');if(kind==='returned')return showNodes('本期退回审批',s.approved.filter(n=>n.returned),'退回也是已完成审批；重提产生新的审批实例');if(kind==='due-tasks')return showNodes('本期应完成办理任务',B.compliance(s.nodes.filter(n=>n.stage!=='等待派单'),s.start,s.end).due,'本期到期，含超时未完成；排除自动派单');if(kind==='pending')return showNodes('期末在途办理任务',s.pending.filter(n=>n.stage!=='等待派单'),'期末已进入且未完成节点 · 含历史积压');const [title,rows,sub]=map[kind]||map.new;showTickets(title,rows,sub,kind);}
function showTickets(title,rows,sub,kind='default'){openModal(title,`${E(scopeName())} · ${state.start} — ${state.end} · ${sub}`,`<div class="drawer-toolbar"><input type="search" data-input="detail-search" aria-label="搜索工单" placeholder="搜索工单号、客户或门店"><span class="criteria">${rows.length} 张工单 · 全国演示样本</span>${act('export-detail','导出明细','','btn')}</div><div id="detail-table"></div>`,true);modal={type:'tickets',title,rows,sub,kind,search:'',page:1};renderDetailTable();}
function showNodes(title,rows,sub){openModal(title,`${E(scopeName())} · ${state.start} — ${state.end} · ${sub}`,`<div class="drawer-toolbar"><input type="search" data-input="detail-search" aria-label="搜索任务" placeholder="搜索工单、人员、环节或门店"><span class="criteria">${rows.length} 个任务实例 / ${new Set(rows.map(n=>n.ticketId)).size} 张工单</span>${act('export-detail','导出明细','','btn')}</div><div id="detail-table"></div>`,true);modal={type:'nodes',title,rows,sub,search:'',page:1};renderDetailTable();}
function detailRows(){return modal.rows.filter(r=>{const t=modal.type==='nodes'?B.byTicket[r.ticketId]:r;return !modal.search||[t.id,t.customer,B.byStore[t.store].name,r.person,r.stage].some(x=>String(x||'').includes(modal.search));}).slice().sort((a,b)=>(b.started||b.created)-(a.started||a.created));}
function ticketStatus(t){const n=B.activeNode(t,summary.end);return t.closed<=summary.end?'已结案':n?.stage==='等待派单'?'待派单':n?.pause&&summary.end>=n.pauseStart&&summary.end<n.pauseStart+n.pause?'已挂起':n?.stage||'待处理';}
function ticketOutcome(t,kind){if(kind==='paid')return money(t.refund+t.compensation);if(kind==='first')return t.contact>summary.end?'首联已超时':`${fixed((t.contact-t.assigned)/B.H)}h / ${t.firstLimit/B.H}h`;if(kind==='closure')return t.closed<=t.created+t.limit?'按时结案':t.closed>summary.end?'到期未结':'超时结案';const end=Math.min(t.closed,summary.end);return fixed((end-t.created)/B.H)+' h';}
function nodeSnapshot(node){return B.ticketFlow(B.byTicket[node.ticketId],summary.end).nodes.find(n=>n.id===node.id);}
function nodeResult(node){if(node.status==='已完成')return node.overdue?'超时完成':'按时完成';return (node.returned?'审批退回':node.status)+(node.overdue?' · 超时':'');}
function nodeTaskTable(nodes){
 const columns=[['工单号',190],['环节',110],['责任人',100],['进入时间',170],['结束时间',170],['耗时 / h',90],['挂起 / h',90],['有效耗时 / h',110],['时限 / h',90],['结果',140],['门店',140],['部门',130]];
 return `<div class="table-scroll node-detail-scroll" tabindex="0" aria-label="节点明细，可横向滚动"><table class="node-detail-table" style="width:${columns.reduce((sum,c)=>sum+c[1],0)}px"><colgroup>${columns.map(c=>`<col style="width:${c[1]}px">`).join('')}</colgroup><thead><tr>${columns.map(([name])=>`<th>${name}</th>`).join('')}</tr></thead><tbody>${nodes.map(r=>{const t=B.byTicket[r.ticketId],n=nodeSnapshot(r);return `<tr data-detail-node="${E(n.id)}"><td>${act('ticket',E(t.id),`data-id="${t.id}"`)}</td><td>${E(n.label)}</td><td>${E(n.person)}</td><td data-field="started" title="规定完成时间：${flowTime(B.nodeDeadline(r,summary.end))}">${flowTime(n.started)}</td><td data-field="ended">${n.ended==null?'未结束':flowTime(n.ended)}</td><td data-field="elapsed">${flowHours(n.elapsed)}</td><td data-field="pause">${flowHours(n.pause)}</td><td data-field="effective" class="${n.overdue?'red':''}">${flowHours(n.effective)}</td><td>${flowHours(n.limit)}</td><td data-field="result" class="${n.overdue?'red':''}">${E(nodeResult(n))}</td><td>${E(B.byStore[t.store].name)}</td><td>${E(n.department)}</td></tr>`;}).join('')||`<tr><td colspan="${columns.length}" class="empty">暂无匹配明细</td></tr>`}</tbody></table></div>`;
}
function renderDetailTable(){
 const rows=detailRows(),pages=Math.max(1,Math.ceil(rows.length/15));modal.page=Math.min(modal.page,pages);
 const shown=rows.slice((modal.page-1)*15,modal.page*15),tickets=modal.type==='tickets';
 const body=tickets?flowTable(shown.map(t=>B.ticketFlow(t,summary.end)),modal.kind,rows.map(t=>B.ticketFlow(t,summary.end))):nodeTaskTable(shown);
 $('#detail-table').innerHTML=body+`<div class="table-footer"><span>匹配 ${rows.length} ${tickets?'张工单':'个任务'}</span><span>${act('detail-page','‹',`data-step="-1" ${modal.page===1?'disabled':''}`)}　${modal.page} / ${pages}　${act('detail-page','›',`data-step="1" ${modal.page===pages?'disabled':''}`)}</span></div>`;
}
function ticketDetail(id){
 const t=B.byTicket[id],back=modal,s=B.byStore[t.store],flow=B.ticketFlow(t,summary.end);if(!flow)return;
 openModal('工单流转明细',`${E(t.id)} · ${E(s.district)} / ${E(s.region)} / ${E(s.name)} · 截至 ${flowTime(summary.end)}`,
 `<div class="drawer-toolbar">${back?act('back-detail','← 返回分析明细'):'<span></span>'}${act('export-flow','导出本单节点','','btn')}</div>
 <div class="detail-kpis"><div><small>创建时间</small><b class="flow-date">${flowTime(flow.created)}</b></div><div><small>结案时间</small><b class="flow-date">${flow.closed==null?'未结案':flowTime(flow.closed)}</b></div><div><small>总自然耗时</small><b>${flowHours(flow.elapsed)} h</b></div><div><small>期末状态</small><b class="flow-date">${E(flow.status)}</b></div></div>
 ${flowNodeTable(flow)}<p>自然耗时 − 挂起时长 = 有效耗时；未结束节点计算至所选期末。时间为北京时间。</p>`,true);
 modal={type:'ticket',back,flow};
}
function drill(dimension,key){if(dimension==='store'){const s=B.summarize({...state,store:key});showTickets(B.byStore[key].name+' · 本期新增客诉',s.cohort,'当前全局筛选 + 所选门店；按创建日期统计');return;}state.tab='customer';state[dimension]=key;state.store='';if(dimension==='district'){state.region='';state.dimension='region';}else{state.district=B.stores.find(s=>s.region===key).district;state.dimension='store';}state.page=1;state.effPage=1;render();window.scrollTo(0,0);}
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2600);}
function csv(filename,headers,rows){const safe=v=>{const s=String(v??'');return '"'+(/^[=+@\-]/.test(s)?"'"+s:s).replaceAll('"','""')+'"';};const blob=new Blob(['\ufeff'+[headers,...rows].map(r=>r.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出当前筛选范围的 CSV');}
function exportAnalysis(){if(state.tab==='efficiency'&&state.effDimension==='ticket')return exportFlows(ledgerRows());const context=[state.start,state.end,scopeName(),state.level||'全部',state.source||'全部','全国虚构演示数据'],h=['开始日期','结束日期','组织范围','等级','来源','数据类型'];if(state.tab==='efficiency'){csv('办理达标检核_'+state.end,[...h,'分析对象','部门','门店','办理时限规则','实际平均有效耗时h','目标按时完成率%（演示）','实际按时完成率%','超时率%','本期应完成次数','本期按时完成次数','本期超时次数','期末超时未完成次数（含历史积压）','期末最长有效超时h','平均耗时完成样本数'],effRows.map(r=>[...context,r.name,r.department,r.store,efficiencyRules(r),fixed(r.mean),r.target,fixed(r.timely),fixed(r.lateRate),r.due.length,r.onTime.length,r.late.length,r.overdue.length,fixed(r.longestOverdue),r.done.length]));}else{const rows=rankRows();csv('全国客诉分析_'+state.end,[...h,'组织','新增客诉','服务人次','每千人次客诉量','重复投诉占比%','期末未结','超时未结','到期按时结案率%','实际退款元','实际赔偿元'],rows.map(r=>[...context,r.name,r.cohort.length,r.volume,fixed(r.rate),fixed(r.repeat),r.open.length,r.overdue.length,fixed(r.closure),r.refund,r.compensation]));}}
function exportDetail(){
 if(modal.type==='tickets')return exportFlows(detailRows().map(t=>B.ticketFlow(t,summary.end)));
 const headers=['统计开始日期','统计结束日期','快照时间(北京时间)','节点实例ID','工单号','环节','责任人','进入时间','结束时间','耗时 / h','挂起 / h','有效耗时 / h','时限 / h','结果','门店','部门'];
 const rows=detailRows().map(r=>{const t=B.byTicket[r.ticketId],n=nodeSnapshot(r);return [state.start,state.end,flowTime(summary.end),n.id,t.id,n.label,n.person,flowTime(n.started),n.ended==null?'':flowTime(n.ended),flowHours(n.elapsed),flowHours(n.pause),flowHours(n.effective),flowHours(n.limit),nodeResult(n),B.byStore[t.store].name,n.department];});
 csv(modal.title+'_'+state.end,headers,rows);
}
function customDate(){returnFocus=document.activeElement;$('#modal-root').innerHTML=`<div class="modal-backdrop center" data-backdrop="1"><form class="date-modal" id="date-form" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><h2 id="dialog-title">自定义统计周期</h2><div class="note">演示可选 2026.08.25 — 2026.10.07，比较周期为紧邻的前一等长周期。</div><label>开始日期<input name="start" type="date" min="2026-08-25" max="2026-10-07" value="${state.start}" required></label><label>结束日期<input name="end" type="date" min="2026-08-25" max="2026-10-07" value="${state.end}" required></label><div class="date-error" role="alert"></div><div class="actions">${act('cancel-date','取消','type="button"','btn')}<button type="submit" class="btn primary">应用日期</button></div></form></div>`;modal={type:'date'};document.body.style.overflow='hidden';$('[name=start]').focus();}
document.addEventListener('click',event=>{const el=event.target.closest('[data-action]');if(!el){if(event.target.dataset.backdrop){close();render();}return;}const a=el.dataset.action,k=el.dataset.key;
 if(a==='tab'){state.tab=el.dataset.tab;render();window.scrollTo(0,0);}else if(a==='reset'){Object.assign(state,{start:'2026-09-08',end:'2026-10-07',period:'30',district:'',region:'',store:'',level:'',source:'',ticketSearch:'',page:1,effPage:1});render();}
 else if(a==='definitions')definitions();else if(a==='close'){close();}else if(a==='segment'){state[el.dataset.key]=el.dataset.value;state.page=1;state.effPage=1;render();}
 else if(a==='metric')metricDetail(el.dataset.kind);else if(a==='drill')drill(el.dataset.dimension,k);
 else if(a==='scope'){const dim=el.dataset.dimension;if(dim==='all'){state.district='';state.region='';state.dimension='district';}if(dim==='district'){state.region='';state.dimension='region';}if(dim==='region')state.dimension='store';state.store='';state.page=1;state.effPage=1;render();}
 else if(a==='stage'){const r=B.efficiency(summary,'stage').find(r=>r.key===k);if(r)showEfficiencyCohort(r);else showNodes(k+' · 本期应完成任务',[],'当前筛选无到期任务');}
 else if(a==='eff-detail'||a==='eff-cohort'){const r=effRows.find(r=>r.key===k);showEfficiencyCohort(r,a==='eff-detail'?'due':el.dataset.kind);}
 else if(a==='distribution'){const value=el.dataset.value;showTickets(value+(k==='level'?'级':'' )+' · 本期客诉',summary.cohort.filter(t=>String(t[k])===value),'当前全局筛选 + 所选结构维度');}
 else if(a==='aging'){const min=Number(el.dataset.min),max=Number(el.dataset.max);showTickets(`客户等待 ${min}h${Number.isFinite(max)?'–'+max+'h':' 以上'}`,summary.open.filter(t=>{const h=(summary.end-t.created)/B.H;return h>=min&&h<max;}),'期末未结工单 · 连续自然时间');}
 else if(a==='org-overdue'){const r=groupRows.find(r=>r.key===k);showTickets(r.name+' · 超时未结',r.overdue,'当前全局筛选 + 所选组织 · 含历史积压');}
 else if(a==='ledger-page'){state.effPage+=Number(el.dataset.step);$('#ledger-table').innerHTML=ledgerPage();}
 else if(a==='export-flow')exportFlows([modal.flow]);
 else if(a==='eff-page'){state.effPage+=Number(el.dataset.step);$('#eff-table').innerHTML=efficiencyTable();}
 else if(a==='page'){state.page+=Number(el.dataset.step);$('#org-table').innerHTML=customerTable();}
 else if(a==='detail-page'){modal.page+=Number(el.dataset.step);renderDetailTable();$('.drawer-content').scrollTo(0,0);}
 else if(a==='ticket')ticketDetail(el.dataset.id);
 else if(a==='back-detail'){const b=modal.back;if(b.type==='tickets')showTickets(b.title,b.rows,b.sub,b.kind);else showNodes(b.title,b.rows,b.sub);modal.search=b.search;modal.page=b.page;$('[data-input=detail-search]').value=b.search;renderDetailTable();}
 else if(a==='export')exportAnalysis();else if(a==='export-detail')exportDetail();else if(a==='cancel-date'){close();render();}
});
document.addEventListener('change',event=>{const k=event.target.dataset.filter;if(!k)return;if(k==='period'&&event.target.value==='custom'){customDate();return;}state[k]=event.target.type==='checkbox'?event.target.checked:event.target.value;state.page=1;state.effPage=1;
 if(k==='period'){const p=state.period;state.start=p==='7'?'2026-10-01':p==='30'?'2026-09-08':p==='month'?'2026-10-01':'2026-09-01';state.end=p==='last'?'2026-09-30':'2026-10-07';}
 if(k==='district'){state.region='';state.store='';}if(k==='region'){state.store='';if(state.region)state.district=B.stores.find(s=>s.region===state.region).district;}if(k==='store'&&state.store){const s=B.byStore[state.store];state.district=s.district;state.region=s.region;}
 render();
});
document.addEventListener('input',event=>{if(event.target.dataset.input==='ledger-search'){state.ticketSearch=event.target.value;state.effPage=1;$('#ledger-table').innerHTML=ledgerPage();}if(event.target.dataset.input==='detail-search'){modal.search=event.target.value;modal.page=1;renderDetailTable();}});
document.addEventListener('submit',event=>{if(event.target.id!=='date-form')return;event.preventDefault();const values=new FormData(event.target),start=values.get('start'),end=values.get('end');if(start>end){$('.date-error').textContent='结束日期不能早于开始日期。';return;}if(B.parse(start)<B.parse('2026-08-25')||B.parse(end)>B.parse('2026-10-07')){$('.date-error').textContent='请选择演示数据覆盖范围内的日期。';return;}state.start=start;state.end=end;state.period='custom';state.page=1;close();render();});
document.addEventListener('keydown',event=>{if(!modal)return;if(event.key==='Escape'){close();render();}if(event.key==='Tab'){const focusable=[...$('#modal-root').querySelectorAll('button:not(:disabled),input,select,a[href]')];const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}});
render();
})();
