'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),{pathToFileURL}=require('node:url'),{chromium}=require('playwright'),B=require('./bi-data.js');
const base=path.resolve(__dirname,'..'),output=process.env.QA_OUTPUT||'/tmp/complaint-bi-qa';fs.mkdirSync(output,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const url=pathToFileURL(path.join(__dirname,'bi.html')).href;await page.goto(url+'?tab=overview');assert.equal(new URL(page.url()).searchParams.get('tab'),'efficiency');assert.equal(await page.locator('.tabs [data-action=tab]').count(),2);assert.equal(await page.locator('[data-tab=overview]').count(),0);
 const expected=B.summarize({start:'2026-09-08',end:'2026-10-07'});assert.equal(await page.locator('[data-kind=first] .metric-value').innerText(),expected.first.toFixed(1)+'%');assert.equal(await page.locator('[data-kind=overdue] .metric-value').innerText(),expected.overdue.length+'单');await page.locator('[data-kind=closure]').click();await page.locator('#detail-table table').waitFor();await page.keyboard.press('Escape');await page.locator('[data-action=aging]').first().click();await page.locator('#detail-table table').waitFor();await page.keyboard.press('Escape');await page.locator('.tabs [data-tab=customer]').click();assert.equal(await page.locator('.chart-wrap svg').count(),1);assert.equal(await page.locator('.region-card').count(),4);assert.equal(await page.locator('.metric-value').first().innerText(),expected.cohort.length.toLocaleString('zh-CN')+'单');
 await page.evaluate(()=>localStorage.setItem('meiye.complaint.unified.v1','{"biPreservationProbe":true}'));
 const preserved=await page.evaluate(()=>localStorage.getItem('meiye.complaint.unified.v1'));
 await page.screenshot({path:path.join(output,'customer-trend.png'),fullPage:true});
 await page.locator('[data-action=metric][data-kind=new]').click();await page.locator('[data-action=ticket]').first().click();await page.locator('.flow-detail-table [data-flow-node]').first().waitFor();assert.match(await page.locator('.flow-detail-table').innerText(),/工单创建/);assert.match(await page.locator('.flow-detail-table').innerText(),/结束时间/);await page.locator('[data-action=back-detail]').click();assert.equal(await page.locator('[data-input=detail-search]').count(),1);await page.locator('[data-input=detail-search]').fill('NO SUCH TICKET');assert.match(await page.locator('#detail-table').innerText(),/暂无匹配工单/);await page.keyboard.press('Escape');
 await page.locator('.tabs [data-tab=efficiency]').click();await page.locator('[data-key=effDimension][data-value=person]').click();assert(!/自动派单/.test(await page.locator('.table-scroll tbody').innerText()));await page.locator('[data-action=eff-detail]').first().click();await page.locator('#detail-table table').waitFor();await page.keyboard.press('Escape');await page.locator('[data-key=effDimension][data-value=stage]').click();await page.screenshot({path:path.join(output,'efficiency.png'),fullPage:true});
 // Targets and exact drill-through cohorts stay aligned with the exported review table.
 const nationalCompliance=B.compliance(expected.nodes.filter(n=>n.stage!=='等待派单'),expected.start,expected.end);
 assert.equal(await page.locator('[data-kind="due-tasks"] .metric-value').innerText(),nationalCompliance.timely.toFixed(1)+'%');
 assert(!/P90/.test(await page.locator('.dashboard-content').innerText()));
 assert.deepEqual(await page.locator('.compliance-table thead th').allTextContents(),['处理环节','办理时限','实际平均耗时 / h','目标按时完成率','实际按时完成率','超时率','本期应完成 / 次','超时未完成 / 次','最长超时 / h']);
 const review=B.efficiency(expected,'stage').find(r=>r.key==='售后办理');
 const reviewRow=page.locator('[data-eff-key="售后办理"]');
 for(const [field,value] of [['mean',review.mean.toFixed(1)],['timely',review.timely.toFixed(1)+'%'],['lateRate',review.lateRate.toFixed(1)+'%'],['due',review.due.length.toLocaleString('zh-CN')],['overdue',review.overdue.length.toLocaleString('zh-CN')],['longestOverdue',review.longestOverdue.toFixed(1)]])assert.equal(await reviewRow.locator('[data-eff-field='+field+']').innerText(),value);
 assert.equal(await page.locator('.compliance-table tbody small,.compliance-table tbody br').count(),0);
 assert(await page.locator('.compliance-table tbody tr').evaluateAll(rows=>rows.every(r=>r.getBoundingClientRect().height<=48)));
 for(const kind of ['due','onTime','late','done','overdue','longest']){
  await reviewRow.locator('[data-action=eff-cohort][data-kind='+kind+']').click();
  assert.match(await page.locator('.drawer-toolbar .criteria').innerText(),new RegExp('^'+review[kind].length+' 个任务实例'));
  const ids=await page.locator('[data-detail-node]').evaluateAll(rows=>rows.map(r=>r.dataset.detailNode));
  assert.deepEqual(ids,review[kind].slice().sort((a,b)=>b.started-a.started).slice(0,15).map(n=>n.id));
  if(kind==='late'){
   const pendingLate=review.late.find(n=>n.ended>expected.end);assert(pendingLate);
   await page.locator('[data-input=detail-search]').fill(pendingLate.ticketId);
   assert.equal(await page.locator('[data-detail-node="'+pendingLate.id+'"] [data-field=ended]').innerText(),'未结束');
  }
  await page.keyboard.press('Escape');
 }
 const complianceDownloadPromise=page.waitForEvent('download');await page.locator('[data-action=export]').click();const complianceDownload=await complianceDownloadPromise,complianceFile=path.join(output,'compliance-export.csv');await complianceDownload.saveAs(complianceFile);
 const complianceCSV=fs.readFileSync(complianceFile,'utf8');assert.match(complianceCSV,/目标按时完成率/);assert.match(complianceCSV,/期末超时未完成次数/);assert(!complianceCSV.includes('P90'));assert(!complianceCSV.includes('达标情况'));
 await page.locator('[data-key=effDimension][data-value=department]').click();assert.match(await page.locator('[data-eff-key="售后服务部"]').innerText(),/按任务规则/);
 await page.locator('[data-key=effDimension][data-value=person]').click();assert.equal(await page.locator('.compliance-table thead th').count(),10);assert.equal(await page.locator('.compliance-table tbody small,.compliance-table tbody br').count(),0);
 await page.locator('[data-key=effDimension][data-value=stage]').click();
 await page.locator('[data-action=tab][data-tab=efficiency]').focus();await page.screenshot({path:path.join(output,'compliance.png'),fullPage:true});
 // Node drawers share the same snapshot-safe time fields and single-line rows.
 await page.locator('[data-action=metric][data-kind=pending]').click();
 assert.deepEqual(await page.locator('.node-detail-table thead th').allTextContents(),['工单号','环节','责任人','进入时间','结束时间','耗时 / h','挂起 / h','有效耗时 / h','时限 / h','结果','门店','部门']);
 const pausedTask=expected.pending.find(n=>n.stage!=='等待派单'&&B.pauseAt(n,expected.end)>0),pausedSnapshot=B.ticketFlow(B.byTicket[pausedTask.ticketId],expected.end).nodes.find(n=>n.id===pausedTask.id);
 await page.locator('[data-input=detail-search]').fill(pausedTask.ticketId);const nodeRow=page.locator('[data-detail-node="'+pausedTask.id+'"]');
 assert.equal(await nodeRow.locator('[data-field=ended]').innerText(),'未结束');
 for(const field of ['elapsed','pause','effective'])assert.equal(await nodeRow.locator('[data-field='+field+']').innerText(),(pausedSnapshot[field]/B.H).toFixed(2));
 assert.equal(await nodeRow.locator('small,br,div').count(),0);assert((await nodeRow.boundingBox()).height<=48);
 const nodeDownloadPromise=page.waitForEvent('download');await page.locator('[data-action=export-detail]').click();const nodeDownload=await nodeDownloadPromise,nodeFile=path.join(output,'node-detail.csv');await nodeDownload.saveAs(nodeFile);
 const nodeCSV=fs.readFileSync(nodeFile,'utf8').trim().split(/\r?\n/).map(line=>[...line.matchAll(/"((?:[^" ]| |"")*)"(?:,|$)/g)].map(m=>m[1].replaceAll('""','"')));
 assert.equal(nodeCSV.length,2);const nodeExport=Object.fromEntries(nodeCSV[0].map((h,i)=>[h,nodeCSV[1][i]]));assert.equal(nodeExport['结束时间'],'');assert.equal(nodeExport['挂起 / h'],(pausedSnapshot.pause/B.H).toFixed(2));assert.equal(nodeExport['有效耗时 / h'],(pausedSnapshot.effective/B.H).toFixed(2));assert(nodeExport['结果']);
 await page.keyboard.press('Escape');await page.locator('[data-action=metric][data-kind=returned]').click();const returnedTask=expected.approved.find(n=>n.returned);await page.locator('[data-input=detail-search]').fill(returnedTask.ticketId);const returnedRow=page.locator('[data-detail-node="'+returnedTask.id+'"]');
 assert.equal(await returnedRow.locator('[data-field=ended]').innerText(),new Date(returnedTask.ended+8*B.H).toISOString().slice(0,19).replace('T',' '));assert.match(await returnedRow.locator('[data-field=result]').innerText(),/审批退回/);await page.keyboard.press('Escape');
 await page.locator('[data-action=metric][data-kind=pending]').click();await page.waitForFunction(()=>getComputedStyle(document.querySelector('#toast')).opacity==='0');await page.locator('.drawer').screenshot({path:path.join(output,'node-detail.png')});await page.keyboard.press('Escape');
 await page.locator('[data-key=effDimension][data-value=ticket]').click();
 assert.equal(await page.locator('#ledger-table [data-flow-ticket]').count(),10);assert.match(await page.locator('#ledger-table thead').innerText(),/工单创建/);assert.match(await page.locator('#ledger-table thead').innerText(),/采购办理/);assert.equal(await page.locator('#ledger-table tbody small,#ledger-table tbody br,#ledger-table tbody div').count(),0);assert(await page.locator('#ledger-table .flow-scroll').evaluate(el=>el.scrollWidth>el.clientWidth));assert(await page.locator('#ledger-table tbody tr').evaluateAll(rows=>rows.every(r=>r.getBoundingClientRect().height<=48)));assert.match(await page.locator('#ledger-table thead').innerText(),/进入时间/);assert.match(await page.locator('#ledger-table thead').innerText(),/结束时间/);
 const firstTicket=await page.locator('#ledger-table [data-flow-ticket]').first().getAttribute('data-flow-ticket');await page.locator('[data-action=ledger-page][data-step="1"]').click();assert.notEqual(await page.locator('#ledger-table [data-flow-ticket]').first().getAttribute('data-flow-ticket'),firstTicket);
 const reentry=B.ticketFlows(expected).find(f=>f.closed!=null&&f.nodes.filter(n=>n.stage==='方案审批').length>1);
 await page.locator('[data-input=ledger-search]').fill(reentry.ticket.id);assert.equal(await page.locator('#ledger-table [data-flow-ticket]').count(),1);assert.match(await page.locator('#ledger-table thead').innerText(),/方案审批 · 第 2 次/);
 await page.locator('#ledger-table [data-action=ticket]').click();assert.equal(await page.locator('.flow-detail-table [data-flow-node]').count(),B.flowRecords(reentry).length);assert.match(await page.locator('.flow-detail-table').innerText(),/工单结案/);await page.keyboard.press('Escape');
 const flowDownloadPromise=page.waitForEvent('download');await page.locator('[data-action=export]').click();const flowDownload=await flowDownloadPromise,flowFile=path.join(output,'flow-export.csv');await flowDownload.saveAs(flowFile);const flowCsv=fs.readFileSync(flowFile,'utf8');assert.equal(flowCsv.trim().split('\n').length,B.flowRecords(reentry).length+1);assert.match(flowCsv,/节点实例ID/);assert.match(flowCsv,/挂起时长h/);assert.equal((flowCsv.match(/"方案审批"/g)||[]).length,2);
 await page.locator('[data-input=ledger-search]').fill('不存在的工单');assert.match(await page.locator('#ledger-table').innerText(),/暂无匹配工单/);await page.locator('[data-input=ledger-search]').fill('');await page.locator('[data-action=tab][data-tab=efficiency]').focus();await page.waitForFunction(()=>!document.querySelector('#toast').classList.contains('show'));await page.locator('.analysis-card').screenshot({path:path.join(output,'ticket-ledger.png')});
 const carryover=B.ticketFlows(expected).find(f=>f.created<expected.start&&f.closed==null);await page.locator('[data-input=ledger-search]').fill(carryover.ticket.id);assert.equal(await page.locator('#ledger-table [title="期初结转工单"]').count(),1);assert.match(await page.locator('#ledger-table').innerText(),/未结束/);await page.locator('[data-input=ledger-search]').fill('');
 await page.reload();assert.equal(await page.locator('[data-key=effDimension][data-value=ticket]').getAttribute('aria-pressed'),'true');await page.locator('[data-key=effDimension][data-value=stage]').click();
 await page.locator('.tabs [data-tab=customer]').click();await page.locator('[data-key=dimension][data-value=region]').click();assert.equal(await page.locator('#org-table tbody tr').count(),10);await page.locator('[data-action=page][data-step="1"]').click();assert.equal(await page.locator('#org-table tbody tr').count(),2);await page.locator('[data-key=dimension][data-value=district]').click();await page.locator('.table-name').filter({hasText:'华东大区'}).click();assert.equal(await page.locator('[data-filter=district]').inputValue(),'华东大区');assert.equal(await page.locator('#org-table tbody tr').count(),3);await page.locator('.table-name').filter({hasText:'沪苏区域'}).click();assert.equal(await page.locator('#org-table tbody tr').count(),4);
 await page.locator('[data-filter=source]').selectOption('微动');await page.locator('[data-filter=level]').selectOption('5');const scoped=B.summarize({start:'2026-09-08',end:'2026-10-07',district:'华东大区',region:'沪苏区域',source:'微动',level:'5'});assert.equal(await page.locator('.metric-value').first().innerText(),scoped.cohort.length+'单');assert.equal(await page.locator('#org-table tbody tr').count(),4);
 const downloadPromise=page.waitForEvent('download');await page.locator('[data-action=export]').click();const download=await downloadPromise;const file=path.join(output,'export.csv');await download.saveAs(file);const csv=fs.readFileSync(file,'utf8');assert.match(csv,/上海徐汇店/);assert.match(csv,/上海静安店/);assert.match(csv,/南京新街口店/);assert(!csv.includes('杭州湖滨店'));
 await page.locator('[data-action=reset]').click();await page.locator('[data-filter=period]').selectOption('custom');await page.locator('[name=start]').fill('2026-10-07');await page.locator('[name=end]').fill('2026-10-01');await page.locator('#date-form [type=submit]').click();assert.match(await page.locator('.date-error').innerText(),/结束日期不能早于开始日期/);await page.locator('[name=start]').fill('2026-09-01');await page.locator('[name=end]').fill('2026-09-30');await page.locator('#date-form [type=submit]').click();assert.equal(await page.locator('.metric-value').first().innerText(),B.summarize({start:'2026-09-01',end:'2026-09-30'}).cohort.length.toLocaleString('zh-CN')+'单');await page.reload();assert.equal(await page.locator('[data-filter=period]').inputValue(),'custom');
 await page.locator('[data-action=definitions]').first().click();await page.locator('.definition').first().waitFor();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>localStorage.getItem('meiye.complaint.unified.v1')),preserved);
 await page.locator('[data-action=reset]').click();await page.screenshot({path:path.join(output,'customer.png'),fullPage:true});
 for(const width of [1440,1024,390,320]){await page.setViewportSize({width,height:900});for(const tab of ['efficiency','customer']){await page.locator('.tabs [data-tab='+tab+']').click();assert.equal(await page.locator('.tab-no,[data-filter=effSort],[data-filter=effStage],[data-filter=sort],[data-filter=onlyOverdue],[data-input=org-search]').count(),0);const centered=await page.locator('.analysis-head .segmented').evaluate(el=>{const a=el.getBoundingClientRect(),b=el.closest('.analysis-card').getBoundingClientRect();return Math.abs(a.x+a.width/2-b.x-b.width/2)<1;});assert(centered,`centered analysis tabs ${width} ${tab}`);assert(await page.locator('.tabs').evaluate(el=>{const a=el.getBoundingClientRect(),b=el.closest('.page').getBoundingClientRect();return Math.abs(a.x+a.width/2-b.x-b.width/2)<1;}),`centered primary tabs ${width}`);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)){console.log(await page.evaluate(()=>({w:innerWidth,html:document.documentElement.scrollWidth,items:[...document.querySelectorAll('body *')].filter(e=>!e.closest('.table-scroll')).map(e=>({cls:e.className,tag:e.tagName,r:e.getBoundingClientRect().right,text:e.textContent.slice(0,40)})).filter(e=>e.r>innerWidth)})));await page.screenshot({path:'/tmp/bi-failing-width.png'});}assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`no overflow ${width} ${tab}`);if(tab==='efficiency'){await page.locator('[data-key=effDimension][data-value=ticket]').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`no ledger overflow ${width}`);await page.locator('[data-key=effDimension][data-value=stage]').click();}}if(width===390)await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});}
 await context.close();
 const hostContext=await browser.newContext({viewport:{width:1440,height:1000}}),host=await hostContext.newPage();host.on('pageerror',e=>errors.push(e.message));const hostURL=pathToFileURL(path.join(base,'index.html')).href;await host.goto(hostURL+'#complaint-tickets');const entry=host.locator('#complaint-nav a.nav-item');await entry.waitFor();assert.equal(await entry.evaluate(el=>el.previousElementSibling.textContent.trim()),'演示入口');await host.locator('#complaint-nav').screenshot({path:path.join(output,'menu-order.png')});assert.equal(await entry.getAttribute('target'),'_blank');assert.equal(await host.locator('#page-complaint-bi').count(),0);const active=await host.locator('.page.active').getAttribute('id');
 const popupPromise=host.waitForEvent('popup');await entry.click();const dashboard=await popupPromise;dashboard.on('pageerror',e=>errors.push(e.message));await dashboard.locator('h1').waitFor();assert.equal(new URL(dashboard.url()).searchParams.has('embed'),false);assert.equal(await dashboard.locator('.sidebar,.recent-tabs,.layout,iframe').count(),0);assert.equal(await dashboard.evaluate(()=>window.top===window),true);assert.equal(await host.locator('.page.active').getAttribute('id'),active);await dashboard.screenshot({path:path.join(output,'standalone.png'),fullPage:true});
 assert.equal(new URL(dashboard.url()).searchParams.get('tab'),'efficiency');await dashboard.locator('[data-action=metric][data-kind=first]').click();await dashboard.locator('[role=dialog]').waitFor();await dashboard.locator('[data-action=close]').click();await dashboard.setViewportSize({width:390,height:844});assert.equal(await dashboard.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await host.goto(hostURL+'#complaint-bi');await host.waitForURL(url=>url.pathname.endsWith('/bi.html'));await host.locator('h1').waitFor();assert.equal(await host.locator('.sidebar,.recent-tabs,iframe').count(),0);assert.deepEqual(errors,[]);console.log('PASS: node drawers and exports include complete timestamps, natural/paused/effective durations and results; ticket lineage, repeated nodes, carryover, raw CSV exports and responsive ledger; two BI tabs, legacy overview redirect, migrated efficiency metrics/aging and customer trend/regions, analysis interactions, removed search/overdue controls and centered button tabs at all viewport widths; sidebar opens a standalone new tab without system navigation, preserves the original page, and redirects old BI bookmarks.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
