'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),{pathToFileURL}=require('node:url'),{chromium}=require('playwright'),B=require('./bi-data.js');
const base=path.resolve(__dirname,'..'),output=process.env.QA_OUTPUT||'/tmp/complaint-bi-qa';fs.mkdirSync(output,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const url=pathToFileURL(path.join(__dirname,'bi.html')).href;await page.goto(url+'?tab=overview');assert.equal(new URL(page.url()).searchParams.get('tab'),'efficiency');assert.equal(await page.locator('.tabs [data-action=tab]').count(),2);assert.equal(await page.locator('[data-tab=overview]').count(),0);
 const expected=B.summarize({start:'2026-09-08',end:'2026-10-07'});assert.equal(await page.locator('[data-kind=first] .metric-value').innerText(),expected.first.toFixed(1)+'%');assert.equal(await page.locator('[data-kind=overdue] .metric-value').innerText(),expected.overdue.length+'单');await page.locator('[data-kind=closure]').click();await page.locator('#detail-table table').waitFor();await page.keyboard.press('Escape');await page.locator('[data-action=aging]').first().click();await page.locator('#detail-table table').waitFor();await page.keyboard.press('Escape');await page.locator('.tabs [data-tab=customer]').click();assert.equal(await page.locator('.chart-wrap svg').count(),1);assert.equal(await page.locator('.region-card').count(),4);assert.equal(await page.locator('.metric-value').first().innerText(),expected.cohort.length.toLocaleString('zh-CN')+'单');
 await page.evaluate(()=>localStorage.setItem('meiye.complaint.unified.v1','{"biPreservationProbe":true}'));
 const preserved=await page.evaluate(()=>localStorage.getItem('meiye.complaint.unified.v1'));
 await page.screenshot({path:path.join(output,'customer-trend.png'),fullPage:true});
 await page.locator('[data-action=metric][data-kind=new]').click();await page.locator('[data-action=ticket]').first().click();await page.locator('.timeline-item').first().waitFor();await page.locator('[data-action=back-detail]').click();assert.equal(await page.locator('[data-input=detail-search]').count(),1);await page.locator('[data-input=detail-search]').fill('NO SUCH TICKET');assert.match(await page.locator('#detail-table').innerText(),/暂无匹配明细/);await page.keyboard.press('Escape');
 await page.locator('.tabs [data-tab=efficiency]').click();await page.locator('[data-key=effDimension][data-value=person]').click();assert(!/自动派单/.test(await page.locator('.table-scroll tbody').innerText()));await page.locator('[data-action=eff-detail]').first().click();await page.locator('#detail-table table').waitFor();await page.keyboard.press('Escape');await page.locator('[data-key=effDimension][data-value=stage]').click();await page.screenshot({path:path.join(output,'efficiency.png'),fullPage:true});
 await page.locator('.tabs [data-tab=customer]').click();await page.locator('[data-key=dimension][data-value=region]').click();assert.equal(await page.locator('#org-table tbody tr').count(),10);await page.locator('[data-action=page][data-step="1"]').click();assert.equal(await page.locator('#org-table tbody tr').count(),2);await page.locator('[data-key=dimension][data-value=district]').click();await page.locator('.table-name').filter({hasText:'华东大区'}).click();assert.equal(await page.locator('[data-filter=district]').inputValue(),'华东大区');assert.equal(await page.locator('#org-table tbody tr').count(),3);await page.locator('.table-name').filter({hasText:'沪苏区域'}).click();assert.equal(await page.locator('#org-table tbody tr').count(),4);
 await page.locator('[data-filter=source]').selectOption('微动');await page.locator('[data-filter=level]').selectOption('5');const scoped=B.summarize({start:'2026-09-08',end:'2026-10-07',district:'华东大区',region:'沪苏区域',source:'微动',level:'5'});assert.equal(await page.locator('.metric-value').first().innerText(),scoped.cohort.length+'单');assert.equal(await page.locator('#org-table tbody tr').count(),4);
 const downloadPromise=page.waitForEvent('download');await page.locator('[data-action=export]').click();const download=await downloadPromise;const file=path.join(output,'export.csv');await download.saveAs(file);const csv=fs.readFileSync(file,'utf8');assert.match(csv,/上海徐汇店/);assert.match(csv,/上海静安店/);assert.match(csv,/南京新街口店/);assert(!csv.includes('杭州湖滨店'));
 await page.locator('[data-action=reset]').click();await page.locator('[data-filter=period]').selectOption('custom');await page.locator('[name=start]').fill('2026-10-07');await page.locator('[name=end]').fill('2026-10-01');await page.locator('#date-form [type=submit]').click();assert.match(await page.locator('.date-error').innerText(),/结束日期不能早于开始日期/);await page.locator('[name=start]').fill('2026-09-01');await page.locator('[name=end]').fill('2026-09-30');await page.locator('#date-form [type=submit]').click();assert.equal(await page.locator('.metric-value').first().innerText(),B.summarize({start:'2026-09-01',end:'2026-09-30'}).cohort.length.toLocaleString('zh-CN')+'单');await page.reload();assert.equal(await page.locator('[data-filter=period]').inputValue(),'custom');
 await page.locator('[data-action=definitions]').first().click();await page.locator('.definition').first().waitFor();await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>localStorage.getItem('meiye.complaint.unified.v1')),preserved);
 await page.locator('[data-action=reset]').click();await page.screenshot({path:path.join(output,'customer.png'),fullPage:true});
 for(const width of [1440,1024,390,320]){await page.setViewportSize({width,height:900});for(const tab of ['efficiency','customer']){await page.locator('.tabs [data-tab='+tab+']').click();assert.equal(await page.locator('.tab-no,[data-filter=effSort],[data-filter=effStage],[data-filter=sort],[data-filter=onlyOverdue],[data-input=org-search]').count(),0);const centered=await page.locator('.analysis-head .segmented').evaluate(el=>{const a=el.getBoundingClientRect(),b=el.closest('.analysis-card').getBoundingClientRect();return Math.abs(a.x+a.width/2-b.x-b.width/2)<1;});assert(centered,`centered analysis tabs ${width} ${tab}`);assert(await page.locator('.tabs').evaluate(el=>{const a=el.getBoundingClientRect(),b=el.closest('.page').getBoundingClientRect();return Math.abs(a.x+a.width/2-b.x-b.width/2)<1;}),`centered primary tabs ${width}`);if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)){console.log(await page.evaluate(()=>({w:innerWidth,html:document.documentElement.scrollWidth,items:[...document.querySelectorAll('body *')].filter(e=>!e.closest('.table-scroll')).map(e=>({cls:e.className,tag:e.tagName,r:e.getBoundingClientRect().right,text:e.textContent.slice(0,40)})).filter(e=>e.r>innerWidth)})));await page.screenshot({path:'/tmp/bi-failing-width.png'});}assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`no overflow ${width} ${tab}`);}if(width===390)await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});}
 await context.close();
 const hostContext=await browser.newContext({viewport:{width:1440,height:1000}}),host=await hostContext.newPage();host.on('pageerror',e=>errors.push(e.message));const hostURL=pathToFileURL(path.join(base,'index.html')).href;await host.goto(hostURL+'#complaint-tickets');const entry=host.locator('#complaint-nav a.nav-item');await entry.waitFor();assert.equal(await entry.evaluate(el=>el.previousElementSibling.textContent.trim()),'演示入口');await host.locator('#complaint-nav').screenshot({path:path.join(output,'menu-order.png')});assert.equal(await entry.getAttribute('target'),'_blank');assert.equal(await host.locator('#page-complaint-bi').count(),0);const active=await host.locator('.page.active').getAttribute('id');
 const popupPromise=host.waitForEvent('popup');await entry.click();const dashboard=await popupPromise;dashboard.on('pageerror',e=>errors.push(e.message));await dashboard.locator('h1').waitFor();assert.equal(new URL(dashboard.url()).searchParams.has('embed'),false);assert.equal(await dashboard.locator('.sidebar,.recent-tabs,.layout,iframe').count(),0);assert.equal(await dashboard.evaluate(()=>window.top===window),true);assert.equal(await host.locator('.page.active').getAttribute('id'),active);await dashboard.screenshot({path:path.join(output,'standalone.png'),fullPage:true});
 assert.equal(new URL(dashboard.url()).searchParams.get('tab'),'efficiency');await dashboard.locator('[data-action=metric][data-kind=first]').click();await dashboard.locator('[role=dialog]').waitFor();await dashboard.locator('[data-action=close]').click();await dashboard.setViewportSize({width:390,height:844});assert.equal(await dashboard.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await host.goto(hostURL+'#complaint-bi');await host.waitForURL(url=>url.pathname.endsWith('/bi.html'));await host.locator('h1').waitFor();assert.equal(await host.locator('.sidebar,.recent-tabs,iframe').count(),0);assert.deepEqual(errors,[]);console.log('PASS: two BI tabs, legacy overview redirect, migrated efficiency metrics/aging and customer trend/regions, analysis interactions, removed search/overdue controls and centered button tabs at all viewport widths; sidebar opens a standalone new tab without system navigation, preserves the original page, and redirects old BI bookmarks.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
