'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Shanghai',reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(10000);
 const url=pathToFileURL(path.resolve(__dirname,'workflow/index.html')).href,go=async(id,mobile=false)=>{await page.goto(url+(mobile?'?view=h5#/mobile/':'#/tickets/')+id,{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'客户资料',exact:true}).waitFor();},profile=()=>page.locator('.crm-customer-view'),tab=name=>profile().getByRole('tab',{name,exact:true}),settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
 const read=()=>page.evaluate(()=>ComplaintStore.load()),open=async()=>{await page.getByRole('button',{name:'客户资料',exact:true}).click();await profile().waitFor();},back=async()=>{await profile().locator('[data-crm=back]').click();await profile().waitFor({state:'detached'});await settle();};
 await go('KS20261007-P41');const before=await read();assert.equal(await page.locator('[data-action=reveal]').count(),0);await page.locator('[data-info-section=more]>summary').click();const pcScroll=await page.locator('.pc-detail-layout').evaluate(e=>e.scrollTop);await open();assert.equal(await page.locator('#drawer-root [role=dialog]').count(),1);assert.equal(await page.locator('#modal-root [role=dialog]').count(),0);assert.equal(await profile().getByRole('tab').count(),4);assert.match(await profile().locator('.crm-customer-summary').innerText(),/林女士.*13800001002/s);assert.match(await profile().locator('.crm-table tbody tr').first().innerText(),/本工单关联/);
 await profile().locator('[data-crm=order]').first().click();assert.match(await profile().locator('.crm-order-expanded:visible').innerText(),/项目名称.*开单人.*原价.*售价.*金额.*支付记录/s);await tab('支付记录').click();assert.equal(await tab('支付记录').getAttribute('aria-selected'),'true');assert.match(await profile().locator('.crm-payments-table').innerText(),/支付方式.*操作人.*交易内容.*交易时间/s);assert.doesNotMatch(await profile().locator('.crm-payments-table').innerText(),/流水号|收款门店|关联订单/);assert.equal(await profile().locator('select,input[type=search]').count(),0);assert(await profile().locator('.crm-payments-table tbody tr').count()>1);await settle();await page.screenshot({path:'/tmp/complaint-crm-pc-payments.png'});
 await tab('订单记录').click();assert.equal(await profile().locator('select,input[type=search]').count(),0);await settle();await page.screenshot({path:'/tmp/complaint-crm-pc-orders.png'});
 for(const width of [1440,1280,1024]){await page.setViewportSize({width,height:900});for(const label of ['订单记录','支付记录','影像资料','回访记录']){await tab(label).click();assert(await profile().evaluate(e=>[e,...e.querySelectorAll('.crm-main,.crm-table-wrap')].every(x=>x.scrollWidth<=x.clientWidth+1)),width+' '+label);}}
 await page.setViewportSize({width:1440,height:1000});await tab('影像资料').click();await profile().locator('.crm-photo img').first().evaluate(img=>img.decode());await settle();await page.screenshot({path:'/tmp/complaint-crm-pc-images.png'});await profile().locator('.crm-photo').first().click();const box=page.getByRole('dialog',{name:'影像照片',exact:true});await box.waitFor();await box.getByRole('button',{name:'放大照片',exact:true}).click();assert.equal(await box.locator('[data-crm=zoomReset]').innerText(),'150%');await page.keyboard.press('ArrowRight');assert.match(await box.locator('footer').innerText(),/2 \/ 2/);await page.keyboard.press('Escape');await box.waitFor({state:'detached'});await tab('回访记录').click();assert.match(await profile().locator('.crm-visits').innerText(),/已接通/);await settle();await page.screenshot({path:'/tmp/complaint-crm-pc-visits.png'});await back();assert.equal(await page.locator('[data-info-section=more]').getAttribute('open'),'');assert.equal(await page.locator('.pc-detail-layout').evaluate(e=>e.scrollTop),pcScroll);assert.deepEqual(await read(),before);
 // Desktop H5 preview keeps the same width as its ticket page, including the photo viewer.
 await go('KS20261007-P41',true);const shell=await page.locator('.mobile-shell').boundingBox();await open();let bounds=await profile().boundingBox();assert.equal(bounds.width,430);assert.equal(bounds.width,shell.width);assert.equal(bounds.x,shell.x);assert.equal(await profile().locator('select,input[type=search]').count(),0);await page.screenshot({path:'/tmp/complaint-crm-h5-desktop.png'});
 await tab('影像资料').click();await profile().locator('.crm-photo').first().click();assert.equal((await box.boundingBox()).width,430);assert.equal((await box.boundingBox()).x,bounds.x);await page.screenshot({path:'/tmp/complaint-crm-h5-desktop-photo.png'});await page.keyboard.press('Escape');await box.waitFor({state:'detached'});await back();assert.equal(await page.locator('.crm-mobile-surface').count(),0);
 // Browser Back closes the mobile photo first, then the profile; original tab and scroll survive.
 await page.setViewportSize({width:390,height:844});await go('KS20261007-P41',true);await page.getByRole('tab',{name:'操作记录',exact:true}).click();await page.getByRole('button',{name:'客户资料',exact:true}).scrollIntoViewIfNeeded();const mobileScroll=await page.evaluate(()=>scrollY);await open();assert.equal((await profile().boundingBox()).width,390);assert.equal(await profile().locator('select,input[type=search]').count(),0);assert.equal(await profile().locator('table').count(),0);assert.equal(await profile().locator('.crm-order-card').count()>1,true);await settle();await page.screenshot({path:'/tmp/complaint-crm-h5-orders.png'});
 await profile().locator('.crm-order-card [data-crm-order]>summary').first().click();assert.match(await profile().locator('.crm-order-card [data-crm-order][open]').first().innerText(),/开单.*原价.*售价.*金额/s);await profile().locator('.crm-order-card [data-crm-order-payments]>summary').first().click();assert.equal(await profile().locator('.crm-order-card').first().locator('details[open]').count(),2);await tab('支付记录').click();assert.equal(await profile().locator('table').count(),0);assert.match(await profile().locator('.crm-payment-card').first().innerText(),/结算收款/);assert.doesNotMatch(await profile().locator('#crm-content').innerText(),/流水号|收款门店|关联订单|交易明细/);await settle();await page.screenshot({path:'/tmp/complaint-crm-h5-payments.png'});
 await tab('影像资料').click();await profile().locator('.crm-photo img').first().evaluate(img=>img.decode());await settle();await page.screenshot({path:'/tmp/complaint-crm-h5-images.png'});await profile().locator('.crm-photo').first().click();await box.waitFor();await settle();await page.screenshot({path:'/tmp/complaint-crm-h5-photo.png'});const area=await box.locator('.crm-photo-viewport').boundingBox(),cx=area.x+area.width/2,cy=area.y+area.height/2;await page.mouse.move(cx+70,cy);await page.mouse.down();await page.mouse.move(cx-70,cy,{steps:8});await page.mouse.up();assert.match(await box.locator('footer').innerText(),/2 \/ 2/);const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx-35,y:cy,id:1},{x:cx+35,y:cy,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx-70,y:cy,id:1},{x:cx+70,y:cy,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await settle();assert.equal(await box.locator('[data-crm=zoomReset]').innerText(),'200%');await cdp.detach();await page.goBack();await box.waitFor({state:'detached'});assert(await profile().isVisible());await page.goBack();await profile().waitFor({state:'detached'});assert.equal(await page.getByRole('tab',{name:'操作记录',exact:true}).getAttribute('aria-selected'),'true');assert(Math.abs(await page.evaluate(()=>scrollY)-mobileScroll)<2);assert.equal(await page.locator('#app').evaluate(e=>e.inert),false);
 await open();await page.setViewportSize({width:320,height:700});for(const label of ['订单记录','支付记录','影像资料','回访记录']){await tab(label).click();assert.equal(await profile().locator('table').count(),0);assert(await profile().evaluate(e=>[e,...e.querySelectorAll('.crm-main,.crm-order-card,.crm-payment-card,.crm-image-group')].every(x=>x.scrollWidth<=x.clientWidth+1)),label);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}await settle();await page.screenshot({path:'/tmp/complaint-crm-h5-320.png'});await back();
 for(const id of ['KS20261007-G01','KS20260929-003','KS20260929-005']){await go(id,true);await open();for(const label of ['订单记录','支付记录','影像资料','回访记录']){await tab(label).click();assert.doesNotMatch(await profile().innerText(),/尚未关联|暂无|加载失败|结算作废|未接通/);assert.equal(await profile().locator('.crm-empty').count(),0);}await back();}assert.deepEqual(errors,[]);
 // Main entry uses the same drawer and fills the host viewport.
 const host=await context.newPage();await host.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href+'#complaint-tickets',{waitUntil:'domcontentloaded'});const f=host.frameLocator('#page-complaint-tickets iframe');await f.locator('.tickets-table').waitFor();await f.locator('#filter-form [name=q]').fill('KS20261007-P41');await f.locator('#filter-form [type=submit]').click();await f.getByRole('button',{name:'查看详情',exact:true}).click();await f.getByRole('button',{name:'客户资料',exact:true}).click();await f.locator('.crm-customer-view').waitFor();assert.equal(await f.locator('#drawer-root [role=dialog]').count(),1);await host.screenshot({path:'/tmp/complaint-crm-host.png'});
 console.log('PASS CRM profiles: four read-only categories, no search/filter controls, fixed-width desktop H5 preview and gallery, original data unchanged, PC single drawer, H5 cards, image viewer/zoom/back, preserved ticket tab and scroll, no identity fallback, normal records for every example customer, 320/390/1024/1280/1440px layouts, host entry.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
