'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Shanghai',reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(10000);
 const url=pathToFileURL(path.resolve(__dirname,'workflow/index.html')).href;
 const go=async(suffix,mobile=false)=>{await page.goto(url+(mobile?'?view=h5#/mobile/':'#/tickets/')+(suffix.startsWith('KS')?suffix:'KS20261007-'+suffix),{waitUntil:'domcontentloaded'});await page.locator(mobile?'.mobile-process-card':'.pc-process-card').waitFor();};
 const current=()=>page.locator('[aria-current=step]'),detail=()=>page.locator('.external-approval-detail'),shot=async(name)=>page.screenshot({path:'/tmp/complaint-external-'+name+'.png'});
 await go('D01');assert.match(await current().innerText(),/付款审批/);assert.match(await current().innerText(),/孙琳/);assert.equal(await page.locator('[data-action=approve],[data-action=reject]').count(),0);assert.equal(await page.locator('.pc-detail-section').count(),5);
 await page.locator('.drawer-footer [data-action=externalApproval]').click();await detail().waitFor();assert.equal(await detail().locator('tbody tr').count(),2);assert.match(await detail().innerText(),/财务负责人同意/);assert.match(await detail().innerText(),/500.00/);assert.equal(await page.locator('#modal-root [type=submit]').count(),0);await shot('pc-approval');await page.locator('#modal-root .drawer-footer [data-action=closeModal]').click();
 // Synchronization is read-only; a separately completed fixture represents approval.
 const pending=await page.evaluate(()=>JSON.stringify(ComplaintStore.load().tickets.find(t=>t.id.endsWith('-D01'))));
 await page.locator('.drawer-footer [data-action=externalApproval]').click();await page.locator('[data-action=approvalSync]').click();await detail().locator('.pill').filter({hasText:'审批中'}).waitFor();await page.locator('#modal-root .drawer-footer [data-action=closeModal]').click();assert.match(await current().innerText(),/付款审批/);assert.equal(await page.locator('[data-action=pay]').count(),0);
 assert.equal(await page.evaluate(()=>JSON.stringify(ComplaintStore.load().tickets.find(t=>t.id.endsWith('-D01')))),pending);
 await page.reload({waitUntil:'domcontentloaded'});assert.match(await current().innerText(),/付款审批/);
 await go('D02');assert.match(await current().innerText(),/付款办理/);assert(await page.locator('[data-action=pay]').isVisible());
 for(const mobile of [false,true]){
  await page.setViewportSize(mobile?{width:390,height:844}:{width:1440,height:1000});
  for(const [id,person] of [['KS20260929-005','蒋琴'],['P40','陆清']]){
   await go(id,mobile);assert.match(await current().innerText(),/付款审批/);assert.match(await current().innerText(),new RegExp(person));assert.equal(await page.locator('[data-action=approve],[data-action=reject]').count(),0);
   await current().locator('[data-action=externalApproval]').click();await detail().waitFor();assert.match(await detail().innerText(),/付款申请/);await page.locator('[data-action=approvalSync]').click();await detail().locator('.pill').filter({hasText:'审批中'}).waitFor();assert.equal(await page.locator('[data-action=pay]').count(),0);await shot((mobile?'h5':'pc')+'-migrated-'+id);
  }
 }
 await page.setViewportSize({width:1440,height:1000});
 await go('D06');await current().locator('[data-action=externalApproval]').click();assert.equal(await detail().locator('[data-action=approvalSync]').count(),0);await detail().locator('[data-action=approvalRetry]').click();await detail().locator('.pill').filter({hasText:'审批中'}).waitFor();await page.locator('#modal-root .drawer-footer [data-action=closeModal]').click();assert.match(await current().innerText(),/付款审批/);
 await go('D10');await current().locator('[data-action=externalApproval]').click();await detail().locator('[data-action=approvalSync]').click();await detail().locator('.pill').filter({hasText:'状态待确认'}).waitFor();assert.equal(await detail().locator('[data-action=approvalRetry]').count(),0);await page.locator('#modal-root .drawer-footer [data-action=closeModal]').click();

 await go('D05');assert(await page.locator('[data-action=amendProcurement]').isVisible());assert.equal(await page.locator('[data-action=proposal]').count(),0);await page.locator('[data-action=amendProcurement]').click();const form=page.locator('[data-form=amendProcurement]');await form.waitFor();assert.equal(await form.locator('tbody tr').count(),2);assert.equal(await form.locator('[name=refund],[name=compensation],[name=payoutAccount]').count(),0);assert.match(await form.innerText(),/500.00/);await shot('pc-procurement-adjustment');await form.locator('[name=exchangeQuantity]').first().fill('3');await form.locator('[name=note]').fill('客户已确认调整商品数量，已付款金额保持不变');await form.locator('[type=submit]').click();await form.waitFor({state:'detached'});assert.match(await current().innerText(),/采购审批/);assert.match(await current().innerText(),/审批中/);const amended=await page.evaluate(()=>ComplaintStore.load().tickets.find(t=>t.id.endsWith('-D05')));assert.equal(amended.payments.length,1);assert.equal(amended.proposal.exchangeItems[0].quantity,3);assert.equal(amended.proposal.refund,50000);
 for(const [suffix,label] of [['D03','采购审批'],['D04','专员办理'],['D06','审批中'],['D07','待同步'],['D08','采购办理'],['D09','专员办理'],['D10','状态待确认'],['D11','采购审批']]){await go(suffix);assert.match(await current().innerText(),new RegExp(label));assert.equal(await page.locator('[data-action=approve],[data-action=reject]').count(),0);}
 for(const width of [1280,1024]){await page.setViewportSize({width,height:900});await go('D03');await current().locator('[data-action=externalApproval]').click();assert(await detail().evaluate(el=>el.scrollWidth<=el.clientWidth+1));await shot('pc-'+width);await page.locator('#modal-root .drawer-footer [data-action=closeModal]').click();}
 await page.setViewportSize({width:390,height:844});await go('D03',true);assert.equal(await page.getByRole('tab').count(),3);assert.equal(await page.locator('[data-action=approve],[data-action=reject]').count(),0);await current().locator('[data-action=externalApproval]').click();await detail().waitFor();assert.equal(await detail().locator('table').count(),0);assert.equal(await detail().locator('.external-detail-row').count(),2);assert.match(await detail().innerText(),/舒缓修护霜/);await shot('h5-approval');await page.locator('.mobile-action-back').click();await detail().waitFor({state:'detached'});
 await go('D05',true); // A second independent rejected fixture restores the amendment screen for mobile.
 await page.evaluate(()=>{const s=ComplaintStore.load(),t=s.tickets.find(t=>t.id.endsWith('-D05')),r=Engine.externalApprovalRecord(s,t);Engine.applyApprovalEvent(s,{id:'browser-proc-reject',instanceId:r.instanceId,scope:'instance',type:'finish',result:'refuse',reason:'替换缺货商品',at:Date.now()+10});ComplaintStore.save(s);});await page.reload({waitUntil:'domcontentloaded'});await page.locator('[data-action=amendProcurement]').click();await form.waitFor();assert.equal(await form.locator('table').count(),0);assert.equal(await form.locator('.mobile-product-card').count(),2);await form.locator('[data-action=addExchange]').click();await page.locator('[name=productSearch]').fill('面膜');assert.match(await page.locator('.product-picker-results').innerText(),/面膜/);await page.locator('[data-action=closeProductPicker]').click();await shot('h5-adjustment');
 for(const width of [390,320]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await form.evaluate(el=>el.scrollWidth<=el.clientWidth+1));}
 assert.deepEqual(errors,[]);await context.close();
 // Root navigation and approval record -> ticket share the same store.
 const c2=await browser.newContext({viewport:{width:1440,height:1000}}),host=await c2.newPage();host.on('pageerror',e=>errors.push(e.message));await host.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href+'#complaint-approvals',{waitUntil:'domcontentloaded'});const f=host.frameLocator('#page-complaint-approvals iframe');await f.getByRole('tab',{name:'审批记录',exact:true}).click();
 for(const [id,action,label] of [['D01','record-sync','审批中'],['D06','record-retry','审批中'],['D10','record-sync','状态待确认']]){
  await f.getByLabel('搜索审批记录',{exact:true}).fill('KS20261007-'+id);await f.getByRole('button',{name:'查询',exact:true}).click();await f.getByRole('button',{name:'查看详情',exact:true}).first().click();const drawer=f.locator('.approval-drawer');await drawer.waitFor();await drawer.locator('[data-approval-action='+action+']').click();await f.locator('#toast').filter({hasText:action==='record-retry'?'审批已重新发起':'审批状态已刷新'}).waitFor();assert.match(await drawer.innerText(),new RegExp(label));await drawer.getByRole('button',{name:'关闭',exact:true}).click();
 }
 await f.getByLabel('搜索审批记录',{exact:true}).fill('KS20261007-D03');await f.getByRole('button',{name:'查询',exact:true}).click();await f.getByRole('button',{name:'查看详情',exact:true}).first().click();await f.locator('.approval-drawer').waitFor();assert.match(await f.locator('.approval-drawer').innerText(),/KS20261007-D03/);await f.locator('.approval-drawer [data-approval-action=ticket]').click();const tf=host.frameLocator('#page-complaint-tickets iframe');await tf.locator('.ticket-drawer').waitFor();assert.match(await tf.locator('[aria-current=step]').innerText(),/采购审批/);assert.deepEqual(errors,[]);
 console.log('PASS external approval PC/H5: linked records, read-only approvals, refresh does not approve, explicit retry, preserved legacy cases, approved fixture -> payment, immutable paid procurement amendment, failed/sync/withdrawal examples, mobile product search, responsive detail, host navigation.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
