/* Isolated UI acceptance for the H5 detail information card and three tabs. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path');
const url=pathToFileURL(path.join(__dirname,'workflow/index.html')).href;
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(10000);
 const go=async suffix=>{await page.goto(url+'?view=h5#/mobile/KS20261007-'+suffix,{waitUntil:'domcontentloaded'});await page.locator('.mobile-detail-tabs').waitFor();};
 const tab=name=>page.getByRole('tab',{name,exact:true}),finish=()=>page.evaluate(()=>document.getAnimations().forEach(a=>a.finish()));
 const read=()=>page.evaluate(()=>ComplaintStore.load());
 const checkTab=async(name,key)=>{await tab(name).click();assert.equal(await tab(name).getAttribute('aria-selected'),'true');assert.equal(await page.locator('[role=tabpanel]:visible').count(),1);assert(await page.locator('#mobile-panel-'+key).isVisible());};
 await go('P41');const original=await read();assert.equal(await page.getByRole('tab').count(),3);assert.equal(await tab('处理方案').getAttribute('aria-selected'),'true');assert(await page.locator('.mobile-ticket-information').isVisible());assert.match(await page.locator('#mobile-panel-plan').innerText(),/订单退款/);assert.match(await page.locator('#mobile-panel-plan').innerText(),/置换商品/);await finish();await page.screenshot({path:'/tmp/complaint-h5-detail-plan.png'});
 await checkTab('操作记录','records');assert.match(await page.locator('#mobile-panel-records').innerText(),/受理工单/);await finish();await page.screenshot({path:'/tmp/complaint-h5-detail-records.png'});
 await checkTab('办理时效','timing');assert.match(await page.locator('#mobile-panel-timing').innerText(),/整单截止/);assert.match(await page.locator('#mobile-panel-timing').innerText(),/有效办理耗时/);await finish();await page.screenshot({path:'/tmp/complaint-h5-detail-timing.png'});assert.equal((await read())._revision,original._revision);
 await tab('办理时效').press('Home');assert.equal(await tab('处理方案').getAttribute('aria-selected'),'true');await tab('处理方案').press('ArrowRight');assert.equal(await tab('操作记录').getAttribute('aria-selected'),'true');await tab('操作记录').press('End');assert.equal(await tab('办理时效').getAttribute('aria-selected'),'true');
 await checkTab('处理方案','plan');await page.locator('.mobile-detail-workspace').evaluate(el=>scrollTo(0,scrollY+el.getBoundingClientRect().top+200));await finish();let positions=await page.evaluate(()=>({header:document.querySelector('.mobile-detail-shell>.mobile-top').getBoundingClientRect().bottom,tabs:document.querySelector('.mobile-detail-tabs').getBoundingClientRect().top}));assert(Math.abs(positions.header-positions.tabs)<2,JSON.stringify(positions));await checkTab('操作记录','records');positions=await page.evaluate(()=>({header:document.querySelector('.mobile-top').getBoundingClientRect().bottom,panel:document.querySelector('#mobile-panel-records').getBoundingClientRect().top}));assert(positions.panel>=positions.header+45,JSON.stringify(positions));await finish();await page.screenshot({path:'/tmp/complaint-h5-detail-sticky-tabs.png'});
 for(const [suffix,state] of [['W04','待处理'],['W01','待处理'],['P39','处理中'],['P41','审批中'],['H02','已挂起'],['P14','待结案'],['C08','已结案']]){
  await go(suffix);assert.equal((await page.locator('.mobile-info-heading .mobile-state').innerText()).trim(),state);assert.equal(await tab('处理方案').getAttribute('aria-selected'),'true');assert.equal(await page.getByRole('tab').count(),3);
  for(const width of [320,390]){await page.setViewportSize({width,height:844});for(const [label,key] of [['处理方案','plan'],['操作记录','records'],['办理时效','timing']]){await checkTab(label,key);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),suffix+' '+label+' '+width);}}
  if(suffix==='H02'){assert.match(await page.locator('#mobile-panel-timing').innerText(),/节点计时已暂停，整单继续计时/);await page.locator('#mobile-panel-timing').scrollIntoViewIfNeeded();await finish();await page.screenshot({path:'/tmp/complaint-h5-detail-suspension.png'});assert(await page.locator('[data-action=resumeTicket]').isVisible());}
  if(suffix==='C08'){assert.match(await page.locator('.mobile-current-task').innerText(),/结案人/);assert.doesNotMatch(await page.locator('.mobile-current-task').innerText(),/待分派/);await checkTab('处理方案','plan');assert.match(await page.locator('#mobile-panel-plan').innerText(),/门店处理结果/);}
 }
 await go('P39');await page.locator('.mobile-info-more>summary').click();const info=page.locator('.mobile-info-more');assert.match(await info.innerText(),/会员号/);assert.match(await info.innerText(),/消费订单/);assert.match(await info.innerText(),/定级与处理规则/);assert.match(await info.innerText(),/来源记录/);await page.locator('.mobile-info-more>summary').click();
 await checkTab('操作记录','records');await page.locator('[data-action=follow]').click();const form=page.locator('[data-form=follow]');await form.locator('[name=content]').fill('确认三栏详情中跟进记录可直接更新');await form.locator('[name=result]').selectOption('plan');await form.locator('[type=submit]').click();await form.waitFor({state:'detached'});await page.locator('[data-form=proposal]').waitFor();await page.locator('#modal-root [data-action=closeModal]').first().click();await page.locator('[data-form=proposal]').waitFor({state:'detached'});assert.equal(await tab('操作记录').getAttribute('aria-selected'),'true');assert.match(await page.locator('#mobile-panel-records').innerText(),/确认三栏详情中跟进记录可直接更新/);
 await checkTab('处理方案','plan');await page.locator('[data-action=proposal]').click();assert(await page.locator('[data-form=proposal]').isVisible());await page.getByRole('button',{name:'返回上一页',exact:true}).click();await page.locator('[data-form=proposal]').waitFor({state:'detached'});assert.equal(await tab('处理方案').getAttribute('aria-selected'),'true');assert.deepEqual(errors,[]);
 console.log('PASS H5 detail: information above three tabs, default solution and full details, records and timing separated, sticky switching and keyboard navigation, six states at 320/390px, suspension details, direct closure result, expanded information, follow-up persistence and unchanged action forms; no overflow or browser errors.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
