'use strict';
const assert=require('node:assert/strict'),E=require('./engine.js'),R=E.Rules,F=R.Flow;
const NOW=Date.parse('2026-09-29T10:00:00+08:00');let count=0;
function test(name,fn){fn();count++;console.log('通过：'+name);}
function setup(edit=()=>{}){
 let s=E.seed(NOW),d=R.prepareScene(R.sceneList(s)[0]);
 d.config.approval.flow=[{...F.node(),title:'主管审核',source:'duty',duty:'客诉主管',handling:{hours:4,overdue:'supervisor'}},{...F.node(),title:'财务审核',source:'duty',duty:'财务审核',handling:{hours:6,overdue:'supervisor'}}];
 edit(d,s);s=R.saveScene(s,'manager',d,0,NOW);let made=E.apply(s,'intake',{type:'create',data:{sceneId:d.id,customerId:'customer1',store:E.STORES[0],title:'处理规则验收',description:'验证实际办理行为'}},NOW);s=made.state;const id=made.caseId;let now=NOW;
 return {get s(){return s;},set s(value){s=value;},get c(){return s.cases.find(c=>c.id===id);},get now(){return now;},set now(value){now=value;},act(type,data={},who){const c=this.c,t=E.pending(c).find(t=>(!who||t.assigneeId===who)&&(t.kind===type||(type==='plan'&&t.kind==='plan')||({refundStart:'refundExecute'}[type]===t.kind)));assert(t,'缺少任务 '+type);s=E.apply(s,who||t.assigneeId,{type,caseId:id,taskId:t.id,expectedRevision:c.revision,data},now).state;},poll(at){now=at;s=E.refresh(s,at);},refund(){this.act('accept');this.act('contact',{result:'connected',content:'已联系'});this.act('plan',{planType:'refund',orderId:'order-r1',refundAmount:'600',refundReason:'未消费',summary:'退回余额',deadline:now+E.HOUR*10});},service(){this.act('accept');this.act('contact',{result:'connected',content:'已联系'});this.act('plan',{summary:'安排服务',deadline:now+E.HOUR,items:[{type:'解释道歉',description:'解释',assigneeId:'store1'}]});this.act('confirm',{version:1,decision:'agree',evidence:'客户接受'});this.act('service',{content:'已完成'});}};
}
test('按每个画布节点的时限产生待办，审批前后分别起算',()=>{const r=setup();r.refund();assert.equal(E.pending(r.c)[0].dueAt,NOW+4*E.HOUR);r.now=NOW+3*E.HOUR;r.act('refundApproval',{decision:'approve',content:'同意'});assert.equal(E.pending(r.c)[0].dueAt,NOW+9*E.HOUR);});
test('从接单起处理阶段持续计时，联系拖延不会刷新处理期限',()=>{const r=setup();r.act('accept');r.now=NOW+25*E.HOUR;r.act('contact',{result:'connected',content:'联系完成'});assert.equal(E.pending(r.c)[0].dueAt,NOW+8*E.HOUR);r.poll(r.now);assert(r.c.targetOverdueAt);assert(E.activePeriod(r.c).overdueNotifiedAt);});
test('临期提醒仅一次，超时按节点通知真实直属上级，不能自动批准',()=>{const r=setup();r.refund();r.poll(NOW+3.3*E.HOUR);assert.equal(r.s.notices.filter(n=>n.title.includes('临期提醒')).length,1);r.poll(NOW+3.4*E.HOUR);assert.equal(r.s.notices.filter(n=>n.title.includes('临期提醒')).length,1);r.poll(NOW+5*E.HOUR);assert(r.s.notices.some(n=>n.recipientId==='director'&&n.title.includes('督办')));assert.equal(r.c.stage,'approval');r.act('refundApproval',{decision:'approve',content:'同意'});assert.equal(r.c.tasks.find(t=>t.kind==='refundApproval').overdueMs,E.HOUR);});
test('节点选择仅提醒本人时，不发送该节点的上级督办',()=>{const r=setup(d=>d.config.approval.flow[0].handling.overdue='remind');r.refund();r.poll(NOW+5*E.HOUR);assert(!r.s.notices.some(n=>n.recipientId==='director'&&n.event==='overdue'));});
test('接单超时只自动转派一次，保留首联期限与原人逾期',()=>{const r=setup(d=>d.config.handling.acceptAction='transfer');r.poll(NOW+E.HOUR);assert.equal(E.pending(r.c)[0].assigneeId,'aftercare');assert.equal(r.c.firstContactDue,NOW+2*E.HOUR);assert.equal(r.c.tasks[0].overdueMs,0.5*E.HOUR);r.poll(NOW+2*E.HOUR);assert.equal(r.c.stage,'unassigned');assert.equal(E.pending(r.c)[0].kind,'assign');});
test('未接通记录下次联系时间，首联任务与原期限保持不变',()=>{const r=setup();r.act('accept');const old=E.pending(r.c)[0].id;r.now=NOW+E.HOUR;r.act('contact',{result:'unreachable',content:'未接听',retryAt:NOW+4*E.HOUR});assert.equal(E.pending(r.c)[0].id,old);assert.equal(E.pending(r.c)[0].dueAt,NOW+2*E.HOUR);assert.equal(E.pending(r.c)[0].retryAt,NOW+4*E.HOUR);});
test('回访多轮仍未接通不重置期限；解决后直接结案，无品控节点',()=>{const r=setup();r.service();const t=E.pending(r.c)[0];r.act('visit',{result:'unreachable',content:'未接',retryAt:NOW+E.HOUR});assert.equal(E.pending(r.c)[0].id,t.id);assert.equal(E.pending(r.c)[0].dueAt,t.dueAt);r.act('visit',{result:'unresolved',content:'还需处理'});r.act('plan',{summary:'再次安排',deadline:NOW+E.HOUR,items:[{type:'解释道歉',description:'再次说明',assigneeId:'store1'}]});r.act('confirm',{version:2,decision:'agree',evidence:'接受'});r.act('service',{content:'完成'});r.act('visit',{result:'resolved',content:'已解决'});assert.equal(r.c.stage,'closed');assert(!r.c.tasks.some(t=>t.kind==='quality'));});
test('审批人为空时按备用职责匹配',()=>{const r=setup(d=>{d.config.approval.flow[0]={...F.node(),title:'门店审核',handling:{hours:2,overdue:'supervisor'}};d.config.handling.empty={mode:'replace',duty:'公司负责人'};});r.act('accept');r.act('contact',{result:'connected',content:'已联系'});r.s.organization=F.organization(r.s);r.s.organization.departments.find(d=>d.store===E.STORES[0]).leaders=[];r.act('plan',{planType:'refund',orderId:'order-r1',refundAmount:'600',refundReason:'未消费',summary:'退款',deadline:NOW+E.HOUR*10});assert.equal(E.pending(r.c)[0].assigneeId,'director');});
test('在途审批人离职，产生管理员异常任务，修复任职后恢复',()=>{const r=setup();r.refund();r.s.organization=F.organization(r.s);r.s.organization.appointments.find(a=>a.personId==='manager').active=false;r.poll(NOW+E.HOUR);assert.equal(E.pending(r.c)[0].kind,'approvalException');assert.equal(r.c.plans[0].approvals[0].status,'paused');assert.throws(()=>r.act('approvalException'),/有效人员|接替|负责人/);r.s.organization.appointments.find(a=>a.personId==='manager').active=true;r.act('approvalException');assert.equal(E.pending(r.c)[0].kind,'refundApproval');assert.equal(r.c.plans[0].approvals[0].status,'pending');});
test('离职自动接替按备用职责派发，原审批链接失效',()=>{const r=setup(d=>d.config.handling.departed={mode:'replace',duty:'公司负责人'});r.refund();const old=E.pending(r.c)[0];r.s.organization=F.organization(r.s);r.s.organization.appointments.find(a=>a.personId==='manager').active=false;r.poll(NOW+E.HOUR);assert.equal(E.pending(r.c)[0].assigneeId,'director');assert.equal(r.c.tasks.find(t=>t.id===old.id).status,'transferred');assert.throws(()=>E.apply(r.s,'manager',{type:'refundApproval',caseId:r.c.id,taskId:old.id,expectedRevision:r.c.revision,data:{decision:'approve',content:'通过'}},r.now),/已处理|转派/);});
test('有效代办优先于管理员交接',()=>{const r=setup();r.refund();r.s.organization=F.organization(r.s);r.s.organization.delegations=[{from:'manager',to:'director',startAt:NOW,endAt:NOW+2*E.HOUR}];r.poll(NOW+E.HOUR);assert.equal(E.pending(r.c)[0].assigneeId,'director');});
test('同一方案连续重复审批沿用已同意结果，财务仍需审批',()=>{const r=setup(d=>{d.config.handling.repeat='consecutive';d.config.approval.flow.splice(1,0,{...F.node(),title:'再核实',source:'duty',duty:'客诉主管',handling:{hours:2,overdue:'supervisor'}});});r.refund();r.act('refundApproval',{decision:'approve',content:'同意'});assert.equal(E.pending(r.c)[0].assigneeId,'finance');assert(r.c.plans[0].approvals[1].reused);});
test('默认逐节点审批不跳过同一人，驳回重提不沿用旧版本',()=>{const r=setup(d=>{d.config.approval.flow.splice(1,0,{...F.node(),title:'再核实',source:'duty',duty:'客诉主管',handling:{hours:2,overdue:'supervisor'}});});r.refund();r.act('refundApproval',{decision:'approve',content:'同意'});assert.equal(E.pending(r.c)[0].assigneeId,'manager');r.act('refundApproval',{decision:'reject',content:'补资料'});r.act('plan',{planType:'refund',orderId:'order-r1',refundAmount:'600',refundReason:'未消费',summary:'补齐重新申请',deadline:NOW+E.HOUR*10});assert.equal(E.pending(r.c)[0].assigneeId,'manager');assert.equal(r.c.plans[1].version,2);});
test('付款提交、结果未知、失败重试沿用同一付款期限',()=>{const r=setup();r.refund();r.act('refundApproval',{decision:'approve',content:'通过'});r.act('refundApproval',{decision:'approve',content:'通过'});r.act('confirm',{version:1,decision:'agree',evidence:'接受'});const due=E.pending(r.c)[0].dueAt;r.now=NOW+E.HOUR;r.act('refundStart');assert.equal(E.pending(r.c)[0].dueAt,due);r.act('refundResult',{result:'unknown',content:'需核查',occurredAt:r.now});assert.equal(E.pending(r.c)[0].dueAt,due);r.act('refundVerify',{result:'failed',content:'核查失败',occurredAt:r.now});assert.equal(E.pending(r.c)[0].dueAt,due);r.act('refundRetry',{decision:'retry',content:'已核实可重试'});assert.equal(E.pending(r.c)[0].dueAt,due);});
test('新字段保存后保留，非法节点时限和异常策略拒绝保存',()=>{const r=setup();const d=R.prepareScene(R.sceneList(r.s)[0]);d.config.approval.flow[0].handling.hours=0;assert.throws(()=>R.saveScene(r.s,'manager',d,r.s.sceneRevision,NOW),/时限/);d.config.approval.flow[0].handling.hours=3;d.config.handling.empty.mode='approve';assert.throws(()=>R.saveScene(r.s,'manager',d,r.s.sceneRevision,NOW),/异常/);d.config.handling.empty.mode='block';const updated=R.saveScene(r.s,'manager',d,r.s.sceneRevision,NOW);assert.equal(updated.ruleScenes[0].config.approval.flow[0].handling.hours,3);assert.equal(updated.cases[0].rulesSnapshot.approval.flow[0].handling.hours,4);});
test('空人阻止提交且不占用退款额度，备用职责是本人时也阻止',()=>{
 const r=setup(d=>{d.config.approval.flow[0]={...F.node(),title:'门店审核',handling:{hours:2,overdue:'supervisor'}};});r.act('accept');r.act('contact',{result:'connected',content:'已联系'});r.s.organization=F.organization(r.s);r.s.organization.departments.find(d=>d.store===E.STORES[0]).leaders=[];
 const submit=()=>r.act('plan',{planType:'refund',orderId:'order-r1',refundAmount:'600',refundReason:'未消费',summary:'退款',deadline:NOW+E.HOUR*10});
 assert.throws(submit,/负责人/);assert.equal(r.c.plans.length,0);assert.equal(E.Refunds.balance(r.s,'order-r1').reserved,0);
 r.c.rulesSnapshot.handling.empty={mode:'replace',duty:'公司负责人'};const row=r.s.organization.arrangements.find(a=>a.duty==='公司负责人');row.departmentId='store1';row.position='门店店长';assert.throws(submit,/申请人/);
});
test('代办授权已过期时不得派给代办人',()=>{const r=setup();r.refund();r.s.organization=F.organization(r.s);r.s.organization.delegations=[{from:'manager',to:'director',startAt:NOW-2*E.HOUR,endAt:NOW}];r.s.organization.appointments.find(a=>a.personId==='manager').active=false;r.poll(NOW+E.HOUR);assert.equal(E.pending(r.c)[0].kind,'approvalException');});
test('旧风险响应字段作为历史值保留，不改变在途工单快照',()=>{
 const r=setup(),draft=R.prepareScene(R.sceneList(r.s)[0]);assert.equal(draft.config.timing.riskHours,0.5);
 draft.config.timing.riskHours=0.1;const saved=R.saveScene(r.s,'manager',draft,r.s.sceneRevision,NOW);assert.equal(saved.ruleScenes[0].config.timing.riskHours,0.1);assert.equal(saved.cases[0].rulesSnapshot.timing.riskHours,0.5);
});
console.log(`完成 ${count} 项处理规则运行验证。`);
