/* Six-state lifecycle and scenario coverage, using an isolated browser profile. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),url=p=>pathToFileURL(path.join(root,p)).href,out='/tmp/complaint-six-states-qa',KEY='meiye.complaint.unified.v1';
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 fs.mkdirSync(out,{recursive:true});const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Shanghai',reducedMotion:'reduce'}),errors=[];context.on('page',p=>p.on('pageerror',error=>errors.push(error.message)));
 const page=await context.newPage();page.setDefaultTimeout(10000);await page.goto(url('index.html')+'#complaint-tickets');const f=page.frameLocator('#page-complaint-tickets iframe');await f.locator('.tickets-table').waitFor();
 const original=await f.locator('body').evaluate(()=>ComplaintStore.load()),catalog=await f.locator('body').evaluate(()=>Engine.WORKFLOW_EXAMPLES);assert.equal(catalog.length,49);
 assert.deepEqual(await f.locator('#filter-form [name=state] option').allTextContents(),['全部状态','待处理','处理中','审批中','待结案','已挂起','已结案']);
 for(const state of ['待处理','处理中','审批中','待结案','已挂起','已结案']){await f.locator('#filter-form [name=state]').selectOption(state);await f.locator('#filter-form [type=submit]').click();assert((await f.locator('.tickets-table tbody tr').count())>0);for(const value of await f.locator('.tickets-table tbody tr td:nth-child(5) > .pill').allTextContents())assert.equal(value,state);await page.screenshot({path:out+'/pc-'+state+'.png'});}
 await f.locator('#filter-form [name=state]').selectOption('');await f.locator('#filter-form [type=submit]').click();
 const expected={W04:'confirmGrading',W05:'retryIntake',W02:'follow',W03:'retryIntake',P01:'proposal',P02:'proposal',P03:'finishStoreAssistance',P04:'proposal',P05:'proposal',P06:'approve',P07:'approve',P08:'approve',P09:'proposal',P10:'finishStore',P11:'pay',P12:'pay',P13:'proposal',P14:'closeTicket',P15:'closeTicket',P16:'closeTicket',P17:'proposal',P18:'proposal',P19:'retryFlowNode',P20:'noPayment',P21:'proposal',P22:'follow',P23:'finishStoreAssistance',P24:'closeTicket',P25:'closeTicket',P26:'closeTicket',P27:'closeTicket',P28:'proposal',P29:'proposal',P30:'proposal',H05:'resumeTicket',H06:'resumeTicket',H07:'resumeTicket',H01:'resumeTicket',H02:'resumeTicket',H03:'resumeTicket',H04:'resumeTicket'};
 const mobile=await context.newPage();mobile.setDefaultTimeout(10000);await mobile.setViewportSize({width:390,height:844});
 for(const row of catalog){
  await f.locator('#filter-form [name=q]').fill(row.id);await f.locator('#filter-form [type=submit]').click();await f.locator('[data-action=detail][data-id="'+row.id+'"]').click();await f.locator('.ticket-drawer').waitFor();assert((await f.locator('.pc-ticket-badges').innerText()).includes(row.state),row.id);
  if(expected[row.suffix])await f.locator('[data-action='+expected[row.suffix]+']').waitFor();
  else if(row.state==='已结案')assert.equal(await f.locator('.pc-footer-actions .action-buttons button').count(),0);
  else assert((await f.locator('.pc-ticket-overview').innerText()).includes('售后派单'));
  assert.equal(await f.locator('[data-action=review],[data-action=risk],[data-action=withdraw],[data-action=escalate]').count(),0);await f.getByRole('button',{name:'关闭详情',exact:true}).click();
  await mobile.goto(url('complaint-prototype/workflow/index.html')+'?view=h5#/mobile/'+row.id);await mobile.locator('.mobile-overview .mobile-state').waitFor();assert.equal(await mobile.locator('.mobile-overview .mobile-state').innerText(),row.state,row.id);
  if(expected[row.suffix])await mobile.locator('[data-action='+expected[row.suffix]+']').waitFor();
  assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),row.id+' overflow');
  assert.equal(await mobile.locator('[data-action=review],[data-action=risk],[data-action=withdraw],[data-action=escalate]').count(),0);
  if(['W04','P06','P15','P22','P26','H04','C07'].includes(row.suffix))await mobile.screenshot({path:out+'/h5-'+row.suffix+'.png',fullPage:true});
 }
 await mobile.goto(url('complaint-prototype/workflow/index.html')+'?view=h5#/mobile');await mobile.locator('[data-action=mobileFilter]').click();assert.deepEqual(await mobile.locator('[data-form=mobileFilters] [name=state] option').allTextContents(),['全部状态','待处理','处理中','审批中','待结案','已挂起','已结案']);await mobile.locator('[data-form=mobileFilters] [name=state]').selectOption('审批中');await mobile.locator('[data-form=mobileFilters] [name=task]').selectOption('payment');await mobile.screenshot({path:out+'/h5-filters.png'});await mobile.locator('[data-form=mobileFilters] [type=submit]').click();await mobile.locator('.mobile-ticket').first().waitFor();for(const value of await mobile.locator('.mobile-ticket .mobile-state').allTextContents())assert.equal(value,'审批中');for(const value of await mobile.locator('.mobile-ticket .mobile-node').allTextContents())assert.equal(value,'付款办理');
 const directory=await context.newPage();await directory.goto(url('complaint-prototype/demo.html'));await directory.locator('.directory-state-group').first().waitFor();assert.equal(await directory.locator('.directory-state-group').count(),6);assert.equal(await directory.locator('.directory-state-group .directory-scene').count(),49);assert(!(await directory.locator('#scene-links').innerText()).includes('回访'));assert.equal(await directory.locator('[data-demo-entry=close_service]').getAttribute('href'),'workflow/index.html?view=h5#/mobile/KS20261007-P14');await directory.screenshot({path:out+'/scenario-directory.png',fullPage:true});
 const prior=await f.locator('body').evaluate(()=>ComplaintStore.load());assert.deepEqual(prior.configuration,original.configuration);assert.deepEqual(prior.tickets,original.tickets);
 // Reading details leaves a pending ticket untouched; an unanswered saved follow-up starts handling.
 await mobile.goto(url('complaint-prototype/workflow/index.html')+'?view=h5#/mobile/KS20261007-W02');assert.equal(await mobile.locator('.mobile-overview .mobile-state').innerText(),'待处理');await mobile.locator('[data-action=follow]').click();const follow=mobile.locator('[data-form=follow]');await follow.locator('[name=connected]').selectOption('no');await follow.locator('[name=content]').fill('暂未接通，已记录本次联系，稍后继续跟进。');await follow.locator('[type=submit]').click();await follow.waitFor({state:'detached'});await mobile.locator('.mobile-overview .mobile-state').getByText('处理中',{exact:true}).waitFor();await mobile.reload();assert.equal(await mobile.locator('.mobile-overview .mobile-state').innerText(),'处理中');assert.equal(await mobile.locator('[data-action=proposal]').count(),0);
 const attempted=await mobile.evaluate(()=>ComplaintStore.load().tickets.find(t=>t.id==='KS20261007-W02'));assert.equal(attempted.firstContact,null);assert.equal(attempted.taskDeadline,original.tickets.find(t=>t.id===attempted.id).taskDeadline);
 await mobile.goto(url('complaint-prototype/workflow/index.html')+'?view=h5#/mobile/KS20261007-P14');await mobile.locator('[data-action=closeTicket]').click();let form=mobile.locator('[data-form=closeTicket]');await form.locator('[name=note]').fill('线下已核实服务协调完成，确认结案。');await form.locator('[name=completed]').check();await form.locator('[type=submit]').click();await form.waitFor({state:'detached'});await mobile.locator('.mobile-overview .mobile-state').getByText('已结案',{exact:true}).waitFor();await mobile.reload();assert.equal(await mobile.locator('.mobile-overview .mobile-state').innerText(),'已结案');await directory.reload();await directory.locator('[data-demo-entry=close_service]').getByText('KS20261007-P14 · 当前已结案',{exact:true}).waitFor();
 await mobile.goto(url('complaint-prototype/workflow/index.html')+'?view=h5#/demo/review');await mobile.locator('.mobile-overview .mobile-state').getByText('已结案',{exact:true}).waitFor();assert.equal(await mobile.locator('[data-action=review]').count(),0);assert.equal(await mobile.evaluate(key=>JSON.parse(localStorage.getItem(key)).tickets.length,KEY),63);assert.deepEqual(errors,[]);
 console.log('PASS: PC/H5 six status filters; all 49 scenarios show the correct status and live node action; separate phase filters; no retired callback/risk/withdraw actions; six scenario groups; stable IDs; old URL alias opens current closure; processing examples persist after completion; configuration untouched; no browser errors or mobile overflow.');
}finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
