/* Read-only flow projection and live approval advancement in an isolated H5 browser. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path');
const url=pathToFileURL(path.join(__dirname,'workflow/index.html')).href;
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Shanghai',reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(10000);
 const go=async suffix=>{await page.goto(url+'?view=h5#/mobile/KS20261007-'+suffix,{waitUntil:'domcontentloaded'});await page.locator('.mobile-process-card').waitFor();};
 const current=()=>page.locator('.mobile-process-node[aria-current=step]'),flow=()=>page.locator('.mobile-process-card'),rows=()=>page.locator('.mobile-process-node');
 const shot=async name=>{await flow().evaluate(el=>scrollTo(0,scrollY+el.getBoundingClientRect().top-120));await page.evaluate(()=>document.getAnimations().forEach(a=>a.finish()));await page.screenshot({path:'/tmp/complaint-h5-process-'+name+'.png'});};
 for(const suffix of ['P06','P07']){await go(suffix);assert.match(await current().locator('.process-assignee').innerText(),/孙琳/);assert.doesNotMatch(await current().locator('.process-assignee').innerText(),/陆清/);assert.match(await current().innerText(),/审批中/);assert.match(await current().innerText(),/预计 .*内完成/);assert.equal(await current().locator('[data-action=externalApproval]').count(),1);assert.equal(await page.locator('[data-action=approve],[data-action=reject]').count(),0);await shot(suffix);}
 await go('P08');assert.match(await current().locator('.process-assignee').innerText(),/陆清、孙琳/);assert.doesNotMatch(await current().innerText(),/或签/);
 await page.evaluate(()=>{const s=ComplaintStore.load(),t=s.tickets.find(t=>t.id.endsWith('-P08')),r=Engine.externalApprovalRecord(s,t);Engine.applyApprovalEvent(s,{id:'h5-instance-finish',instanceId:r.instanceId,scope:'instance',type:'finish',result:'agree',at:Date.now()+10});ComplaintStore.save(s);});await page.reload({waitUntil:'domcontentloaded'});await flow().waitFor();assert.match(await current().locator('h4').innerText(),/付款办理/);const finished=rows().filter({hasText:'付款审批'});assert.match(await finished.innerText(),/完成于/);assert.match(await finished.innerText(),/已通过/);
 await go('P34');assert.deepEqual(await rows().locator('h4').allTextContents(),['售后办理','付款办理','采购办理','售后结案']);assert.match(await rows().first().innerText(),/许宁/);assert.match(await rows().first().innerText(),/完成于/);assert.equal(await page.locator('.mobile-process-node.is-future .process-time').count(),0);await shot('payment');
 await page.evaluate(()=>{const s=ComplaintStore.load(),t=s.tickets.find(t=>t.id.endsWith('-P34'));t.taskDeadline=Date.now()-2.5*Engine.H;ComplaintStore.save(s);});await page.reload({waitUntil:'domcontentloaded'});await flow().waitFor();assert.match(await current().locator('.process-time').innerText(),/已超时 2小时/);assert(await current().locator('.process-time.is-overdue').isVisible());await shot('overdue');
 await go('P19');assert.match(await current().innerText(),/待分派/);assert.doesNotMatch(await current().locator('.process-assignee').innerText(),/林岚|林岑|经理/);assert.equal(await current().locator('.process-assignee b').innerText(),'待分派');assert.match(await current().innerText(),/没有有效办理人/);
 await go('P13');assert.equal(await current().locator('h4').innerText(),'售后办理');assert.doesNotMatch(await current().innerText(),/完成于/);assert.match(await rows().filter({hasText:'付款办理'}).innerText(),/已退回/);assert.match(await rows().filter({hasText:'付款办理'}).innerText(),/退回于/);assert.match(await rows().filter({hasText:'付款办理'}).innerText(),/完整收款账户/);await shot('returned');
 await go('H02');assert.match(await current().innerText(),/已挂起/);assert.match(await current().innerText(),/节点计时已暂停/);assert.match(await current().innerText(),/预计恢复/);assert.doesNotMatch(await current().innerText(),/内完成/);await shot('paused');
 await go('P38');assert.equal(await current().locator('h4').innerText(),'门店办理');assert.match(await current().innerText(),/首次联系/);assert.match(await current().innerText(),/首联截止/);assert.doesNotMatch(await current().innerText(),/内完成/);
 await go('P39');assert.deepEqual(await rows().locator('h4').allTextContents(),['门店办理','售后办理']);assert.match(await rows().first().innerText(),/已完成/);assert.match(await rows().first().innerText(),/周妍/);assert.match(await rows().first().innerText(),/继续售后办理/);assert.match(await current().innerText(),/许宁/);
 await go('C08');assert.deepEqual(await rows().locator('h4').allTextContents(),['门店办理','门店结案']);assert.equal(await page.locator('.mobile-process-node.is-done').count(),2);assert.doesNotMatch(await flow().innerText(),/待分派|办理中|未开始/);assert.match(await rows().last().innerText(),/周妍/);await shot('store-closed');
 await go('C06');assert.equal(await current().count(),0);assert.equal(await rows().count(),await page.locator('.mobile-process-node.is-done').count());assert.equal(await flow().locator('.process-time').count(),0);assert.match(await flow().innerText(),/流程已结束/);
 await go('W04');assert.equal(await current().count(),0);assert.match(await flow().innerText(),/确认客诉等级/);await go('W05');assert.equal(await current().count(),0);assert.match(await flow().innerText(),/尚未匹配到适用规则/);await go('W01');assert.match(await current().innerText(),/待分派/);assert.doesNotMatch(await current().innerText(),/内完成/);
 await go('P06');await page.getByRole('tab',{name:'操作记录',exact:true}).click();const before=await page.evaluate(()=>ComplaintStore.load()),t=before.tickets.find(t=>t.id.endsWith('-P06'));assert.equal(await page.locator('.record-timeline-card .event').count(),t.logs.length);assert.match(await page.locator('#mobile-panel-records').innerText(),/系统/);assert.equal(await page.getByRole('tab',{name:'处理记录',exact:true}).count(),0);await page.getByRole('tab',{name:'处理方案',exact:true}).click();assert.equal((await page.evaluate(()=>ComplaintStore.load()))._revision,before._revision);
 for(const suffix of ['P06','P08','P13','P19','P34','P38','H02','C06','C08','W05']){await go(suffix);await page.setViewportSize({width:320,height:720});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),suffix);assert.doesNotMatch(await flow().innerText(),/undefined|NaN/);assert(await rows().evaluateAll(nodes=>nodes.every(n=>n.scrollWidth<=n.clientWidth+1)),suffix);await page.setViewportSize({width:390,height:844});}
 assert.deepEqual(errors,[]);console.log('PASS H5 process: actual pending assignees, external approval current people and instance callback → payment, payment → procurement ordering, completed times, overdue and first-contact deadlines, paused clock, missing assignee, returned sales, source-store intake, direct/final closure, ungraded/unmatched tickets, complete operation logs, read-only rendering, 320/390px layout.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
