'use strict';
const assert=require('node:assert/strict'),E=require('./engine.js'),R=E.Rules,F=R.Flow;
const NOW=Date.parse('2026-09-29T10:00:00+08:00');let count=0;
function test(name,fn){fn();count++;console.log('通过：'+name);}
function setup(edit=()=>{}){
 let s=E.seed(NOW),d=R.prepareScene(R.sceneList(s)[0]);
 d.config.approval.flow=[{...F.node(),title:'主管审核',source:'duty',duty:'客诉主管',handling:{hours:4,overdue:'supervisor'}},{...F.node(),title:'财务审核',source:'duty',duty:'财务审核',handling:{hours:6,overdue:'supervisor'}}];
 edit(d,s);s=R.saveScene(s,'manager',d,0,NOW);let made=E.apply(s,'intake',{type:'create',data:{sceneId:d.id,customerId:'customer1',store:E.STORES[0],title:'处理规则验收',description:'验证实际办理行为'}},NOW);s=made.state;const id=made.caseId;let now=NOW;
 return {get s(){return s;},set s(value){s=value;},get c(){return s.cases.find(c=>c.id===id);},get now(){return now;},set now(value){now=value;},act(type,data={},who){const c=this.c,t=E.pending(c).find(t=>(!who||t.assigneeId===who)&&(t.kind===type||(type==='plan'&&t.kind==='plan')||({refundStart:'refundExecute'}[type]===t.kind)));assert(t,'缺少任务 '+type);s=E.apply(s,who||t.assigneeId,{type,caseId:id,taskId:t.id,expectedRevision:c.revision,data},now).state;},poll(at){now=at;s=E.refresh(s,at);},refund(){this.act('accept');this.act('contact',{result:'connected',content:'已联系'});this.act('plan',{planType:'refund',orderId:'order-r1',refundAmount:'600',refundReason:'未消费',summary:'退回余额',deadline:now+E.HOUR*10});},service(){this.act('accept');this.act('contact',{result:'connected',content:'已联系'});this.act('plan',{summary:'安排服务',deadline:now+E.HOUR,items:[{type:'解释道歉',description:'解释',assigneeId:'store1'}]});this.act('confirm',{version:1,decision:'agree',evidence:'客户接受'});this.act('service',{content:'已完成'});}};
}
test('节点无人审批时指定承接人，并沿用该节点的办理时效',()=>{const r=setup(d=>{d.config.approval.flow[0]={...F.node(),title:'门店审核',handling:{hours:3,overdue:'supervisor',emptyAssigneeId:'director'}};});r.act('accept');r.act('contact',{result:'connected',content:'已联系'});r.s.organization=F.organization(r.s);r.s.organization.departments.find(d=>d.store===E.STORES[0]).leaders=[];r.act('plan',{planType:'refund',orderId:'order-r1',refundAmount:'600',refundReason:'未消费',summary:'退款',deadline:NOW+E.HOUR*10});assert.equal(E.pending(r.c)[0].assigneeId,'director');assert.equal(E.pending(r.c)[0].dueAt,NOW+3*E.HOUR);});
test('节点承接人只在无人审批时生效，失效或自审不能继续派发',()=>{const s=E.seed(NOW),d=R.prepareScene(R.sceneList(s)[0]),org=F.organization(s),n={...F.node(),handling:{hours:3,overdue:'supervisor',emptyAssigneeId:'director'}},ctx={store:E.STORES[0],applicantId:'intake'};assert.deepEqual(F.resolveApprovers(d.config,org,n,ctx),[['store1']]);org.departments.find(x=>x.store===E.STORES[0]).leaders=[];assert.deepEqual(F.resolveApprovers(d.config,org,n,ctx),[['director']]);assert.throws(()=>F.resolveApprovers(d.config,org,n,{...ctx,applicantId:'director'}),/申请人/);org.appointments.find(x=>x.personId==='director').active=false;assert.throws(()=>F.resolveApprovers(d.config,org,n,ctx),/失效/);n.handling.emptyAssigneeId='';assert.throws(()=>F.resolveApprovers(d.config,org,n,ctx),/负责人/);});
test('空节点承接人与办理时效按节点保存，非法值拒绝保存',()=>{const s=E.seed(NOW),d=R.prepareScene(R.sceneList(s)[0]),n=R.approvalNodes(d.config.approval.flow)[0].node;n.handling.hours=7;n.handling.emptyAssigneeId='director';const saved=R.saveScene(s,'manager',d,0,NOW),read=R.prepareScene(R.sceneList(saved)[0]);assert.equal(R.approvalNodes(read.config.approval.flow)[0].node.handling.hours,7);assert.equal(R.approvalNodes(read.config.approval.flow)[0].node.handling.emptyAssigneeId,'director');for(const value of ['',0,-1,721]){n.handling.hours=value;assert.throws(()=>R.saveScene(s,'manager',d,0,NOW),/时限/);}n.handling.hours=7;n.handling.emptyAssigneeId='unknown';assert.throws(()=>R.saveScene(s,'manager',d,0,NOW),/承接人/);});
console.log(`完成 ${count} 项节点设置验证。`);
