/* Continuous desktop work sheet acceptance through the real host iframe. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path');
const url=pathToFileURL(path.resolve(__dirname,'../index.html')).href;
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Shanghai',reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(10000);
 await page.goto(url+'#complaint-tickets',{waitUntil:'domcontentloaded'});const f=page.frameLocator('#page-complaint-tickets iframe');await f.locator('.tickets-table').waitFor();
 const drawer=f.locator('.ticket-drawer'),body=f.locator('.pc-detail-layout'),main=f.locator('.pc-detail-main'),info=f.locator('.pc-ticket-information'),flow=f.locator('.pc-process-card'),current=()=>f.locator('.pc-process-node[aria-current=step]');
 const link=label=>f.locator('.pc-detail-nav').getByRole('button',{name:label,exact:true}),settle=()=>f.locator('body').evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 const open=async suffix=>{if(await drawer.count())await f.getByRole('button',{name:'关闭详情',exact:true}).click();const id='KS20261007-'+suffix;await f.locator('#filter-form [name=q]').fill(id);await f.locator('#filter-form [type=submit]').click();await f.locator('[data-action=detail][data-id="'+id+'"]').click();await drawer.waitFor();await settle();};
 const read=()=>f.locator('body').evaluate(()=>ComplaintStore.load());
 const shot=async name=>{await settle();await page.screenshot({path:'/tmp/complaint-pc-sheet-'+name+'.png'});};
 const go=async label=>{await link(label).click();await settle();assert.equal(await link(label).getAttribute('aria-current'),'location',label);};
 await open('P41');const original=await read();assert.equal(await drawer.getByRole('tab').count(),0);assert.equal(await f.locator('.pc-detail-section').count(),5);assert.equal(await f.locator('.pc-ticket-sidebar').count(),0);assert.match(await info.innerText(),/林女士/);assert.match(await f.locator('.pc-ticket-facts').innerText(),/付款办理/);assert.match(await f.locator('.pc-ticket-facts').innerText(),/陆清/);assert.equal(await f.locator('.plan-read-section').filter({hasText:'订单退款'}).locator('tbody tr').count(),2);assert.equal(await f.locator('.plan-read-section').filter({hasText:'置换商品'}).locator('tbody tr').count(),2);assert.match(await f.locator('.pc-solution-payable').innerText(),/500.00/);
 assert(await main.evaluate(el=>{const plan=el.querySelector('.plan-detail'),flow=el.querySelector('.pc-process-card');return !!(plan.compareDocumentPosition(flow)&Node.DOCUMENT_POSITION_FOLLOWING);}));assert.equal(await main.evaluate(el=>getComputedStyle(el).overflowY),'visible');await shot('overview');
 for(const [width,height] of [[1440,1000],[1366,768],[1280,900],[1024,800]]){await page.setViewportSize({width,height});await settle();assert(await drawer.evaluate(el=>[el,...el.querySelectorAll('.pc-detail-main,.pc-ticket-information,.card,.solution-table-wrap')].every(x=>x.scrollWidth<=x.clientWidth+1)),'overflow '+width);await shot('width-'+width);}await page.setViewportSize({width:1440,height:1000});
 await info.locator('[data-info-section=more]>summary').click();assert.match(await info.innerText(),/订单来源/);const headerBefore=await drawer.locator('.drawer-header').boundingBox();await go('处理方案');assert(await body.evaluate(el=>el.scrollTop>0));assert.deepEqual(await drawer.locator('.drawer-header').boundingBox(),headerBefore);await shot('solution');assert(await drawer.locator('.drawer-footer').isVisible());await go('处理流程');await shot('process');
 await go('操作记录');assert.equal(await link('操作记录').innerText(),'操作记录');assert.equal(await info.locator('[data-info-section=more]').getAttribute('open'),'');const t=original.tickets.find(t=>t.id.endsWith('-P41'));assert.equal(await f.locator('.pc-operation-event').count(),t.logs.length);assert.match(await f.locator('.pc-operation-card').innerText(),/系统/);await shot('records');
 await go('办理时效');assert.match(await f.locator('.pc-time-summary').innerText(),/整单截止/);assert.match(await f.locator('.suspension-metrics').innerText(),/有效办理耗时/);await shot('timing');assert.equal((await read())._revision,original._revision);
 await link('办理时效').press('Home');await settle();assert.equal(await link('工单信息').getAttribute('aria-current'),'location');await link('工单信息').press('ArrowRight');await settle();assert.equal(await link('处理方案').getAttribute('aria-current'),'location');await link('处理方案').press('End');await settle();assert.equal(await link('办理时效').getAttribute('aria-current'),'location');
 for(const [suffix,state] of [['W04','待处理'],['W05','待处理'],['W01','待处理'],['P39','处理中'],['P06','审批中'],['P13','处理中'],['H02','已挂起'],['P14','待结案'],['C08','已结案']]){
  await open(suffix);assert.match(await f.locator('.pc-ticket-badges').innerText(),new RegExp(state));assert.equal(await f.locator('.pc-detail-section').count(),5);
  if(suffix==='W01'){assert(await drawer.locator('[data-action=assign]').isVisible());assert.equal(await f.locator('.tickets-table [data-action=assign]').count(),0);assert.match(await f.locator('.pc-ticket-facts').innerText(),/待分派/);}
  if(suffix==='W04')assert(await drawer.locator('[data-action=confirmGrading]').isVisible());
  if(suffix==='W05')assert(await drawer.locator('[data-action=retryIntake]').isVisible());
  if(suffix==='P06'){assert.equal(await current().locator('.pc-process-assignee').innerText(),'孙琳');assert.match(await current().innerText(),/审批中/);assert.equal(await current().locator('[data-action=externalApproval]').count(),1);assert.equal(await drawer.locator('[data-action=approve],[data-action=reject]').count(),0);await go('处理流程');await shot('approval');}
  if(suffix==='P13'){assert.equal(await current().locator('.pc-process-title strong').innerText(),'售后办理');assert.doesNotMatch(await current().innerText(),/完成于/);assert.match(await flow.innerText(),/已退回/);}
  if(suffix==='H02'){assert.match(await f.locator('.pc-ticket-facts').innerText(),/节点计时已暂停/);await go('办理时效');assert.match(await f.locator('.aftercare-context').innerText(),/节点计时已暂停，整单继续计时/);assert(await drawer.locator('[data-action=resumeTicket]').isVisible());await shot('paused');}
  if(suffix==='C08'){assert.match(await f.locator('.pc-ticket-facts').innerText(),/周妍/);assert.match(await f.locator('.plan-detail').innerText(),/门店处理结果/);assert.equal(await current().count(),0);assert.match(await flow.innerText(),/门店结案/);await shot('closed');}
 }
 await open('P39');assert.equal(await drawer.locator('.action-buttons [data-action=closeEarly]').count(),0);assert.equal(await drawer.locator('.ticket-more-items [data-action=closeEarly]').count(),0);await info.locator('[data-info-section=more]>summary').click();await go('操作记录');const scroll=await body.evaluate(el=>el.scrollTop);await drawer.locator('[data-action=follow]').click();const form=f.locator('[data-form=follow]');await form.locator('[name=content]').fill('桌面连续详情保留当前阅读位置并记录本次跟进。');await form.locator('[name=result]').selectOption('plan');await form.locator('[type=submit]').click();await form.waitFor({state:'detached'});await f.locator('[data-form=proposal]').waitFor();await f.locator('#modal-root [data-action=closeModal]').first().click();await f.locator('[data-form=proposal]').waitFor({state:'detached'});await settle();assert.match(await f.locator('.pc-operation-card').innerText(),/保留当前阅读位置/);assert.equal(await info.locator('[data-info-section=more]').getAttribute('open'),'');assert(Math.abs(await body.evaluate(el=>el.scrollTop)-scroll)<2);
 await drawer.locator('[data-action=proposal]').click();assert(await f.locator('[data-form=proposal]').isVisible());await f.getByRole('button',{name:'关闭抽屉',exact:true}).click();await f.locator('[data-form=proposal]').waitFor({state:'detached'});assert.deepEqual(errors,[]);
 console.log('PASS PC continuous detail: one scroll surface, five section anchors with sticky navigation and keyboard support, horizontal information and amount summaries, complete refund/product tables, flow below solution, actual pending approvers, return/pause/closure, complete logs and timing, disclosures and reading position preserved after follow-up, manual assignment and closure through follow-up, 1024/1280/1366/1440px layout, no overflow or browser errors.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
