'use strict';
const assert=require('node:assert/strict'),E=require('./engine.js'),R=E.Rules,F=R.Flow;
const NOW=Date.parse('2026-09-29T10:00:00+08:00');let count=0;
function test(name,fn){fn();count++;console.log('通过：'+name);}
function setup(edit=()=>{}){
 let s=E.seed(NOW),d=R.prepareScene(R.sceneList(s)[0]);
 d.config.approval.flow=[{...F.node(),title:'主管审核',source:'duty',duty:'客诉主管',handling:{hours:4,overdue:'supervisor'}},{...F.node(),title:'财务审核',source:'duty',duty:'财务审核',handling:{hours:6,overdue:'supervisor'}}];
 edit(d,s);s=R.saveScene(s,'manager',d,0,NOW);let made=E.apply(s,'intake',{type:'create',data:{sceneId:d.id,customerId:'customer1',store:E.STORES[0],title:'处理规则验收',description:'验证实际办理行为'}},NOW);s=made.state;const id=made.caseId;let now=NOW;
 return {get s(){return s;},set s(value){s=value;},get c(){return s.cases.find(c=>c.id===id);},get now(){return now;},set now(value){now=value;},act(type,data={},who){const c=this.c,t=E.pending(c).find(t=>(!who||t.assigneeId===who)&&(t.kind===type||(type==='plan'&&t.kind==='plan')||({refundStart:'refundExecute'}[type]===t.kind)));assert(t,'缺少任务 '+type);s=E.apply(s,who||t.assigneeId,{type,caseId:id,taskId:t.id,expectedRevision:c.revision,data},now).state;},poll(at){now=at;s=E.refresh(s,at);},refund(){this.act('accept');this.act('contact',{result:'connected',content:'已联系'});this.act('plan',{planType:'refund',orderId:'order-r1',refundAmount:'600',refundReason:'未消费',summary:'退回余额',deadline:now+E.HOUR*10});},service(){this.act('accept');this.act('contact',{result:'connected',content:'已联系'});this.act('plan',{summary:'安排服务',deadline:now+E.HOUR,items:[{type:'解释道歉',description:'解释',assigneeId:'store1'}]});this.act('confirm',{version:1,decision:'agree',evidence:'客户接受'});this.act('service',{content:'已完成'});}};
}
const M=require('./node-assignment.js')(E);
test('岗位审批使用维护的人员，会签产生独立审批任务并保留节点时效',()=>{const r=setup((d,s)=>{s.nodeAssignmentRules=M.defaults();s.nodeAssignmentRules.positions.push({id:'custom-approval',name:'区域审批岗',members:['quality','director']});d.config.approval.flow[0]={...F.node(),title:'区域审核',source:'position',positionId:'custom-approval',positionName:'区域审批岗',handling:{hours:3,overdue:'supervisor',emptyAssigneeId:'manager'}};d.config.approval.flow[1]={...F.node(),title:'财务审核',source:'position',positionId:'finance',positionName:'财务付款岗',handling:{hours:4,overdue:'supervisor'}};});r.refund();assert.deepEqual(E.pending(r.c).map(t=>t.assigneeId),['quality','director']);assert.ok(E.pending(r.c).every(t=>t.dueAt===NOW+3*E.HOUR));r.act('refundApproval',{decision:'approve',content:'通过'},'quality');r.act('refundApproval',{decision:'approve',content:'通过'},'director');assert.equal(E.pending(r.c)[0].assigneeId,'finance');});
test('岗位成员变更用于后续匹配，空岗和失效人员进入兜底',()=>{const s=E.seed(NOW),d=R.prepareScene(R.sceneList(s)[0]);s.nodeAssignmentRules=M.defaults();s.nodeAssignmentRules.positions.push({id:'custom',name:'审批岗',members:['quality']});const n={...F.node(),source:'position',positionId:'custom',handling:{hours:4,overdue:'supervisor',emptyAssigneeId:'director'}},ctx={applicantId:'intake'};assert.deepEqual(F.resolveApprovers(d.config,F.organization(s),n,ctx),[['quality']]);s.nodeAssignmentRules.positions.at(-1).members=['manager'];assert.deepEqual(F.resolveApprovers(d.config,F.organization(s),n,ctx),[['manager']]);s.organization=F.organization(s);s.organization.appointments.find(p=>p.personId==='manager').active=false;assert.deepEqual(F.resolveApprovers(d.config,F.organization(s),n,ctx),[['director']]);});
test('保存时拒绝已删除岗位和非财务岗位作为退款末级审批',()=>{const s=E.seed(NOW),d=R.prepareScene(R.sceneList(s)[0]);d.config.approval.flow=[{...F.node(),source:'position',positionId:'missing'}];assert.throws(()=>R.saveScene(s,'manager',d,0,NOW),/岗位已删除/);d.config.approval.flow[0].positionId='aftercare';assert.throws(()=>R.saveScene(s,'manager',d,0,NOW),/财务/);d.config.approval.flow[0].positionId='finance';assert.doesNotThrow(()=>R.saveScene(s,'manager',d,0,NOW));});
console.log(`完成 ${count} 项岗位审批验证。`);
