'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Shanghai',reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(12000);
 const url=pathToFileURL(path.resolve(__dirname,'workflow/index.html')).href,go=async(suffix,mobile=false)=>{await page.goto(url+(mobile?'?view=h5#/mobile/':'#/tickets/')+'KS20261007-'+suffix,{waitUntil:'domcontentloaded'});await page.locator(mobile?'.mobile-process-card':'.pc-process-card').waitFor();};
 const state=()=>page.evaluate(()=>ComplaintStore.load()),saved=async id=>(await state()).tickets.find(t=>t.id==='KS20261007-'+id),form=()=>page.locator('[data-form=finishProcurement]'),submit=async()=>{await form().getByRole('button',{name:'确认发货',exact:true}).click();await form().waitFor({state:'detached'});},settle=()=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 // Both real navigation entries expose the new fillable procurement examples.
 const host=await context.newPage(),root=pathToFileURL(path.resolve(__dirname,'../index.html')).href;
 await host.goto(root+'#complaint-tickets',{waitUntil:'domcontentloaded'});const tickets=host.frameLocator('#page-complaint-tickets iframe');await tickets.locator('.tickets-table').waitFor();await tickets.locator('#filter-form [name=q]').fill('KS20261007-D17');await tickets.locator('#filter-form [type=submit]').click();assert.match(await tickets.locator('.tickets-table tbody').innerText(),/采购办理：待发货/);await tickets.getByRole('button',{name:'查看详情',exact:true}).click();await tickets.getByRole('button',{name:'采购发货',exact:true}).click();await tickets.locator('[data-form=finishProcurement]').waitFor();assert.equal(await tickets.locator('[data-form=finishProcurement] table tbody tr').count(),2);await host.screenshot({path:'/tmp/complaint-procurement-entry-pc.png'});await host.close();
 const directory=await context.newPage();await directory.goto(root+'#complaint-demo',{waitUntil:'domcontentloaded'});const scenes=directory.frameLocator('#page-complaint-demo iframe');await scenes.locator('[data-demo-entry=dingtalk-purchase-shipping]').waitFor();assert.equal(await scenes.locator('[data-demo-entry=dingtalk-shipment-pending]').count(),1);
 const [h5]=await Promise.all([context.waitForEvent('page'),scenes.locator('[data-demo-entry=dingtalk-shipment-pending]').click()]);await h5.waitForLoadState('domcontentloaded');await h5.getByRole('button',{name:'采购发货',exact:true}).click();const shipping=h5.locator('[data-form=finishProcurement]');await shipping.waitFor();assert.equal(await shipping.locator('table').count(),0);assert.deepEqual(await shipping.locator('[name=shipmentQuantity]').evaluateAll(es=>es.map(e=>e.value)),['1','1']);assert.equal((await h5.locator('.mobile-action-page').boundingBox()).width,430);await h5.screenshot({path:'/tmp/complaint-procurement-entry-h5.png'});await h5.close();await directory.close();
 await go('D03');assert.equal(await page.getByRole('button',{name:'采购发货',exact:true}).count(),0);
 await go('D08');const before=await saved('D08');await page.getByRole('button',{name:'采购发货',exact:true}).click();await form().waitFor();assert.deepEqual(await form().locator('[name=method] option').allTextContents(),['请选择发货方式','总部发货','门店发货','其他']);assert.equal(await form().locator('table tbody tr').count(),2);assert.equal(await form().locator('[name=completed],[name=files],[name=reference]').count(),0);
 await form().locator('[name=method]').selectOption('总部发货');await form().locator('[name=shipmentQuantity]').nth(0).fill('1');await form().locator('[name=shipmentQuantity]').nth(1).fill('0');await form().locator('[name=trackingNumber]').fill('SF-PARTIAL-1001');await form().locator('[name=note]').fill('修护霜先发 1 件，余下商品到货后发出。');await settle();await page.screenshot({path:'/tmp/complaint-procurement-shipping-pc.png'});await submit();
 let t=await saved('D08');assert.equal(t.currentAssignee,'procurement');assert.equal(t.execution.index,before.execution.index);assert.equal(t.taskDeadline,before.taskDeadline);assert.deepEqual(t.payments,before.payments);assert.equal(t.handlingRecords.at(-1).items.length,1);assert.equal(t.handlingRecords.at(-1).trackingNumber,'SF-PARTIAL-1001');assert.match(await page.locator('.shipment-records').innerText(),/SF-PARTIAL-1001/);assert.match(await page.locator('.pc-operation-list').innerText(),/采购发货/);
 await page.reload({waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'采购发货',exact:true}).click();assert.deepEqual(await form().locator('[name=shipmentQuantity]').evaluateAll(es=>es.map(e=>e.value)),['1','1']);await form().locator('[name=method]').selectOption('门店发货');await form().locator('[name=note]').fill('其余商品从门店发出');await submit();t=await saved('D08');assert.equal(t.state,'待结案');assert.equal(t.handlingRecords.filter(r=>r.action==='shipment').length,2);assert.equal(await page.getByRole('button',{name:'采购发货',exact:true}).count(),0);assert(await page.getByRole('button',{name:'确认结案',exact:true}).isVisible());assert.deepEqual(t.proposal,before.proposal);assert.deepEqual(t.payments,before.payments);
 await page.locator('.shipment-records').scrollIntoViewIfNeeded();await settle();await page.screenshot({path:'/tmp/complaint-procurement-shipping-pc-detail.png'});
 // Mobile uses an independent page with product cards, numerical steppers and a fixed action bar.
 await page.setViewportSize({width:390,height:844});await go('D14',true);await page.getByRole('button',{name:'采购发货',exact:true}).click();assert.equal(await form().locator('table').count(),0);assert.equal(await form().locator('.shipment-item').count(),2);assert.equal(await page.locator('.mobile-action-page[aria-label="采购发货"]').count(),1);
 await form().locator('[name=method]').selectOption('其他');await form().getByRole('button',{name:'减少发货数量',exact:true}).first().click();assert.equal(await form().locator('[name=shipmentQuantity]').first().inputValue(),'0');await form().getByRole('button',{name:'增加发货数量',exact:true}).first().click();assert.equal(await form().locator('[name=shipmentQuantity]').first().inputValue(),'1');await form().getByRole('button',{name:'增加发货数量',exact:true}).first().click();assert.equal(await form().locator('[name=shipmentQuantity]').first().inputValue(),'1');
 await form().locator('[name=trackingNumber]').fill('YT-SUPPLIER-1002');await form().locator('[name=note]').fill('余下商品由供应商发货');await form().locator('.shipment-method-section').scrollIntoViewIfNeeded();await settle();await page.screenshot({path:'/tmp/complaint-procurement-shipping-h5.png'});
 await page.setViewportSize({width:320,height:700});await settle();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await form().evaluate(f=>[...f.querySelectorAll('.solution-section,.shipment-item')].every(e=>e.scrollWidth<=e.clientWidth+1)));await page.screenshot({path:'/tmp/complaint-procurement-shipping-h5-320.png'});await submit();assert.equal((await saved('D14')).state,'待结案');assert.match(await page.locator('.shipment-records').innerText(),/YT-SUPPLIER-1002/);assert.equal(await page.locator('.shipment-records table').count(),0);
 await page.setViewportSize({width:390,height:844});await page.locator('.shipment-records').scrollIntoViewIfNeeded();await settle();await page.screenshot({path:'/tmp/complaint-procurement-shipping-h5-detail.png'});
 // An empty shipment stays editable and does not create a record or complete procurement.
 await page.goto(url+'?view=h5#/mobile/KS20261007-P31',{waitUntil:'domcontentloaded'});await page.getByRole('button',{name:'采购发货',exact:true}).click();await form().locator('[name=method]').selectOption('总部发货');await form().locator('[name=shipmentQuantity]').fill('0');await form().getByRole('button',{name:'确认发货',exact:true}).click();await form().locator('.error-slot').filter({hasText:'商品及数量'}).waitFor();assert.equal((await saved('P31')).phase,'待采购办理');assert.equal((await saved('P31')).handlingRecords?.filter(r=>r.action==='shipment').length||0,0);
 assert.deepEqual(errors,[]);console.log('PASS PC/H5 procurement shipping: approval gating, method options, PC table/mobile cards, quantities, partial shipping clock, full completion, immutable approved goods/funds, persistence, shipment details/logs, 320px layout, empty shipment rejection.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
