'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Shanghai',reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(12000);
 const url=f=>pathToFileURL(path.resolve(__dirname,f)).href;await page.goto(url('../index.html')+'#complaint-rules',{waitUntil:'domcontentloaded'});
 assert.deepEqual((await page.locator('#complaint-nav .nav-item').allTextContents()).map(t=>t.trim()),['客诉工单','规则配置','售后排班','审批管理','演示入口']);
 const f=page.frameLocator('#page-complaint-rules iframe'),table=f.locator('.scene-table'),basic=f.locator('.rule-basic-drawer');await table.waitFor();assert.equal(await table.locator('tbody tr').count(),5);assert.deepEqual(await f.getByRole('tab').allTextContents(),['审批场景','岗位人员']);
 const before=await f.locator('body').evaluate(()=>ComplaintStore.load());const fifth=table.locator('tbody tr').filter({hasText:'五级客诉'});
 await fifth.getByRole('button',{name:'编辑',exact:true}).click();assert.equal(await basic.getByLabel('定级条件',{exact:true}).inputValue(),before.configuration.ruleScenes.find(s=>s.level===5).grading.criteria);assert.equal(await basic.locator('[data-scene=description],input[type=checkbox]').count(),0);
 await basic.getByLabel('定级条件',{exact:true}).fill('发生严重损伤，需经理直接协调。');await basic.getByLabel('识别关键词',{exact:true}).fill('重度灼伤');await basic.getByLabel('排除条件',{exact:true}).fill('没有重度灼伤');await page.screenshot({path:'/tmp/complaint-rule-setup-scene.png'});await basic.getByRole('button',{name:'保存',exact:true}).click();await basic.waitFor({state:'detached'});
 assert.equal(await f.locator('body').evaluate(()=>AIGrading.classify(ComplaintStore.load().configuration,{description:'客户出现重度灼伤'}).level),5);
 await fifth.getByRole('button',{name:'流程配置',exact:true}).click();const canvas=f.locator('.ac-flow-canvas');assert.match(await f.locator('.ac-grading-node').innerText(),/五级/);assert.equal(await canvas.getByText('售后专员办理',{exact:true}).count(),0);assert.equal(await canvas.getByText('售后经理办理',{exact:true}).count(),1);
 for(let i=0;i<3;i++)await f.getByRole('button',{name:'缩小流程',exact:true}).click();await page.screenshot({path:'/tmp/complaint-rule-setup-five-flow.png'});
 await canvas.locator('.ac-node-handling').filter({hasText:'售后经理办理'}).locator('.ac-node-body').click();const form=f.locator('#flow-drawer-form');await form.waitFor();assert.equal(await form.locator('[name=kind]').inputValue(),'manager');assert.deepEqual(await form.locator('[name]').evaluateAll(es=>es.map(e=>e.name).sort()),['fallbackId','hours','kind','personId','title']);assert.equal(await form.locator('[name=source],[name=positionId],input[type=checkbox]').count(),0);await form.locator('[name=personId]').selectOption('jiang');await form.locator('[name=fallbackId]').selectOption('manager');await form.locator('[name=hours]').fill('6');await page.screenshot({path:'/tmp/complaint-rule-setup-manager.png'});await f.locator('[data-flow-save]').click();await form.waitFor({state:'detached'});
 await f.getByRole('button',{name:'保存配置',exact:true}).click();await table.waitFor();const updated=await f.locator('body').evaluate(()=>ComplaintStore.load()),n=updated.configuration.ruleScenes.find(s=>s.level===5).config.ticketFlow.nodes.find(n=>n.kind==='sales');assert.equal(n.personId,'jiang');assert.equal(n.fallbackId,'manager');assert.equal(n.hours,6);assert.deepEqual(updated.tickets,before.tickets);assert.deepEqual(updated.orders,before.orders);
 // The creation drawer has the same grading fields and no hidden enable switch.
 await f.getByRole('button',{name:'＋ 新建规则',exact:true}).click();await basic.getByLabel('审批场景名称',{exact:true}).fill('新审批场景');assert.equal(await basic.getByLabel('定级条件',{exact:true}).inputValue(),'');await basic.getByRole('button',{name:'保存',exact:true}).click();await basic.locator('#scene-basic-error').filter({hasText:'定级条件'}).waitFor();await basic.getByRole('button',{name:'取消',exact:true}).click();
 // A specialist remains a separate type, and the add-node type list includes manager.
 await table.locator('tbody tr').filter({hasText:'二级客诉'}).getByRole('button',{name:'流程配置',exact:true}).click();await canvas.locator('.ac-node-handling').filter({hasText:'售后专员办理'}).locator('.ac-node-body').click();assert.equal(await form.locator('[name=kind] option:checked').innerText(),'专员办理');assert.equal(await form.locator('[name=source]').count(),1);await f.locator('[data-flow-close]').first().click();
 await canvas.locator('.ac-node-handling').filter({hasText:'售后专员办理'}).locator('xpath=following-sibling::*[1]').locator('[data-flow-action=add]').click();await f.locator('.flow-add-menu [data-kind=handling]').click();assert.deepEqual(await form.locator('[name=kind] option').allTextContents(),['门店办理','专员办理','经理办理','付款办理','门店结案','售后结案','采购办理']);await form.locator('[name=kind]').selectOption('manager');assert.equal(await form.locator('[name=source]').count(),0);await f.locator('[data-flow-close]').first().click();await f.getByRole('button',{name:'‹ 返回',exact:true}).click();
 await f.getByRole('tab',{name:'岗位人员',exact:true}).click();await f.locator('.na-position-table').waitFor();assert.deepEqual(await f.locator('.na-position-table th').allTextContents(),['岗位名称','岗位成员 按轮排顺序','操作']);await page.screenshot({path:'/tmp/complaint-rule-setup-positions.png'});
 await page.locator('#complaint-nav .nav-item').filter({hasText:'售后排班'}).click();const schedule=page.frameLocator('#page-complaint-schedule iframe');await schedule.getByRole('tab',{name:'派单设置',exact:true}).click();const dispatch=schedule.locator('#schedule-dispatch-form');assert.equal(await dispatch.locator('input').count(),1);assert.equal(await schedule.locator('.schedule-rules').count(),0);assert.equal(await schedule.getByRole('button',{name:'编辑',exact:true}).count(),0);await dispatch.getByLabel('指定派单时间',{exact:true}).fill('10:15');await dispatch.getByRole('button',{name:'保存',exact:true}).click();await schedule.locator('#toast').filter({hasText:'派单设置已保存'}).waitFor();await page.screenshot({path:'/tmp/complaint-rule-setup-dispatch.png'});
 await page.locator('#complaint-nav .nav-item').filter({hasText:'审批管理'}).click();const approvals=page.frameLocator('#page-complaint-approvals iframe');await approvals.locator('.approval-table').waitFor();assert.equal((await page.locator('#complaint-nav .nav-item.active').innerText()).trim(),'审批管理');assert.equal(await approvals.locator('.approval-table [data-approval-action=template-records]').count(),0);assert.equal(await approvals.getByRole('tab',{name:'审批记录',exact:true}).count(),1);await page.screenshot({path:'/tmp/complaint-rule-setup-templates.png'});
 await page.reload({waitUntil:'domcontentloaded'});await page.locator('#complaint-nav .nav-item').filter({hasText:'售后排班'}).click();await schedule.getByRole('tab',{name:'派单设置',exact:true}).click();assert.equal(await dispatch.getByLabel('指定派单时间',{exact:true}).inputValue(),'10:15');
 await page.goto(url('index.html')+'?page=rules#rules/ai-grading',{waitUntil:'domcontentloaded'});await page.locator('.scene-table').waitFor();assert.equal(await page.getByRole('tab',{name:'AI 定级',exact:true}).count(),0);assert.deepEqual(errors,[]);
 console.log('PASS all 8 rule setup changes: unified scene grading and persistence, five-grade manager flow, distinct handling types, manager person/fallback/time fields, positions columns, menu order, template actions, direct dispatch-time save, old AI URL redirect, existing tickets and funds preserved.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
