(function(root){
  'use strict';
  const E=root.CaseEngine,R=E.Rules;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const person=id=>E.STAFF.find(p=>p.id===id)?.name||id;
  const levels=[[1,'一级'],[2,'二级'],[3,'三级'],[4,'四级'],[5,'五级']];
  const input=(label,path,value,type='text',extra='')=>`<label class="rule-field"><span>${label}</span><input data-scene="${path}" aria-label="${label}" type="${type}" value="${esc(value)}" ${extra}></label>`;
  const select=(label,path,options,value)=>`<label class="rule-field"><span>${label}</span><select data-scene="${path}" aria-label="${label}">${options.map(([v,t])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;
  const toggle=(label,path,value)=>`<label class="scene-check"><input type="checkbox" data-scene="${path}" ${value?'checked':''}>${label}</label>`;
  const people=ids=>E.STAFF.filter(p=>ids.includes(p.id)).map(p=>[p.id,p.name+' · '+p.role]);
  function flowSummary(d,state){const prepared=window.TicketFlowConfig?window.TicketFlowConfig.prepare(state,R.prepareScene(d)):R.prepareScene(d);return R.Flow.summary(prepared.config.ticketFlow?.nodes||prepared.config.approval.flow);}
  function filterBar(filters){return `<form id="scene-filters" class="filters"><input name="keyword" aria-label="审批场景名称" placeholder="搜索审批场景名称" value="${esc(filters.keyword)}"><select name="status" aria-label="审批场景状态"><option value="">全部状态</option><option value="true" ${filters.status==='true'?'selected':''}>启用</option><option value="false" ${filters.status==='false'?'selected':''}>停用</option></select><button class="btn" type="submit">查询</button><button class="btn quiet" type="button" data-scene-action="reset-filter">重置</button></form>`;}
  function list(state,filters){
    const all=R.sceneList(state),rows=all.filter(s=>(!filters.keyword||(s.name+' '+s.description).includes(filters.keyword))&&(!filters.status||String(s.enabled)===filters.status));
    return `<section class="panel"><div class="table-wrap"><table class="scene-table"><thead><tr><th>审批场景名称</th><th>客诉等级</th><th>整单办结时限</th><th>工单办理流程</th><th>状态</th><th>操作</th></tr></thead><tbody>${rows.map(s=>`<tr><td><strong>${esc(s.name)}</strong></td><td>${levels.find(([v])=>v===s.level)[1]}</td><td>${s.config.timing.targetHours} 小时</td><td class="scene-flow-summary">${esc(flowSummary(s,state))}</td><td><span class="badge ${s.enabled?'green':''}">${s.enabled?'启用':'停用'}</span></td><td class="nowrap scene-rule-actions"><button class="btn quiet compact blue" data-scene-action="edit" data-id="${esc(s.id)}">流程配置</button><button class="btn quiet compact blue" data-scene-action="edit-basic" data-id="${esc(s.id)}">编辑</button><button class="btn quiet compact" data-scene-action="toggle" data-id="${esc(s.id)}">${s.enabled?'停用':'启用'}</button></td></tr>`).join('')||'<tr><td colspan="6"><div class="empty"><h3>暂无符合条件的审批场景</h3><p>可调整查询条件，或新建一个审批场景。</p></div></td></tr>'}</tbody></table></div><div class="table-foot">共 ${rows.length} 个审批场景</div></section><p class="small muted mt">每个审批场景独立维护办理节点、审批节点及各节点时限。</p>`;
  }
  function basic(d){return `<section class="scene-section"><h2>审批场景信息</h2><div class="rule-grid">${input('审批场景名称','name',d.name,'text','maxlength="30" placeholder="例如：四级客诉" required')}${select('客诉等级','level',levels,d.level)}${input('首次联系时限（小时）','config.timing.firstContactHours',d.config.timing.firstContactHours,'number','min="0.25" max="720" step="0.25" required')}${input('整单时限（小时）','config.timing.targetHours',d.config.timing.targetHours,'number','min="0.25" max="720" step="0.25" required')}<label class="rule-field full"><span>定级条件 <span class="required">*</span></span><textarea data-scene="grading.criteria" aria-label="定级条件" rows="3" maxlength="1000" placeholder="填写该等级的判断条件" required>${esc(d.grading?.criteria)}</textarea></label><label class="rule-field full"><span>识别关键词</span><textarea data-scene="grading.keywords" aria-label="识别关键词" rows="2" maxlength="500" placeholder="多个关键词用逗号分隔">${esc(d.grading?.keywords)}</textarea></label><label class="rule-field full"><span>排除条件</span><textarea data-scene="grading.exclusions" aria-label="排除条件" rows="2" maxlength="500" placeholder="填写不属于该等级的情况">${esc(d.grading?.exclusions)}</textarea></label></div></section>`;}
  function approval(d,state){return window.ApprovalFlowUI.canvas(d,state);}
  function editor(state,d,tab){
    return `<div class="approval-config-page"><div class="page-heading scene-editor-heading secondary-page-heading approval-config-heading"><div><button class="btn quiet blue secondary-page-back approval-back" data-scene-action="back">‹ 返回</button><h1>流程配置</h1></div><button class="btn primary" type="submit" form="rules-form">保存配置</button></div><section class="panel scene-editor"><form id="rules-form" novalidate><div id="rules-error" class="form-error callout error" role="alert"></div>${approval(d,state)}</form></section></div>`;
  }
  function read(form,draft){
    const d=JSON.parse(JSON.stringify(draft));form?.querySelectorAll('[data-scene]').forEach(el=>{if(el.type==='radio'&&!el.checked)return;const keys=el.dataset.scene.split('.'),key=keys.pop();let obj=d;keys.forEach(k=>obj=obj[k]||(obj[k]={}));obj[key]=el.type==='checkbox'?el.checked:el.type==='number'?(el.value===''?'':Number(el.value)):el.value;});d.level=Number(d.level);return d;
  }
  root.RuleSettingsView={list,editor,read,filterBar,basicEditor:basic};
})(window);
