'use strict';
const assert=require('node:assert/strict'),E=require('./engine.js'),R=E.Rules;
const NOW=Date.parse('2026-09-29T10:00:00+08:00');let count=0;
function test(name,fn){fn();count++;console.log('通过：'+name);}
const create=(s,id,more={})=>E.apply(s,'intake',{type:'create',data:{sceneId:id,sceneRevision:s.sceneRevision||0,customerId:'customer1',store:E.STORES[0],title:'场景规则验收',description:'核对场景规则',autoAssign:true,...more}},NOW);
function act(s,id,type,data={}){const c=s.cases.find(c=>c.id===id),t=E.pending(c)[0];return E.apply(s,t.assigneeId,{type,caseId:id,taskId:t.id,expectedRevision:c.revision,data},NOW+60000).state;}
test('默认四个独立场景，读取列表不改动历史工单',()=>{const s=E.demo(NOW),before=JSON.stringify(s),list=R.sceneList(s);assert.deepEqual(list.map(x=>x.level),[1,2,3,4]);list[0].config.timing.firstContactHours=7;assert.equal(list[1].config.timing.firstContactHours,2);assert.equal(JSON.stringify(s),before);});
test('新建场景可独立保存，重读JSON后仍可配置',()=>{let s=E.seed(NOW),d=R.newScene(s);d.name='预约等待专项';d.config.timing.firstContactHours=1;s=R.saveScene(s,'manager',d,0,NOW);assert.equal(s.ruleScenes.length,5);assert.equal(s.sceneHistory.length,1);const saved=R.sceneList(JSON.parse(JSON.stringify(s))).at(-1);assert.equal(saved.version,1);assert.equal(saved.config.timing.firstContactHours,1);});
test('同名场景、空名称、等级越界和非法时限阻止保存',()=>{const s=E.seed(NOW),d=R.newScene(s);assert.throws(()=>R.saveScene(s,'manager',d,0,NOW),/名称/);d.name='一级客诉';assert.throws(()=>R.saveScene(s,'manager',d,0,NOW),/重复/);d.name='新场景';d.level=5;assert.throws(()=>R.saveScene(s,'manager',d,0,NOW),/等级/);d.level=4;d.config.timing.firstContactHours=0;assert.throws(()=>R.saveScene(s,'manager',d,0,NOW),/时限/);});
test('场景保存仅主管可做且拒绝跨窗口覆盖',()=>{const s=E.seed(NOW),d=R.sceneList(s)[0];assert.throws(()=>R.saveScene(s,'store1',d,0,NOW),/主管/);const next=R.saveScene(s,'manager',d,0,NOW);assert.throws(()=>R.saveScene(next,'manager',d,0,NOW),/其他窗口/);});
test('停用不删历史，禁止新单选择，必须保留一个可用场景',()=>{let s=E.seed(NOW);const made=create(s,'scene-level-1');s=made.state;const old=JSON.stringify(s.cases);s=R.toggleScene(s,'manager','scene-level-1',0,NOW);assert.equal(JSON.stringify(s.cases),old);assert.throws(()=>create(s,'scene-level-1'),/停用/);for(const level of [2,3])s=R.toggleScene(s,'manager','scene-level-'+level,s.sceneRevision,NOW);assert.throws(()=>R.toggleScene(s,'manager','scene-level-4',s.sceneRevision,NOW),/至少保留/);});
test('四级场景产生四级工单并由主管承接，无未定义标签',()=>{const made=create(E.seed(NOW),'scene-level-4'),c=made.state.cases[0];assert.equal(c.level,4);assert.equal(E.pending(c)[0].assigneeId,'manager');assert.equal(c.rulesSnapshot.scene.name,'四级客诉');});
test('场景可以单独选择按店派单，不再按等级强制覆盖',()=>{let s=E.seed(NOW),d=R.sceneList(s)[3];d.config.routing.sceneMode='store';s=R.saveScene(s,'manager',d,0,NOW);const c=create(s,d.id).state.cases[0];assert.equal(c.level,4);assert.equal(E.pending(c)[0].assigneeId,'store1');});
test('新场景独立时限生效，旧工单和其他场景不被修改',()=>{let s=E.seed(NOW),first=create(s,'scene-level-1');s=first.state;const before=JSON.stringify(s.cases[0]),d=R.sceneList(s)[0];d.config.timing.firstContactHours=1;s=R.saveScene(s,'manager',d,0,NOW);const next=create(s,d.id);assert.equal(next.state.cases[0].firstContactDue,NOW+E.HOUR);assert.equal(next.state.cases[0].rulesSnapshot.scene.version,2);assert.equal(JSON.stringify(next.state.cases.find(c=>c.id===first.caseId)),before);assert.equal(R.sceneList(s)[1].config.timing.firstContactHours,2);});
test('金额条件按严格大于判断，节点顺序与新增节点生效',()=>{const s=E.seed(NOW),d=R.sceneList(s)[0];d.config.approval.nodes.splice(1,0,{assigneeId:'director',condition:'always',amount:0});d.config.approval.delegateId='quality';const valid=R.validateScene(s,d);assert.deepEqual(R.approvalPreview(valid.config,'refund',500),['director','finance']);assert.deepEqual(R.approvalPreview(valid.config,'refund',500.01),['manager','director','finance']);});
test('审批重复人员、空流程、财务被跳过及代审冲突均阻止保存',()=>{const s=E.seed(NOW),draft=()=>R.sceneList(s)[0];let d=draft();delete d.config.approval.nodes;assert.throws(()=>R.validateScene(s,d),/审批流程/);d=draft();d.config.approval.nodes=[];assert.throws(()=>R.validateScene(s,d),/1至5/);d=draft();d.config.approval.nodes[0].assigneeId='finance';assert.throws(()=>R.validateScene(s,d),/重复/);d=draft();d.config.approval.nodes.at(-1).condition='amountAbove';assert.throws(()=>R.validateScene(s,d),/财务/);d=draft();d.config.approval.delegateId='quality';d.config.approval.nodes[0].assigneeId='quality';assert.throws(()=>R.validateScene(s,d),/替代/);});
test('新配置不能静默套用到已经打开的填单表单',()=>{const s=E.seed(NOW),next=R.saveScene(s,'manager',R.sceneList(s)[0],0,NOW);assert.throws(()=>create(next,'scene-level-1',{sceneRevision:0}),/场景配置已更新/);});
test('自定义审批链贯通实际退款任务并进入负责人意见待办',()=>{let s=E.seed(NOW),d=R.sceneList(s)[0];d.config.approval.nodes.splice(1,0,{assigneeId:'director',condition:'always',amount:0});d.config.approval.delegateId='quality';s=R.saveScene(s,'manager',d,0,NOW);let r=create(s,d.id);s=r.state;const id=r.caseId;s=act(s,id,'accept');s=act(s,id,'contact',{result:'connected',content:'已核实订单'});s=act(s,id,'plan',{planType:'refund',orderId:'order-r1',refundAmount:'600',refundReason:'未使用服务',summary:'按原路退回',deadline:NOW+24*E.HOUR});for(const who of ['manager','director','finance']){assert.equal(E.pending(s.cases[0])[0].assigneeId,who);s=act(s,id,'refundApproval',{decision:'approve',content:'核对通过'});}assert.equal(s.cases[0].stage,'confirm');assert.equal(E.pending(s.cases[0])[0].assigneeId,'store1');});
console.log(`完成 ${count} 项场景配置验证。`);
