(function(){
'use strict';
const M=AftercareSchedule,Store=CaseStore,$=q=>document.querySelector(q),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const params=new URLSearchParams(location.search),actor=params.get('actor')||'manager',days=['日','一','二','三','四','五','六'];
let state,tab=['shifts','roster','dispatch'].includes(location.hash.slice(1))?location.hash.slice(1):'roster',week=M.dateKey(),query='',selected=new Set(),dialog=null,lastFocus,toastTimer;
const monday=day=>M.addDays(day,-((new Date(day+'T12:00:00+08:00').getUTCDay()+6)%7));week=monday(week);
const action=(a,extra='')=>`data-schedule-action="${a}" ${extra}`,button=(text,a,cls='btn',extra='')=>`<button type="button" class="${cls}" ${action(a,extra)}>${text}</button>`;
const time=s=>s.start+' – '+(M.minutes(s.end)<M.minutes(s.start)?'次日 ':'')+s.end;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function render(){
 state=Store.load();const config=M.get(state),staff=M.staff(state);selected=new Set([...selected].filter(id=>staff.some(p=>p.id===id)));
 document.body.classList.toggle('embedded',params.get('embed')==='1');document.body.classList.add('schedule-page');
 $('#application').innerHTML=`<div class="pc-shell"><aside class="side"><div class="brand"><span class="brand-mark">✦</span><div><strong>美业AI平台</strong><small>SERVICE OPERATIONS</small></div></div><div class="side-label">客诉管理</div><a class="nav" href="workflow/index.html#/tickets">客诉工单</a><a class="nav" href="index.html?page=rules#rules/scenes">规则配置</a><a class="nav active" href="schedule.html">售后排班</a><a class="nav" href="approvals.html">审批管理</a></aside><main class="main"><header class="pc-header"><span>客诉管理 / 售后排班</span><div class="row"><span>林岚 · 售后主管</span><span class="avatar">林</span></div></header><div class="page-body">${actor!=='manager'?'<div class="empty"><h3>暂无配置权限</h3><p>售后排班由授权主管维护。</p></div>':`<div class="page-heading"><div><h1>售后排班</h1><p>维护售后班次、人员排班及每日派单时间。</p></div>${tab==='shifts'?button('＋ 新增班次','new-shift','btn primary'):tab==='roster'?button('批量排班','batch','btn primary'):''}</div><section class="panel rules-query-panel"><nav class="tabs schedule-tabs" role="tablist" aria-label="售后排班">${[['shifts','班次设置'],['roster','人员排班'],['dispatch','派单设置']].map(([id,label])=>`<button type="button" role="tab" aria-selected="${tab===id}" class="${tab===id?'active':''}" ${action('tab',`data-tab="${id}"`)}>${label}</button>`).join('')}</nav></section>${tab==='shifts'?shifts(config):tab==='dispatch'?dispatch(config):roster(config,staff)}`}</div></main></div>`;
 syncRosterSelection();
}
function shifts(c){return `<section class="panel"><div class="table-wrap"><table class="scene-table schedule-shifts"><thead><tr><th>班次名称</th><th>工作时段</th><th>班次时长</th><th>操作</th></tr></thead><tbody>${c.shifts.map(s=>`<tr><td><span class="schedule-shift-tag ${s.id==='late'?'late':''}">${esc(s.name)}</span></td><td>${esc(time(s))}</td><td>${((M.minutes(s.end)-M.minutes(s.start)+1440)%1440)/60} 小时</td><td>${button('编辑','edit-shift','btn quiet compact blue',`data-id="${esc(s.id)}"`)}${button('删除','delete-shift','btn quiet compact blue',`data-id="${esc(s.id)}"`)}</td></tr>`).join('')}<tr><td><span class="schedule-shift-tag rest">休息</span></td><td>不参与新单分配</td><td>—</td><td><span class="small muted">固定选项</span></td></tr></tbody></table></div></section><p class="schedule-help">班次支持跨日，结束时间早于开始时间时按次日计算。时间均为北京时间。</p>`;}
function roster(c,staff){
 const dates=Array.from({length:7},(_,i)=>M.addDays(week,i)),today=M.dateKey(),rows=staff.filter(p=>(p.name+' '+p.positions.join(' ')).includes(query));
 const weekLabel=week.replaceAll('-','/')+' — '+dates.at(-1).slice(5).replace('-','/');
 const chevron=direction=>`<svg class="ico" viewBox="0 0 24 24" aria-hidden="true"><path d="${direction==='prev'?'m14 7-5 5 5 5':'m10 7 5 5-5 5'}"/></svg>`;
 const calendar='<svg class="ico" viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 10h16"/></svg>';
 const dayClass=day=>day===today?'schedule-today':[0,6].includes(new Date(day+'T12:00:00+08:00').getUTCDay())?'schedule-weekend':'';
 return `<section class="panel schedule-roster-panel">
  <div class="schedule-toolbar">
   <div class="schedule-week">
    <div class="schedule-week-nav">${button(chevron('prev'),'prev','btn schedule-nav-button','aria-label="上一周"')}${button(chevron('next'),'next','btn schedule-nav-button','aria-label="下一周"')}</div>
    <label class="schedule-range">${calendar}<strong>${weekLabel}</strong><input type="date" data-schedule-date aria-label="排班日期" title="选择排班周" value="${week}"></label>
    ${button('本周','today','btn compact schedule-this-week')}
   </div>
   <form id="schedule-search"><div class="schedule-search-control"><svg class="ico" viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4 4"/></svg><input class="schedule-search" name="query" aria-label="搜索员工或岗位" placeholder="搜索员工或岗位" value="${esc(query)}"></div><button class="btn" type="submit">查询</button></form>
  </div>
  <div class="schedule-overview"><div class="schedule-counts"><span class="schedule-staff-count">售后员工 <b>${staff.length}</b></span><span>当前当班 <b>${staff.filter(p=>M.duty(state,p.id)).length}</b></span><span>今日休息 <b>${staff.filter(p=>c.roster[today]?.[p.id]==='rest').length}</b></span><span>今日未排班 <b>${staff.filter(p=>!c.roster[today]?.[p.id]).length}</b></span></div><div class="schedule-legend" aria-label="班次图例">${c.shifts.map(s=>`<span class="${s.id==='late'?'late':'early'}"><i aria-hidden="true"></i>${esc(s.name)}</span>`).join('')}<span class="rest"><i aria-hidden="true"></i>休息</span></div></div>
  ${rows.length?`<div class="table-wrap schedule-roster-scroll"><table class="schedule-table" aria-label="${weekLabel} 售后排班表"><thead><tr><th scope="col"><input type="checkbox" data-schedule-all aria-label="全选当前员工"></th><th scope="col">售后员工</th>${dates.map(day=>`<th scope="col" class="${dayClass(day)}"><span class="schedule-day-label">${day.slice(5).replace('-','/')}</span><small>周${days[new Date(day+'T12:00:00+08:00').getUTCDay()]}${day===today?' · 今天':''}</small></th>`).join('')}</tr></thead><tbody>${rows.map(p=>`<tr><td><input type="checkbox" data-schedule-person="${p.id}" aria-label="选择${esc(p.name)}" ${selected.has(p.id)?'checked':''}></td><td><div class="schedule-employee"><span class="schedule-employee-avatar" aria-hidden="true">${esc(Array.from(p.name)[0])}</span><span><strong>${esc(p.name)}</strong><small>${esc(p.positions.join('、')||p.role)}</small></span></div></td>${dates.map(day=>{const value=c.roster[day]?.[p.id],shift=c.shifts.find(s=>s.id===value),label=shift?.name||(value==='rest'?'休息':'未排班'),kind=value==='rest'?'rest':!shift?'empty':shift.id==='late'?'late':'early';return `<td class="${dayClass(day)}"><button type="button" class="schedule-cell ${kind}" ${action('cell',`data-person="${p.id}" data-date="${day}"`)} aria-label="${esc(p.name)} ${day} ${esc(label)}"><span class="schedule-cell-name">${!shift&&value!=='rest'?'<span class="schedule-cell-plus" aria-hidden="true">＋</span>':''}${esc(label)}</span>${shift?`<small>${esc(time(shift))}</small>`:''}</button></td>`;}).join('')}</tr>`).join('')}</tbody></table></div>`:`<div class="schedule-empty"><p>${staff.length?'没有匹配的售后员工':'请先在规则配置的岗位人员中添加售后办理人员'}</p></div>`}
  <div class="schedule-selection" hidden><span aria-live="polite">已选择 <b data-selected-count>${selected.size}</b> 位员工</span>${button('清空选择','clear-selection','btn quiet compact')}${button('批量排班','batch','btn compact primary')}</div>
 </section>`;
}
function syncRosterSelection(){
 const inputs=[...document.querySelectorAll('[data-schedule-person]')],all=$('[data-schedule-all]');
 for(const input of inputs){input.checked=selected.has(input.dataset.schedulePerson);input.closest('tr').classList.toggle('is-selected',input.checked);}
 if(all){all.checked=inputs.length>0&&inputs.every(input=>input.checked);all.indeterminate=inputs.some(input=>input.checked)&&!all.checked;}
 if($('[data-selected-count]'))$('[data-selected-count]').textContent=selected.size;
 if($('.schedule-selection'))$('.schedule-selection').hidden=selected.size===0;
}
function dispatch(c){return `<section class="panel schedule-settings"><div class="panel-head"><h3>售后新单分配</h3></div><div class="panel-body"><form id="schedule-dispatch-form" class="schedule-dispatch-form"><label class="rule-field"><span>指定派单时间</span><input type="time" name="dispatchStart" aria-label="指定派单时间" value="${esc(c.dispatchStart)}" required></label><button type="submit" class="btn primary">保存</button></form></div></section>`;}
function open(type,data={}){
 if(actor!=='manager')return;state=Store.load();const c=M.get(state);lastFocus=document.activeElement;dialog={type,data,c,version:c.version,saving:false};let title,body;
 if(type==='shift'){const s=c.shifts.find(s=>s.id===data.id)||{name:'',start:'09:00',end:'18:00'};title=data.id?'编辑班次':'新增班次';body=`<div class="rule-grid"><label class="rule-field full"><span>班次名称</span><input name="name" aria-label="班次名称" maxlength="20" value="${esc(s.name)}" required></label><label class="rule-field"><span>开始时间</span><input name="start" aria-label="开始时间" type="time" value="${s.start}" required></label><label class="rule-field"><span>结束时间</span><input name="end" aria-label="结束时间" type="time" value="${s.end}" required></label></div><p class="schedule-help">结束时间早于开始时间表示次日结束。修改后，使用该班次的排班同步更新。</p>`;}

 else{const staff=M.staff(state),ids=data.person?[data.person]:[...selected],value=data.person?(c.roster[data.date]?.[data.person]||'early'):'early';title=data.person?'调整排班':'批量排班';body=`<section class="schedule-drawer-section"><h3>售后员工</h3><div class="schedule-people">${staff.map(p=>`<label class="schedule-person"><input type="checkbox" name="people" value="${p.id}" ${ids.includes(p.id)?'checked':''}><span>${esc(p.name)}</span></label>`).join('')||'<p class="small muted">暂无可排班的售后员工，请先维护岗位人员。</p>'}</div></section><section class="schedule-drawer-section"><h3>排班日期</h3><div class="rule-grid"><label class="rule-field"><span>开始日期</span><input type="date" name="start" aria-label="开始日期" value="${data.date||week}" required></label><label class="rule-field"><span>结束日期</span><input type="date" name="end" aria-label="结束日期" value="${data.date||M.addDays(week,6)}" required></label></div><div class="schedule-weekdays">${[1,2,3,4,5,6,0].map(day=>`<label><input type="checkbox" name="weekdays" value="${day}" checked>周${days[day]}</label>`).join('')}</div></section><section class="schedule-drawer-section"><h3>安排班次</h3><label class="rule-field"><span>班次</span><select name="shift" aria-label="班次">${[...c.shifts.map(s=>[s.id,s.name+' · '+time(s)]),['rest','休息'],['','清空排班']].map(([id,label])=>`<option value="${id}" ${value===id?'selected':''}>${esc(label)}</option>`).join('')}</select></label><p class="schedule-help">保存后覆盖所选员工在所选日期的原排班，其他日期保持不变。</p></section>`;}
 $('#modal-root').innerHTML=`<div class="overlay"><section class="drawer schedule-drawer" role="dialog" aria-modal="true" aria-labelledby="schedule-dialog-title"><header class="drawer-head"><h2 id="schedule-dialog-title">${title}</h2>${button('×','close','close','aria-label="关闭"')}</header><form id="schedule-form" novalidate><div class="drawer-scroll"><div id="schedule-error" class="form-error callout error" role="alert"></div>${body}</div><footer class="form-actions">${button('取消','close')}<button type="submit" class="btn primary">保存</button></footer></form></section></div>`;document.body.style.overflow='hidden';$('#schedule-form input')?.focus();
}
function close(){if(dialog?.saving)return;dialog=null;$('#modal-root').innerHTML='';document.body.style.overflow='';lastFocus?.focus();}
async function persist(draft,version){await Store.exclusive(()=>{const fresh=Store.load(),next=M.save(fresh,actor,draft,version);Store.save(next);});window.dispatchEvent(new Event('complaint-schedule-updated'));}
document.addEventListener('click',async e=>{if(e.target.matches('[data-schedule-date]')){try{e.target.showPicker?.();}catch{}return;}const b=e.target.closest('[data-schedule-action]');if(!b)return;try{const a=b.dataset.scheduleAction;if(a==='tab'){tab=b.dataset.tab;history.replaceState(null,'','#'+tab);render();}if(a==='prev'||a==='next'){week=M.addDays(week,a==='prev'?-7:7);render();}if(a==='today'){week=monday(M.dateKey());render();}if(a==='new-shift'||a==='edit-shift')open('shift',{id:b.dataset.id});if(a==='batch')open('batch');if(a==='clear-selection'){selected.clear();syncRosterSelection();}if(a==='cell')open('batch',{person:b.dataset.person,date:b.dataset.date});if(a==='close')close();if(a==='delete-shift'){const c=M.get(Store.load());if(Object.values(c.roster).some(row=>Object.values(row).includes(b.dataset.id)))throw Error('该班次已有排班，请先调整相关员工的班次');if(!confirm('删除此班次？'))return;c.shifts=c.shifts.filter(s=>s.id!==b.dataset.id);await persist(c,c.version);render();toast('班次已删除');}}catch(error){toast(error.message);}});
document.addEventListener('change',e=>{
 if(e.target.hasAttribute('data-schedule-date')&&M.isDate(e.target.value)){week=monday(e.target.value);render();}
 if(e.target.hasAttribute('data-schedule-all'))document.querySelectorAll('[data-schedule-person]').forEach(input=>{e.target.checked?selected.add(input.dataset.schedulePerson):selected.delete(input.dataset.schedulePerson);});
 if(e.target.dataset.schedulePerson){e.target.checked?selected.add(e.target.dataset.schedulePerson):selected.delete(e.target.dataset.schedulePerson);}
 syncRosterSelection();
});
document.addEventListener('submit',async e=>{if(e.target.id==='schedule-dispatch-form'){e.preventDefault();if(actor!=='manager')return;const submit=e.target.querySelector('[type=submit]'),draft=M.get(state);draft.dispatchStart=e.target.elements.dispatchStart.value;submit.disabled=true;try{await persist(draft,draft.version);render();toast('派单设置已保存');}catch(error){toast(error.message);submit.disabled=false;}return;}if(e.target.id==='schedule-search'){e.preventDefault();query=e.target.elements.query.value.trim();render();return;}if(e.target.id!=='schedule-form')return;e.preventDefault();const ctx=dialog;if(!ctx||ctx.saving)return;const f=new FormData(e.target),submit=e.target.querySelector('[type=submit]');ctx.saving=true;submit.disabled=true;try{let draft=structuredClone(ctx.c);if(ctx.type==='shift'){const row={id:ctx.data.id||'shift-'+Date.now().toString(36),name:f.get('name'),start:f.get('start'),end:f.get('end')},i=draft.shifts.findIndex(s=>s.id===row.id);if(i<0)draft.shifts.push(row);else draft.shifts[i]=row;}else draft=M.batch(state,draft,{people:f.getAll('people'),start:f.get('start'),end:f.get('end'),weekdays:f.getAll('weekdays').map(Number),shift:f.get('shift')});await persist(draft,ctx.version);ctx.saving=false;close();render();toast(ctx.type==='batch'?'排班已保存':ctx.type==='shift'?'班次已保存':'派单设置已保存');}catch(error){$('#schedule-error').textContent=error.message;$('#schedule-error').scrollIntoView({block:'nearest'});}finally{ctx.saving=false;submit.disabled=false;}});
document.addEventListener('keydown',e=>{if(!dialog)return;if(e.key==='Escape')close();if(e.key==='Tab'){const els=[...document.querySelectorAll('.schedule-drawer input,.schedule-drawer select,.schedule-drawer button')].filter(el=>!el.disabled),first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.addEventListener('storage',e=>{if(e.key!==Store.KEY)return;if(dialog)toast('其他页面已更新数据，保存时将校验最新版本');else render();});window.addEventListener('hashchange',()=>{if(dialog)return;tab=['shifts','roster','dispatch'].includes(location.hash.slice(1))?location.hash.slice(1):'roster';render();});
try{render();}catch(error){$('#application').innerHTML=`<main class="page-body"><div class="callout error">${esc(error.message)}</div></main>`;}
})();
