/* Run in an isolated browser context; never reads the user's normal Chrome profile. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),url=p=>pathToFileURL(path.join(root,p)).href,KEY='meiye.complaint.unified.v1',out=process.env.SOLUTION_QA_DIR||'/tmp/complaint-solution-qa';
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 fs.mkdirSync(out,{recursive:true});const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
 const page=await context.newPage();page.setDefaultTimeout(10000);await page.goto(url('index.html')+'#complaint-tickets');const f=page.frameLocator('#page-complaint-tickets iframe');await f.locator('.tickets-table').waitFor();
 const read=()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY),before=await read();
 const fixture=await f.locator('body').evaluate(()=>{
  const s=ComplaintStore.load(),C=ComplaintConfiguration,P=createTicketFlowConfig(C.Rules.Flow,C.STAFF,C.Assignment),original=C.Rules.sceneList(s.configuration).find(x=>x.level===2),result={};
  for(const mode of ['payment','store','approval']){
   const scene=P.prepare(s.configuration,original),nodes=scene.config.ticketFlow.nodes;
   if(mode!=='approval')nodes.splice(1,nodes.length-2,P.node(mode,s.configuration,scene));
   s.configuration=C.Rules.saveScene(s.configuration,'manager',scene,s.configuration.sceneRevision,Date.now());
   const t=Engine.create(s,'chen',{name:'林女士',phone:'13800001002',order:'O2',store:'上海徐汇店',channel:'400电话',title:'方案确认验收 · '+mode,description:'客户申请退款'});
   Engine.follow(s,t,t.currentAssignee,{connected:true,content:'线下已核实客户与处理事项'});result[mode]=t.id;
  }ComplaintStore.save(s);return result;
 });
 await page.reload();await f.locator('.tickets-table').waitFor();
 async function open(id){await f.locator('#filter-form [name=q]').fill(id);await f.locator('#filter-form [type=submit]').click();await f.locator('[data-action=detail][data-id="'+id+'"]').click();await f.locator('.ticket-drawer').waitFor();}
 async function submit(form){const revision=await form.evaluate(()=>JSON.parse(localStorage.getItem('meiye.complaint.unified.v1'))._revision);await form.locator('[type=submit]').click();await form.waitFor({state:'detached'});await page.waitForFunction(({key,revision})=>JSON.parse(localStorage.getItem(key))._revision>revision,{key:KEY,revision});}
 await open(fixture.payment);await f.locator('[data-action=proposal]').click();const form=f.locator('[data-form=proposal]');assert.equal(await form.locator('[name=consent]').count(),0);assert.equal(await form.locator('[name=type] option').count(),7);assert.equal(await form.getByRole('button',{name:'确认方案',exact:true}).count(),1);
 for(const key of ['service','refund','compensation','combined','exchange','refund_exchange','compensation_exchange']){await form.locator('[name=type]').selectOption(key);assert.equal(await form.locator('[name=refund]').isDisabled(),!['refund','combined','refund_exchange'].includes(key));assert.equal(await form.locator('[name=compensation]').isDisabled(),!['compensation','combined','compensation_exchange'].includes(key));assert.equal(await form.locator('.exchange-editor').isVisible(),['exchange','refund_exchange','compensation_exchange'].includes(key));}
 await form.locator('[name=type]').selectOption('refund_exchange');await form.locator('[name=exchangeName]').fill('修护霜 50g');await form.locator('[name=exchangePrice]').fill('180');await form.locator('[name=exchangeQuantity]').fill('2');await form.locator('[name=refund]').fill('123.45');await form.locator('[name=content]').fill('退还未使用疗程费用，并置换修护霜。');await page.screenshot({path:out+'/pc-refund-exchange.png'});
 await form.locator('[name=type]').selectOption('refund');await form.locator('[name=refund]').fill('0');await form.locator('[type=submit]').click();await form.locator('.error-inline').waitFor();assert((await form.locator('.error-slot').innerText()).includes('大于 0 的退款金额'));assert.equal((await read()).tickets.find(t=>t.id===fixture.payment).phase,'处理中');await page.screenshot({path:out+'/pc-zero-refund.png'});
 await form.locator('[name=refund]').fill('123.45');await submit(form);await f.locator('[data-action=pay]').waitFor();let t=(await read()).tickets.find(t=>t.id===fixture.payment);assert.equal(t.phase,'待付款');assert.equal(t.state,'付款办理');assert.equal(t.approval,null);assert.equal(t.proposal.exchangeItems.length,0);assert.equal(t.owner,'aftercare');
 await f.locator('[data-action=detailTab][data-id=fund]').click();assert((await f.locator('.pc-ticket-content').innerText()).includes('处理流程'));await page.screenshot({path:out+'/pc-no-approval-payment.png'});await f.locator('[data-action=pay]').click();const payment=f.locator('[data-form=pay]');await payment.locator('[name=reference]').fill('UI-PAY-'+fixture.payment);await payment.locator('[name=proof]').setInputFiles({name:'付款凭证.txt',mimeType:'text/plain',buffer:Buffer.from('已付款123.45元')});await submit(payment);await f.locator('[data-action=closeTicket]').waitFor();assert((await f.locator('.pc-ticket-badges').innerText()).includes('待结案'));assert.equal((await read()).tickets.find(t=>t.id===fixture.payment).phase,'待结案');await f.locator('[data-action=closeTicket]').click();const close=f.locator('[data-form=closeTicket]');await close.locator('[name=note]').fill('已线下确认退款到账，所有事项处理完成');await close.locator('[name=completed]').check();await submit(close);assert.equal((await read()).tickets.find(t=>t.id===fixture.payment).phase,'已结案');await f.getByRole('button',{name:'关闭详情',exact:true}).click();
 const mobile=await context.newPage();mobile.setDefaultTimeout(10000);await mobile.setViewportSize({width:390,height:844});await mobile.goto(url('complaint-prototype/workflow/index.html')+'?view=h5#/mobile/'+fixture.store);await mobile.locator('[data-action=proposal]').click();const mf=mobile.locator('[data-form=proposal]');await mf.locator('[name=type]').selectOption('exchange');await mf.locator('[name=exchangeName]').fill('修护霜 50g');await mf.locator('[name=exchangeQuantity]').fill('2');await mf.locator('[name=exchangePrice]').fill('180');await mf.locator('[data-action=addExchange]').click();assert.equal(await mf.locator('.exchange-row').count(),2);await mf.locator('[name=exchangeName]').nth(1).fill('保湿面膜');await mf.locator('[name=exchangePrice]').nth(1).fill('19.90');await mf.locator('[name=content]').fill('已线下确认置换商品，由门店交付客户。');assert((await mf.locator('[data-exchange-total]').innerText()).includes('379.90'));await mobile.screenshot({path:out+'/h5-exchange.png',fullPage:true});assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await submit(mf);await mobile.locator('[data-action=finishStore]').waitFor();t=(await read()).tickets.find(t=>t.id===fixture.store);assert.equal(t.currentAssignee,'store2');assert.equal(t.state,'处理中');assert.equal(t.proposal.exchangeValue,37990);assert.equal(t.owner,'aftercare');
 await mobile.reload();await mobile.locator('[data-action=finishStore]').click();const sf=mobile.locator('[data-form=finishStore]');await sf.locator('[name=note]').fill('已核实并完成两款商品的交付，客户签收');await mobile.screenshot({path:out+'/h5-store-result.png'});await submit(sf);await mobile.locator('[data-action=closeTicket]').waitFor();assert.equal(await mobile.locator('.mobile-overview .mobile-state').innerText(),'待结案');await mobile.locator('[data-action=closeTicket]').click();const cf=mobile.locator('[data-form=closeTicket]');await cf.locator('[name=note]').fill('已与门店确认商品交付，处理结束');await cf.locator('[name=completed]').check();await mobile.screenshot({path:out+'/h5-close.png'});await submit(cf);assert.equal((await read()).tickets.find(t=>t.id===fixture.store).phase,'已结案');
 await page.reload();await f.locator('.tickets-table').waitFor();await open(fixture.approval);await f.locator('[data-action=proposal]').click();await form.locator('[name=refund]').fill('20');await form.locator('[name=content]').fill('协商退款20元');await submit(form);await f.locator('[data-action=reject]').waitFor();assert.equal((await read()).tickets.find(t=>t.id===fixture.approval).phase,'待部门审批');await page.screenshot({path:out+'/pc-department-approval.png'});await f.locator('[data-action=reject]').click();const reject=f.locator('[data-form=reject]');await reject.locator('[name=note]').fill('请补充办理依据');await submit(reject);assert((await f.locator('.pc-ticket-badges').innerText()).includes('处理中'));await f.locator('[data-action=proposal]').click();assert.equal(await form.locator('[name=refund]').inputValue(),'20');await form.locator('[name=type]').selectOption('service');await form.locator('[name=content]').fill('补充核实后，已通过服务协调完成处理');await submit(form);await f.locator('[data-action=closeTicket]').waitFor();t=(await read()).tickets.find(t=>t.id===fixture.approval);assert.equal(t.proposal.version,2);assert.equal(t.proposal.refund,0);assert.equal(t.approvalHistory[0].status,'已驳回');
 await page.reload();await f.locator('.tickets-table').waitFor();const end=await read();assert.deepEqual(end.tickets.filter(t=>before.tickets.some(old=>old.id===t.id)),before.tickets);assert.equal(end.tickets.find(t=>t.id===fixture.store).proposal.exchangeItems.length,2);assert.equal(end.tickets.find(t=>t.id===fixture.payment).phase,'已结案');
 const rules=await context.newPage();await rules.goto(url('complaint-prototype/index.html')+'?page=rules#rules');await rules.locator('.scene-table').waitFor();const schedule=await context.newPage();await schedule.goto(url('complaint-prototype/schedule.html'));await schedule.getByText('班次设置',{exact:true}).waitFor();assert.deepEqual(errors,[]);
 console.log('PASS PC/H5: seven solution types, conditional fields, positive amount validation, product rows/totals, no-approval payment and closure, store handling and closure, department rejection/resubmission, snapshots after config changes, reload persistence, old tickets retained, rule/schedule entry loading, no browser errors or mobile overflow.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
