const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),url=p=>pathToFileURL(path.join(root,p)).href,out='/tmp/complaint-editable-branches-qa';
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 fs.mkdirSync(out,{recursive:true});const context=await browser.newContext({viewport:{width:1440,height:1050},timezoneId:'Asia/Shanghai'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());page.setDefaultTimeout(10000);
 await page.goto(url('complaint-prototype/index.html')+'?page=rules#rules');await page.locator('.scene-table').waitFor();const before=await page.evaluate(()=>ComplaintStore.load());const ruleId=before.configuration.ruleScenes.find(r=>r.level===2).id;
 const open=async id=>{await page.locator('[data-scene-action=edit][data-id="'+id+'"]').click();await page.locator('.ac-grading-node').waitFor();};await open(ruleId);
 const canvas=page.locator('.ac-flow-canvas'),form=page.locator('#flow-drawer-form'),source=()=>page.locator('.ac-branch-title[data-flow-action=condition]').filter({hasText:'工单来源'}).first(),result=()=>page.locator('.ac-branch-title[data-flow-action=condition]').filter({hasText:'门店处理结果'}).first();
 const saveDrawer=async()=>{await page.locator('[data-flow-save]').click();await page.locator('.flow-drawer').waitFor({state:'detached'});},close=()=>page.locator('[data-flow-close]').first().click();
 assert.equal(await page.locator('.source-routing').count(),0);assert((await page.locator('.ac-grading-node').innerText()).includes('二级'));assert.equal(await canvas.getByText('售后专员办理',{exact:true}).count(),1);assert.equal(await canvas.getByText('售后经理办理',{exact:true}).count(),0);
 for(let i=0;i<3;i++)await page.locator('[data-flow-action=zoom-out]').click();await page.screenshot({path:out+'/editable-source-flow.png'});
 // Edits use normal condition controls, and enum changes affect the path immediately.
 await source().click();assert.deepEqual(await form.locator('[name=judgeBy]').evaluateAll(es=>es.map(e=>e.value)),['source','storeResult','plan']);assert.equal(await form.locator('[name=conditionValue]').count(),3);await page.screenshot({path:out+'/source-condition.png'});await form.locator('[name=conditionValue][value=hotline]').uncheck();await form.locator('[name=title]').fill('微信渠道先门店');await saveDrawer();
 assert.equal(await page.getByRole('button',{name:'查看流转路径'}).count(),0);
 await page.locator('[type=submit][form=rules-form]').click();await page.locator('.scene-table').waitFor();await page.reload();await open(ruleId);await source().click();assert.equal(await form.locator('[name=conditionValue][value=hotline]').isChecked(),false);await form.locator('[name=conditionValue][value=hotline]').check();await form.locator('[name=title]').fill('非 CRM 来源');await saveDrawer();
 await result().click();assert.equal(await form.locator('[name=judgeBy]:checked').inputValue(),'storeResult');await page.screenshot({path:out+'/store-result-condition.png'});await form.locator('[name=conditionValue][value=resolved]').uncheck();await form.locator('[name=conditionValue][value=unresolved]').check();await saveDrawer();await result().click();await form.locator('[name=conditionValue][value=unresolved]').uncheck();await form.locator('[name=conditionValue][value=resolved]').check();await saveDrawer();
 // Copy, rename and delete a condition, using the existing branch editor.
 const card=source().locator('..');await card.hover();await card.locator('[data-flow-action=condition-copy]').click();await form.locator('[name=title]').fill('来源条件副本');await saveDrawer();const duplicate=page.locator('.ac-condition-card').filter({hasText:'来源条件副本'});assert.equal(await duplicate.count(),1);await duplicate.hover();await duplicate.locator('[data-flow-action=condition-delete]').click();assert.equal(await duplicate.count(),0);
 // Add a real nested branch and then delete it again; the common tree has no fixed intake overlay.
 const store=()=>page.locator('.ac-node-handling').filter({hasText:'门店首次办理'});await store().locator('xpath=preceding-sibling::*[1]').locator('[data-flow-action=add]').click();await page.locator('.flow-add-menu [data-kind=branch]').click();await form.locator('[name=judgeBy][value=source]').check();await form.locator('[name=title]').fill('新增来源条件');await form.locator('[name=conditionValue][value=wechat]').check();await saveDrawer();const added=page.locator('.ac-condition-card').filter({hasText:'新增来源条件'});assert.equal(await added.count(),1);await added.hover();await added.locator('[data-flow-action=condition-delete]').click();assert.equal(await added.count(),0);
 await store().locator('.ac-node-body').click();await form.locator('[name=hours]').fill('8');assert.equal(await form.locator('[name=firstHours]').count(),0);assert.deepEqual(await form.locator('[name=source] option').allTextContents(),['工单所属门店负责人','客户的接待老师']);await saveDrawer();
 await canvas.locator('.ac-node-handling').filter({hasText:'售后专员办理'}).locator('.ac-node-body').click();assert.equal(await form.locator('[name="actions.store"]').count(),0);await form.locator('[name=source]').selectOption('person');assert(!(await form.locator('[name=personId] option').allTextContents()).some(s=>s.includes('售后主管')));await form.locator('[name=personId]').selectOption('chen');await saveDrawer();
 // Normal new handling nodes still allow all handling kinds.
 await canvas.locator('.ac-node-handling').filter({hasText:'售后专员办理'}).locator('xpath=following-sibling::*[1]').locator('[data-flow-action=add]').click();await page.locator('.flow-add-menu [data-kind=handling]').click();assert.deepEqual(await form.locator('[name=kind] option').evaluateAll(es=>es.map(e=>e.value)),['store','sales','manager','payment','store_close','close','procurement']);for(const kind of ['store','sales','manager','payment','store_close','close','procurement']){await form.locator('[name=kind]').selectOption(kind);assert.equal(await form.locator('[name=kind]').inputValue(),kind);assert((await form.locator('[name=title]').inputValue()).length>0);if(kind==='store_close'){assert.equal(await form.locator('[name=hours]').count(),0);assert((await form.innerText()).includes('工单直接结束'));}else assert.equal(await form.locator('[name=hours]').count(),1);}await page.screenshot({path:out+'/complete-handling-types.png'});await close();
 // A continuing branch has one insertion point, even when several nested groups end.
 assert.equal(await canvas.locator('.ac-branch-title').filter({hasText:'门店处理结果为「未解决」'}).locator('..').locator('..').locator(':scope > .ac-connector > .ac-add:not([hidden])').count(),1);
 await canvas.locator('.ac-node-end .ac-node-body').click();assert.equal(await form.locator('[name=kind]').inputValue(),'store_close');await saveDrawer();
 // A completed branch skips editable task connectors and joins the shared finish.
 const terminal=canvas.locator('.ac-node-end');assert.equal(await canvas.locator('.ac-completion-lines [data-terminal-node]').count(),await terminal.count());assert.equal(await terminal.locator('xpath=following-sibling::*[1][contains(@class,"ac-connector")]').count(),0);assert.equal(await terminal.locator('..').getAttribute('class').then(s=>s.includes('ac-branch-terminal')),true);const joins=await page.locator('.ac-join-lines').evaluateAll(es=>es.map(el=>el.querySelectorAll('path').length));assert(joins.includes(0));assert(joins.includes(2));
 await page.locator('[type=submit][form=rules-form]').click();await page.locator('.scene-table').waitFor();const after=await page.evaluate(()=>ComplaintStore.load()),changed=after.configuration.ruleScenes.find(r=>r.id===ruleId);assert.equal(changed.config.ticketFlow.schema,2);assert(!changed.config.ticketFlow.entryRouting);assert.deepEqual(after.tickets,before.tickets);assert.deepEqual(after.orders,before.orders);
 await open(ruleId);assert.equal(await page.getByRole('button',{name:'查看流转路径'}).count(),0);await page.locator('[data-scene-action=back]').click();
 // Rules 1-4 show their own grade and one specialist; a new level-5 rule shows only manager.
 for(const rule of before.configuration.ruleScenes){await open(rule.id);assert((await page.locator('.ac-grading-node').innerText()).includes(['','一级','二级','三级','四级','五级'][rule.level]));assert.equal(await canvas.getByText('售后专员办理',{exact:true}).count(),rule.level===5?0:1);assert.equal(await canvas.getByText('售后经理办理',{exact:true}).count(),rule.level===5?1:0);await page.locator('[data-scene-action=back]').click();}
 const fifth=await page.evaluate(()=>ComplaintStore.load().configuration.ruleScenes.find(r=>r.level===5));await open(fifth.id);assert.equal(await canvas.getByText('售后经理办理',{exact:true}).count(),1);assert.equal(await canvas.getByText('售后专员办理',{exact:true}).count(),0);await page.locator('.ac-flow').evaluate(el=>el.scrollTop=480);await page.screenshot({path:out+'/level-five-manager.png'});await canvas.locator('.ac-node-handling').filter({hasText:'售后经理办理'}).locator('.ac-node-body').click();assert(!(await form.locator('[name=personId] option').allTextContents()).some(s=>s.includes('售后专员')));await close();await page.locator('[type=submit][form=rules-form]').click();await page.locator('.scene-table').waitFor();
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('PASS editable branches: restored rule-grade node; 1-4 specialist / 5 manager; real source/result conditions; edit/copy/add/delete; removed path-preview button; persistence; terminal connectors; node settings; unchanged tickets and orders; no browser errors.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
