/* Isolated PC/H5 acceptance for ticket-level suspension, recovery and history. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),url=p=>pathToFileURL(path.join(root,p)).href,KEY='meiye.complaint.unified.v1',out='/tmp/complaint-suspension-qa';
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 fs.mkdirSync(out,{recursive:true});const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Shanghai',reducedMotion:'reduce'}),errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
 const page=await context.newPage();page.setDefaultTimeout(10000);await page.goto(url('index.html')+'#complaint-tickets');const f=page.frameLocator('#page-complaint-tickets iframe');await f.locator('.tickets-table').waitFor();assert.equal(await f.getByRole('button',{name:'挂起管理',exact:true}).count(),0);
 const state=()=>f.locator('body').evaluate(()=>ComplaintStore.load());const original=await state();
 const id='KS20261007-P01';async function open(){await f.locator('#filter-form [name=q]').fill(id);await f.locator('#filter-form [type=submit]').click();await f.locator('[data-action=detail][data-id="'+id+'"]').click();await f.locator('.ticket-drawer').waitFor();}
 const localTime=async(surface,ms)=>surface.locator('body').evaluate((_,ms)=>{const d=new Date(ms);return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);},ms);
 async function more(surface,action){await surface.locator('.ticket-more-menu summary').click();await surface.locator('[data-action='+action+']').click();return surface.locator('[data-form='+action+']');}
 async function submit(form){await form.locator('[type=submit]').click();await form.waitFor({state:'detached'});}
 await open();let form=await more(f,'suspendTicket');assert.equal(await form.locator('[name=expectedAt]').getAttribute('required'),'');assert.equal(await form.locator('[name=reasonType] option').count(),4);await form.locator('[name=reasonType]').selectOption('materials');await form.locator('[name=note]').fill('客户明天提供支付凭证，当前缺少必要核实材料。');await form.locator('[name=expectedAt]').fill(await localTime(f,Date.now()+2*3600000));await form.locator('[type=submit]').click();await form.locator('.error-inline').waitFor();assert((await form.innerText()).includes('沟通记录'));await form.locator('[name=evidenceId]').selectOption({index:1});await page.screenshot({path:out+'/pc-suspend-form.png'});await submit(form);await f.locator('[data-action=resumeTicket]').waitFor();assert.equal(await f.locator('[data-action=extendSuspension]').count(),0);let t=(await state()).tickets.find(t=>t.id===id);assert.equal(t.state,'已挂起');assert.equal(t.suspension.reasonType,'materials');
 form=await more(f,'resumeTicket');await form.locator('[name=note]').fill('客户已补齐必要材料，继续办理。');await submit(form);t=(await state()).tickets.find(t=>t.id===id);assert.equal(t.state,'处理中');assert.equal(t.suspensionHistory.length,1);await f.locator('.pc-detail-nav').getByRole('button',{name:'办理时效',exact:true}).click();assert((await f.locator('.suspension-metrics').innerText()).includes('已恢复'));await page.screenshot({path:out+'/pc-resumed-clock.png'});
 const mobile=await context.newPage();mobile.setDefaultTimeout(10000);await mobile.setViewportSize({width:390,height:844});await mobile.goto(url('complaint-prototype/workflow/index.html')+'?view=h5#/mobile/'+id);form=await more(mobile,'suspendTicket');assert((await form.innerText()).includes('额度已用完'));await form.locator('[name=reasonType]').selectOption('materials');await form.locator('[name=note]').fill('再次等待资料');await form.locator('[name=expectedAt]').fill(await localTime(mobile,Date.now()+3600000));await form.locator('[name=evidenceId]').selectOption({index:1});await form.locator('[type=submit]').click();await form.locator('.error-inline').waitFor();assert((await form.innerText()).includes('自主挂起次数'));await mobile.screenshot({path:out+'/h5-quota.png'});
 // Set up a supervisor-authorized pause in the fixture; there is no separate management page.
 await mobile.goto(url('complaint-prototype/workflow/index.html')+'?view=h5#/mobile');assert.equal(await mobile.getByRole('button',{name:'挂起管理',exact:true}).count(),0);await mobile.evaluate(id=>{const s=ComplaintStore.load(),t=s.tickets.find(t=>t.id===id);Engine.suspendTicket(s,t,'manager',{reasonType:'materials',note:'等待必要外部材料',expectedAt:Date.now()+Engine.H,evidenceId:Engine.suspensionEvidence(t)[0].id,basis:'已核实确需等待'});ComplaintStore.save(s);},id);await mobile.goto(url('complaint-prototype/workflow/index.html')+'?view=h5#/mobile/'+id);await mobile.locator('.mobile-overview .mobile-state').getByText('已挂起',{exact:true}).waitFor();
 // A scheduled expiry is processed even if the page does not remain open; no next-node advance.
 const expected=await mobile.evaluate(id=>{const s=ComplaintStore.load(),t=s.tickets.find(t=>t.id===id),r=t.suspension;r.at=Date.now()-2*Engine.H;r.expectedAt=Date.now()-Engine.H;t.nodeTiming.startedAt=r.at-Engine.H;ComplaintStore.save(s);return {deadline:r.taskDeadline+Engine.H,total:t.deadline};},id);await mobile.reload();await mobile.locator('.mobile-overview .mobile-state').getByText('处理中',{exact:true}).waitFor();let loaded=await mobile.evaluate(id=>ComplaintStore.load().tickets.find(t=>t.id===id),id);assert.equal(loaded.taskDeadline,expected.deadline);assert.equal(loaded.deadline,expected.total);assert.equal(loaded.suspensionHistory.at(-1).auto,true);assert.equal(loaded.execution,undefined);await mobile.getByRole('tab',{name:'办理时效',exact:true}).click();assert((await mobile.locator('.suspension-metrics').innerText()).includes('有效办理耗时'));await mobile.screenshot({path:out+'/h5-auto-resume.png',fullPage:true});assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await mobile.goto(url('complaint-prototype/workflow/index.html')+'?view=h5#/mobile');await mobile.locator('[data-action=mobileFilter]').click();form=mobile.locator('[data-form=mobileFilters]');assert.equal(await form.locator('[name=suspensionReason],[name=suspensionRisk]').count(),0);await form.locator('[name=state]').selectOption('处理中');await submit(form);await mobile.locator('[data-form=mobileSearch] [name=q]').fill(id);await mobile.locator('[data-form=mobileSearch] [type=submit]').click();await mobile.locator('.mobile-ticket').first().waitFor();assert((await mobile.locator('.mobile-ticket-list').innerText()).includes(id));
 const end=await state();assert.deepEqual(end.configuration,original.configuration);assert.deepEqual(end.tickets.filter(t=>t.id!==id),original.tickets.filter(t=>t.id!==id));assert.deepEqual(errors,[]);console.log('PASS suspension PC/H5: required reasons/time/evidence, staff quota, ticket-level resume without a management page, exact scheduled recovery after reload, clocks and history, filters, preserved unrelated tickets/configuration, no errors or horizontal overflow.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
