'use strict';
const {test,afterEach}=require('node:test'),assert=require('node:assert/strict');
const E=require('./workflow/engine.js'),C=require('./configuration.js'),Store=require('./shared-store.js');
const realNow=Date.now;let now;afterEach(()=>{Date.now=realNow;});
function setup(){now=Date.parse('2026-10-07T02:00:00Z');Date.now=()=>now;const s=C.initialize(E.seed());E.prepareTickets(s);const t=E.create(s,'chen',{name:'林女士',phone:'13800001002',order:'O2',store:'上海徐汇店',channel:'门店H5 / A3',title:'退款协商',description:'申请退款'});E.follow(s,t,t.owner,{connected:true,content:'已核实客户资料'});return {s,t};}
const data=t=>({reasonType:'materials',note:'等待客户补充必要凭证',expectedAt:now+4*E.H,evidenceId:E.suspensionEvidence(t)[0].id,basis:'已核实等待事项及必要时长'});
const memory=()=>{const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)};};
test('reason category, future deadline and linked evidence are enforced atomically',()=>{const {s,t}=setup(),before=E.clone(s);for(const d of [{...data(t),reasonType:'internal_payment'},{...data(t),reasonType:'__proto__'},{...data(t),expectedAt:null},{...data(t),expectedAt:now},{...data(t),evidenceId:'missing'},{...data(t),evidenceId:'',files:[]}])assert.throws(()=>E.suspendTicket(s,t,t.owner,d));assert.deepEqual(E.clone(s),before);E.suspendTicket(s,t,t.owner,{...data(t),evidenceId:'',files:[{name:'客户沟通凭证'}]});assert.equal(t.suspension.files[0].name,'客户沟通凭证');});
test('staff is limited to one pause per ticket and 24 cumulative hours',()=>{const {s,t}=setup();assert.throws(()=>E.suspendTicket(s,t,t.owner,{...data(t),expectedAt:now+24*E.H+1}),/24/);E.suspendTicket(s,t,t.owner,data(t));now+=E.H;E.resumeTicket(s,t,t.owner,'已补齐');E.transferAftercare(s,t,t.owner,'chen','交接');assert.throws(()=>E.suspendTicket(s,t,'chen',data(t)),/次数/);assert.equal(E.suspensionUsage(t).duration,E.H);assert.throws(()=>E.suspendTicket(s,t,'manager',{...data(t),basis:''}),/主管处理依据/);E.suspendTicket(s,t,'manager',{...data(t),expectedAt:now+48*E.H});assert.equal(t.suspension.supervisor,true);assert.equal(E.suspensionUsage(t).count,2);});
test('only an active same-department supervisor can extend or correct a pause',()=>{const {s,t}=setup();E.suspendTicket(s,t,t.owner,data(t));const until=t.suspension.expectedAt;for(const a of [t.owner,'finance','gu']){assert.throws(()=>E.extendSuspension(s,t,a,{expectedAt:until+E.H,basis:'延长'}),/主管/);assert.throws(()=>E.invalidateSuspension(s,t,a,'纠正'),/主管/);}E.extendSuspension(s,t,'manager',{expectedAt:until+E.H,basis:'客户已约定次日提供'});assert.equal(t.suspension.extensions.length,1);assert.equal(t.suspension.extensions[0].from,until);assert.equal(t.suspension.expectedAt,until+E.H);s.configuration.organization.appointments.find(p=>p.personId==='manager').active=false;assert.throws(()=>E.extendSuspension(s,t,'manager',{expectedAt:until+2*E.H,basis:'延长'}),/主管/);});
test('delayed automatic recovery excludes only the scheduled pause, even after the page was closed',()=>{const {s,t}=setup(),whole=t.deadline,due=t.taskDeadline;now+=E.H;E.suspendTicket(s,t,t.owner,{...data(t),expectedAt:now+2*E.H});const end=t.suspension.expectedAt;now+=5*E.H;assert(E.prepareTickets(s));assert.equal(t.state,'处理中');assert.equal(t.taskDeadline,due+2*E.H);assert.equal(t.deadline,whole);assert.equal(t.suspensionHistory[0].resumedAt,end);assert.equal(t.suspensionHistory[0].processedAt,now);assert.equal(t.suspensionHistory[0].auto,true);assert.equal(E.nodeTiming(t).total,6*E.H);assert.equal(E.nodeTiming(t).net,4*E.H);assert(E.ruleTasks(s,t).some(r=>r.title.includes('挂起已到期')&&r.people.includes('manager')));const before=E.clone(t);assert.equal(E.prepareTickets(s),false);assert.deepEqual(t,before);});
test('extension delays recovery, while manual recovery credits only actual elapsed pause',()=>{const {s,t}=setup(),due=t.taskDeadline;E.suspendTicket(s,t,t.owner,{...data(t),expectedAt:now+E.H});E.extendSuspension(s,t,'manager',{expectedAt:now+4*E.H,basis:'确认等待必要资料'});now+=2*E.H;assert.equal(E.prepareTickets(s),false);E.resumeTicket(s,t,t.owner,'提前补齐');assert.equal(t.taskDeadline,due+2*E.H);assert.equal(E.suspensionUsage(t).duration,2*E.H);});
test('invalid suspension time is counted as effective work time and overdue evidence is retained',()=>{const {s,t}=setup();t.taskDeadline=now-30*60000;const due=t.taskDeadline,whole=t.deadline;E.suspendTicket(s,t,t.owner,data(t));assert(E.ruleTasks(s,t).some(r=>r.title==='挂起前节点已超时'));now+=2*E.H;E.invalidateSuspension(s,t,'manager','等待内部财务应流转付款节点');assert.equal(t.taskDeadline,due);assert.equal(t.deadline,whole);assert.equal(t.suspensionHistory[0].excludedDuration,0);assert.equal(E.nodeTiming(t).pause,0);assert.equal(E.nodeTiming(t).net,2*E.H);assert(E.nodeTiming(t).overdue);assert.equal(E.suspensionUsage(t).invalid,1);});
test('approval return and transfer cannot reset the ticket suspension quota',()=>{const {s,t}=setup();E.suspendTicket(s,t,t.owner,data(t));now+=E.H;E.resumeTicket(s,t,t.owner,'已收到');E.confirmSolution(s,t,t.owner,{typeKey:'refund',refund:10000,compensation:0,account:'原渠道',content:'线下协商退款'});E.approve(s,t,E.taskPeople(s,t)[0],false,'补充依据');assert.equal(t.state,'处理中');assert.throws(()=>E.suspendTicket(s,t,t.owner,data(t)),/次数/);assert.equal(E.nodeTiming(t).pause,0);assert(t.nodeTimingHistory.some(r=>r.title==='售后办理'));const finished=E.nodeTimingHistory(t).find(r=>r.title==='售后办理');assert.equal(finished.pause,E.H);assert.equal(finished.net,0);});
test('legacy indefinite pauses get a bounded deadline without fabricating category or evidence',()=>{const {s,t}=setup();const original={id:'old-pause',at:now-48*E.H,by:t.owner,reason:'历史等待',expectedAt:null,returnState:t.phase,nodeId:t.activeNode,taskDeadline:t.taskDeadline};t.suspension=E.clone(original);t.phase='已挂起';t.taskDeadline=null;E.prepareTickets(s);const r=t.suspensionHistory[0];assert.deepEqual(r.legacy,original);assert.equal(r.reasonType,'legacy');assert.equal(r.evidence,undefined);assert.equal(r.duration,24*E.H);assert.equal(t.taskDeadline,original.taskDeadline+24*E.H);assert.equal(t.state,'处理中');});
test('shared storage performs expiration once and rejects a stale open suspension form',()=>{setup();const mem=memory(),store=Store.createStore(mem,E,C),s=store.load(),t=s.tickets.find(t=>t.id==='KS20261007-P01');E.suspendTicket(s,t,t.owner,{...data(t),expectedAt:now+E.H});store.save(s);const stale=store.load();now+=2*E.H;const current=store.load(),x=current.tickets.find(x=>x.id===t.id);assert(!x.suspension);assert.equal(current._revision,s._revision+1);assert.throws(()=>store.save(stale),/其他页面/);assert.deepEqual(store.load(),current);});
test('staff statistics attribute supervisor actions to the responsible employee and preserve transfer history',()=>{const {s,t}=setup();E.suspendTicket(s,t,t.owner,data(t));now+=E.H;E.resumeTicket(s,t,'manager','已补齐');E.transferAftercare(s,t,t.owner,'chen','交接');E.suspendTicket(s,t,'manager',data(t));now+=E.H;E.invalidateSuspension(s,t,'manager','内部事项不应挂起');const rows=E.suspensionStatistics(s,'manager'),first=rows.find(r=>r.id==='aftercare'),second=rows.find(r=>r.id==='chen');assert.equal(first.count,1);assert.equal(first.duration,E.H);assert.equal(second.count,1);assert.equal(second.invalid,1);assert(second.rate>0);assert.throws(()=>E.suspensionStatistics(s,'chen'),/主管/);});
test('an inactive owner does not keep an expired ticket suspended indefinitely',()=>{const {s,t}=setup();E.suspendTicket(s,t,t.owner,{...data(t),expectedAt:now+E.H});s.configuration.organization.appointments.find(p=>p.personId===t.owner).active=false;now+=2*E.H;E.prepareTickets(s);assert.equal(t.state,'处理中');assert(E.taskPeople(s,t).some(a=>E.suspensionManager(s,t,a)));});
