/* Shared PC/H5 suspension forms use the existing fields, cards and drawers. */
function elapsedLabel(ms){const minutes=Math.max(0,Math.floor(ms/60000));return minutes>=60?Math.floor(minutes/60)+'小时'+minutes%60+'分':minutes+'分钟';}
function suspensionFilters(f){return select('suspensionReason',Object.entries(E.SUSPENSION_REASONS).concat([['legacy','历史挂起']]),f.suspensionReason,'全部挂起原因')+select('suspensionRisk',[['active','正在挂起'],['repeated','多次挂起'],['near','临近超时挂起'],['invalid','原因不成立'],['long','累计超过24小时']],f.suspensionRisk,'全部挂起情况');}
function suspensionMatches(t,f){const rows=E.suspensionRecords(t),u=E.suspensionUsage(t);return (!f.suspensionReason||rows.some(r=>r.reasonType===f.suspensionReason))&&(!f.suspensionRisk||({active:!!t.suspension,repeated:u.count>1,near:u.near>0,invalid:u.invalid>0,long:u.duration>24*E.H})[f.suspensionRisk]);}
function suspensionListNote(t){const r=t.suspension;return r?`<span class="sub suspension-list-note">${esc(E.SUSPENSION_REASONS[r.reasonType]||'历史挂起')} · 已挂起 ${elapsedLabel(Math.min(Date.now(),r.expectedAt)-r.at)}<br>恢复 ${date(r.expectedAt)}${r.overdueAtStart?'<br><span class="red-text">挂起前节点已超时</span>':''}</span>`:'';}
function suspensionContext(t){const r=t.suspension,u=E.suspensionUsage(t);return `<section class="card aftercare-context"><div class="section-title"><h3>工单已挂起</h3><span class="pill amber">${esc(E.SUSPENSION_REASONS[r.reasonType]||'历史挂起')}</span></div><p class="text">${esc(r.reason)}</p>${dataRows([['挂起人',esc(name(r.by))],['挂起时间',date(r.at)],['自动恢复时间',date(r.expectedAt)],['本单累计',u.count+' 次 · '+elapsedLabel(u.duration)],...(r.basis?[['主管依据',esc(r.basis)]]:[]),...(r.evidence?[['关联记录',esc(r.evidence.title)+' · '+date(r.evidence.at)+'<div class="text">'+esc(r.evidence.body)+'</div>']]:[])])}${filesView(r.files||[])}${r.overdueAtStart?'<p class="red-text">挂起前节点已超时，超时记录保留。</p>':''}<p class="sub aftercare-clock-note">节点计时已暂停，整单继续计时；到期自动恢复原节点，不推进流程。</p></section>`;}
function suspensionMetrics(t,{expanded=false,title='办理时效与挂起记录'}={}){const clock=E.nodeTiming(t),u=E.suspensionUsage(t),rows=E.suspensionRecords(t);if(!clock&&!rows.length)return '';return `<details class="card suspension-metrics" ${expanded?'open':''}><summary>${esc(title)}${u.count?' · '+u.count+' 次':''}</summary>${clock?dataRows([['当前节点',esc(clock.title)],['节点总耗时',elapsedLabel(clock.total)],['有效办理耗时',elapsedLabel(clock.net)],['本节点暂停时长',elapsedLabel(clock.pause)],['超时情况',clock.overdue?'<span class="red-text">节点已超时，记录保留</span>':'未超时']]):''}${dataRows([['整单累计挂起',u.count+' 次 · '+elapsedLabel(u.duration)],['自主挂起额度','每单 1 次，累计不超过 24 小时']])}${E.nodeTimingHistory(t).length?'<details class="node-time-history"><summary>已完成节点耗时</summary>'+E.nodeTimingHistory(t).map(n=>'<div class="aftercare-history-row"><b>'+esc(n.title)+'</b><p class="sub">总耗时 '+elapsedLabel(n.total)+' · 有效办理 '+elapsedLabel(n.net)+' · 暂停 '+elapsedLabel(n.pause)+(n.overdue?' · 已超时':'')+'</p></div>').join('')+'</details>':''}${[...rows].reverse().map(r=>`<div class="aftercare-history-row"><div class="section-title"><b>${esc(E.SUSPENSION_REASONS[r.reasonType]||'历史挂起')}</b><span class="sub">${r.invalidated?'原因不成立':r.resumedAt?r.auto?'到期自动恢复':'已恢复':'挂起中'}</span></div><p class="sub">${esc(name(r.by))} · ${date(r.at)} → ${date(r.resumedAt||r.expectedAt)}</p><p class="text">${esc(r.reason)}</p>${r.basis?'<p class="text">主管依据：'+esc(r.basis)+'</p>':''}${r.evidence?'<p class="sub">关联记录：'+esc(r.evidence.title)+' · '+date(r.evidence.at)+'</p>':''}${filesView(r.files||[])}${(r.extensions||[]).map(x=>'<p class="text">'+esc(name(x.by))+'延长至 '+date(x.to)+'：'+esc(x.basis)+'</p>').join('')}${r.resumeNote?'<p class="text">'+esc(r.resumeNote)+'</p>':''}${r.invalidated?'<p class="red-text">本次挂起时间计入有效办理耗时。</p>':''}${r.nearDeadline?'<p class="sub">临近或已超过节点时限时挂起，供主管复核。</p>':''}</div>`).join('')}</details>`;}
function controlledSuspensionForm(act,t){
 if(!['suspendTicket','resumeTicket','extendSuspension','invalidateSuspension'].includes(act))return false;
 const p=E.aftercarePermissions(S,t,S.actor),key=({suspendTicket:'suspend',resumeTicket:'resume',extendSuspension:'extend',invalidateSuspension:'invalidate'})[act];if(!p[key])throw Error('当前人员没有此项操作权限');
 const supervisor=E.suspensionManager(S,t,S.actor),u=E.suspensionUsage(t),r=t.suspension;let body,title,submit;
 if(act==='suspendTicket'){
  title='挂起工单';submit='确认挂起';const blocked=!supervisor&&(u.count>=1||u.duration>=24*E.H);
  body=`<div class="banner">仅用于等待客户或外部必要材料。内部审批、门店处理、付款应流转到对应节点。到期自动恢复计时，整单继续计时。</div><div class="gap"></div>${dataRows([['本单已挂起',u.count+' 次 · '+elapsedLabel(u.duration)],['自主额度','每单 1 次，累计最多 24 小时']])}${blocked?'<p class="red-text">本单自主挂起额度已用完，请由售后主管操作。</p>':''}<div class="gap"></div><div class="form-grid">${field('原因类型 *',select('reasonType',Object.entries(E.SUSPENSION_REASONS),'','请选择原因'),true)}${field('具体说明 *',txt('note'),true)}${field('预计恢复时间 *',inp('expectedAt','','datetime-local',true),true)}${field('关联沟通记录',select('evidenceId',E.suspensionEvidence(t).map(r=>[r.id,date(r.at)+' · '+r.title]),'','请选择相关记录'),true)}${field('挂起依据附件','<input type="file" name="files" multiple>',true)}${supervisor?field('主管处理依据 *',txt('basis'),true):''}</div><p class="sub">关联记录与依据附件至少提供一项。超出自主额度或再次挂起，由主管填写依据后办理。</p>`;
 }else if(act==='extendSuspension'){title=submit='延长挂起';body=`<div class="banner">原恢复时间：${date(r.expectedAt)}。延长仅限售后主管，记录原时间与处理依据。</div><div class="gap"></div><div class="form-grid">${field('新的恢复时间 *',inp('expectedAt','','datetime-local',true),true)}${field('延长依据 *',txt('basis'),true)}</div>`;}
 else if(act==='invalidateSuspension'){title=submit='纠正挂起';body=`<div class="banner">确认挂起原因不成立后，立即恢复办理，本次挂起时间计入有效办理耗时，保留完整记录。</div><div class="gap"></div>${field('纠正依据 *',txt('note'),true)}`;}
 else{title=submit='恢复办理';body=`<div class="banner">${esc(r.reason)}</div><div class="gap"></div>${dataRows([['原定恢复时间',date(r.expectedAt)],['恢复至',esc(r.returnState==='待首联'?'首次联系':'售后办理')]])}<div class="gap"></div>${field('恢复说明 *',txt('note'),true)}`;}
 modal(title,body,{form:act,id:t.id,submit});return true;
}
