'use strict';
const assert=require('node:assert/strict'),E=require('./engine'),A=require('./access');
const NOW=Date.parse('2026-09-29T10:00:00+08:00'),H=E.HOUR;
let count=0;function test(name,fn){fn();console.log('通过：'+name);count++;}
function scenario(){
 let s=E.seed(NOW),r=E.apply(s,'intake',{type:'create',data:{sceneId:'scene-level-1',customerId:'customer1',store:E.STORES[0],title:'统一处理流程验收',description:'客户反馈服务沟通不足',orderId:'order-r1'}},NOW);s=r.state;const id=r.caseId;
 return {get s(){return s;},set s(v){s=v;},get c(){return s.cases.find(c=>c.id===id);},at:NOW,
 task(kind){return E.pending(this.c).find(t=>!kind||t.kind===kind);},
 act(type,data={},who){const c=this.c,t=this.task();s=E.apply(s,who||t.assigneeId,{type,caseId:id,taskId:t?.id,expectedRevision:c.revision,data},this.at).state;return this.c;},
 process(data){return this.act('process',{content:'已核实客户诉求并安排处理',contactResult:'connected',method:'电话记录',...data});},
 resolved(){return this.process({intent:'resolved',customerAgreed:true,evidence:'客户电话明确认可已解决',fulfillment:'已解释误会并完成致歉，无剩余事项'});},
 refund(){return this.process({intent:'refund',orderId:'order-r1',refundAmount:'600',refundReason:'未消费服务',deadline:this.at+20*H});},
 approve(){while(this.c.stage==='approval')this.act('refundApproval',{decision:'approve',content:'同意当前版本退款'});}
 };
}
test('查看不接单，接单不等于联系；处理时钟从接单起算',()=>{const x=scenario();assert.equal(E.activePeriod(x.c),undefined);assert(!x.c.firstConnectedAt);x.at+=10*60000;x.act('accept');assert.equal(E.activePeriod(x.c).createdAt,x.at);assert.equal(E.activePeriod(x.c).dueAt,x.at+8*H);assert(!x.c.firstConnectedAt);});
test('一次联系已解决：单次提交进入400回访，不能直接结案',()=>{const x=scenario();x.act('accept');x.at+=H;x.resolved();assert.equal(x.c.stage,'visit');assert.equal(x.c.firstConnectedAt,x.at);assert(x.c.plans[0].resolvedInContact);assert(x.c.plans[0].items.every(i=>i.status==='done'));assert.equal(x.c.processingPeriods[0].elapsedMs,H);x.act('visit',{result:'resolved',content:'确认问题解决'});assert.equal(x.c.stage,'closed');assert(!x.c.tasks.some(t=>t.kind==='quality'));});
test('未接通只算尝试；再次跟进不重置首联、处理与整单期限',()=>{const x=scenario();x.act('accept');const p=E.activePeriod(x.c),target=x.c.targetAt,first=x.c.firstContactDue;x.at+=H;x.process({intent:'followup',contactResult:'unreachable',waitingReason:'客户未接听',retryAt:x.at+H});assert(x.c.firstAttemptAt);assert(!x.c.firstConnectedAt);assert.equal(E.activePeriod(x.c).dueAt,p.dueAt);assert.equal(x.c.firstContactDue,first);assert.equal(x.c.targetAt,target);assert.equal(x.c.nextFollowupAt,x.at+H);x.at+=H;x.process({intent:'followup',waitingReason:'等待客户核对',retryAt:x.at+H});assert.equal(x.c.stage,'plan');assert.equal(x.c.firstConnectedAt,x.at);assert.equal(E.activePeriod(x.c).id,p.id);assert.equal(E.pending(x.c)[0].dueAt,p.dueAt);});
test('保存跟进必须留下一步；错误提交原子回滚首次联系和所有记录',()=>{const x=scenario();x.act('accept');const before=JSON.stringify(x.s);assert.throws(()=>x.process({intent:'followup',retryAt:x.at+H}),/待跟进事项/);assert.equal(JSON.stringify(x.s),before);assert.throws(()=>x.process({intent:'resolved',customerAgreed:true,evidence:'客户已接受'}),/实际解决结果/);assert.equal(JSON.stringify(x.s),before);});
test('未接通、未得到客户接受均不能提交已解决结果',()=>{const x=scenario();x.act('accept');assert.throws(()=>x.process({intent:'resolved',contactResult:'unreachable'}),/首次有效联系/);assert.throws(()=>x.process({intent:'resolved',fulfillment:'解释完毕',evidence:'已解释'}),/客户已接受/);assert.equal(x.c.plans.length,0);});
test('未来补做服务必须由执行人登记，不能用方案提交冒充履行',()=>{const x=scenario();x.act('accept');x.process({intent:'service',customerAgreed:true,evidence:'客户同意次日补做',serviceType:'补做服务',executorId:'aftercare',itemDescription:'补做一次护理',deadline:x.at+5*H});assert.equal(x.c.stage,'service');assert.equal(x.task().assigneeId,'aftercare');assert(!E.pending(x.c).some(t=>t.kind==='visit'));assert.equal(x.task().dueAt,x.at+5*H);assert.throws(()=>x.act('service',{content:'已完成'},'store1'),/不由您/);x.act('service',{content:'已完成补做，客户确认'});assert.equal(x.c.stage,'visit');});
test('退款方案送审后结束处理阶段，等待审批不计入处理人耗时',()=>{const x=scenario();x.act('accept');x.at+=H;x.refund();assert.equal(x.c.stage,'approval');assert.equal(E.activePeriod(x.c),undefined);assert.equal(x.c.processingPeriods[0].elapsedMs,H);x.at+=6*H;x.approve();assert.equal(x.c.stage,'confirm');assert.equal(x.c.processingPeriods.length,2);assert.equal(E.activePeriod(x.c).createdAt,x.at);assert.equal(x.c.processingPeriods[0].elapsedMs,H);});
test('审批完成后必须记录同版客户意见，结果核实成功才进回访',()=>{const x=scenario();x.act('accept');x.refund();x.approve();assert.throws(()=>x.act('refundStart',{},'finance'),/已处理|转派/);x.process({intent:'confirm',version:1,decision:'agree',content:'已电话确认客户接受V1退款600元'});assert.equal(x.c.stage,'refund');assert(!E.activePeriod(x.c));x.act('refundStart');x.act('refundResult',{result:'unknown',content:'渠道未返回结果',occurredAt:x.at});assert.equal(x.task().kind,'refundVerify');assert.throws(()=>x.act('refundStart'),/已处理|转派/);x.act('refundVerify',{result:'success',reference:'FLOW-OK-1',content:'渠道已成功',occurredAt:x.at});assert.equal(x.c.stage,'visit');x.act('visit',{result:'resolved',content:'客户确认到账并解决'});assert.equal(x.c.stage,'closed');});
test('审批驳回生成新处理时段，旧审批链接不能继续使用',()=>{const x=scenario();x.act('accept');x.refund();const old=x.task();x.at+=2*H;x.act('refundApproval',{decision:'reject',content:'补齐订单依据'});assert.equal(x.c.stage,'plan');assert.equal(E.activePeriod(x.c).createdAt,x.at);assert(!A.taskAccess(x.s,old.assigneeId,x.c.id,old.id).actionable);x.refund();assert.equal(x.c.plans.at(-1).version,2);assert.equal(x.c.plans[0].refund.reservation,'released');});
test('回访未解决重新处理，整单时钟连续，原处理和执行历史保留',()=>{const x=scenario();x.act('accept');x.resolved();const original=x.c.processingPeriods[0],target=x.c.targetAt;x.at+=2*H;x.act('visit',{result:'unresolved',content:'仍有问题'});assert.equal(x.c.round,2);assert.equal(E.activePeriod(x.c).createdAt,x.at);assert.deepEqual(x.c.processingPeriods[0],original);assert.equal(x.c.targetAt,target);x.resolved();x.act('visit',{result:'resolved',content:'这次解决'});assert.equal(x.c.stage,'closed');});
test('处理交接保留前任耗时，接替者需接单，不能重置本段截止时间',()=>{const x=scenario();x.act('accept');const first=E.activePeriod(x.c);x.at+=9*H;x.act('assign',{assigneeId:'aftercare',reason:'店长休假，售后交接'},'manager');assert.equal(x.c.stage,'accept');assert.equal(x.c.processingPeriods[0].status,'transferred');assert.equal(x.c.processingPeriods[0].overdueMs,H);assert.equal(x.c.firstContactDue,NOW+2*H);x.at+=H;x.act('accept');const next=E.activePeriod(x.c);assert.equal(next.assigneeId,'aftercare');assert.equal(next.createdAt,x.at);assert.equal(next.dueAt,first.dueAt);x.at+=H;x.resolved();assert.equal(x.c.processingPeriods[1].overdueMs,H);});
test('跟进提醒与办理超时各一次，提醒链接绑定实际待办任务',()=>{const x=scenario();x.act('accept');x.process({intent:'followup',waitingReason:'等客户核对',retryAt:x.at+H});x.s=E.refresh(x.s,x.at+9*H);const n=x.s.notices.find(n=>n.title==='跟进时间已到');assert(n);assert.equal(n.taskId,x.task().id);const over=x.s.notices.find(n=>n.title==='办理超时提醒 · 联系与处理');assert(over);assert.equal(over.taskId,x.task().id);const count=x.s.notices.length;x.s=E.refresh(x.s,x.at+10*H);assert.equal(x.s.notices.length,count);assert.equal(E.timings(x.c,x.at+10*H).find(t=>t.kind==='processing').overdueMs,2*H);});
test('跨端重复提交与其他人操作被拒绝，不能重复生成回访',()=>{const x=scenario();x.act('accept');const command={type:'process',caseId:x.c.id,taskId:x.task().id,expectedRevision:x.c.revision,data:{intent:'resolved',contactResult:'connected',content:'解决',customerAgreed:true,evidence:'同意',fulfillment:'已完成'}};assert.throws(()=>E.apply(x.s,'manager',command,x.at),/不由您/);x.s=E.apply(x.s,'store1',command,x.at).state;assert.throws(()=>E.apply(x.s,'store1',command,x.at),/已被更新/);assert.equal(E.pending(x.c).filter(t=>t.kind==='visit').length,1);});
test('旧工单安全迁移：保留期限与历史，重复加载不再迁移',()=>{const x=scenario();x.act('accept');x.act('contact',{result:'connected',content:'已联系'});const old=JSON.parse(JSON.stringify(x.s)),c=old.cases[0];delete c.workflowVersion;delete c.processingPeriods;old.workflowVersion=2;const due=E.pending(c)[0].dueAt,records=c.records.length;E.normalize(old,NOW);assert.equal(E.activePeriod(c).dueAt,due);assert(E.activePeriod(c).legacy);assert.equal(c.records.length,records);const snap=JSON.stringify(old);E.normalize(old,NOW);assert.equal(JSON.stringify(old),snap);});
test('历史品控待办迁移为真实回访，不凭空生成解决记录或自动结案',()=>{const x=scenario();x.act('accept');x.resolved();const old=JSON.parse(JSON.stringify(x.s)),c=old.cases[0],t=E.pending(c)[0];c.stage='quality';t.kind='quality';t.assigneeId='quality';delete c.workflowVersion;const visits=c.visits.length;E.normalize(old,NOW+H);assert.equal(c.stage,'visit');assert.equal(t.status,'cancelled');assert.equal(c.visits.length,visits);assert.equal(E.pending(c)[0].assigneeId,'callback');assert(!c.closedAt);assert(!A.taskAccess(old,'quality',c.id,t.id).actionable);});
test('配置处理阶段时限仅影响新工单，已受理快照保持原截止时间',()=>{const x=scenario();x.act('accept');const oldDue=E.activePeriod(x.c).dueAt;const d=E.Rules.prepareScene(E.Rules.sceneList(x.s)[0]);d.config.timing.processingHours=3;x.s=E.Rules.saveScene(x.s,'manager',d,0,NOW);assert.equal(E.activePeriod(x.c).dueAt,oldDue);const made=E.apply(x.s,'intake',{type:'create',data:{sceneId:d.id,customerId:'customer1',store:E.STORES[0],title:'新时限',description:'新时限验证'}},NOW);const c=made.state.cases[0],t=E.pending(c)[0],accepted=E.apply(made.state,t.assigneeId,{type:'accept',caseId:c.id,taskId:t.id,expectedRevision:c.revision},NOW);assert.equal(E.activePeriod(accepted.state.cases[0]).dueAt,NOW+3*H);});
console.log(`完成 ${count} 项统一流程与时效验证。`);
