/* 独立演示业务模型：不调用外部服务。金额以分保存。 */
(function(root){
'use strict';
const H=3600000, USERS=[{id:'chen',name:'陈悦',role:'agent',title:'售后专员'},{id:'zhou',name:'周宁',role:'agent',title:'售后专员'},{id:'jiang',name:'蒋琴',role:'lead',title:'售后负责人'},{id:'gu',name:'顾岚',role:'lead',title:'区域审批负责人'},{id:'li',name:'李晓',role:'store',title:'杭州湖滨店店长',store:'杭州湖滨店'},{id:'zhang',name:'张敏',role:'store',title:'上海徐汇店店长',store:'上海徐汇店'},{id:'sun',name:'孙琳',role:'finance',title:'财务'},{id:'wu',name:'吴桐',role:'sales',title:'业务员',store:'杭州湖滨店'},{id:'wang',name:'王言',role:'admin',title:'系统管理员'}];
const CHANNELS=['400电话','经理热线','门店H5 / A3','微信小程序','售后保障 / 企微','业务员代发起'];
const STATES=['待分派','待首联','处理中','待方案审批','待打款','待回访','已结案'];
const STORES=['杭州湖滨店','上海徐汇店','南京新街口店','成都春熙店'];
const Configuration=typeof module!=='undefined'&&module.exports?require('../configuration.js'):root.ComplaintConfiguration;
for(const p of Configuration.STAFF)if(!USERS.some(u=>u.id===p.id))USERS.push({id:p.id,name:p.name,title:p.role,role:({'售后主管':'lead','审批主管':'lead','财务审核':'finance','门店店长':'store','系统管理员':'admin','业务员':'sales'})[p.role]||'agent',...(p.store!=='*'?{store:p.store}:{})});
const FIELDS={level:'投诉等级',repeat:'重复投诉',channel:'来源渠道',store:'所属门店',type:'方案类型',refund:'退款金额',compensation:'赔偿金额',total:'申请总额'};
const id=()=>Math.random().toString(36).slice(2,10), clone=o=>JSON.parse(JSON.stringify(o));
function user(uid){return USERS.find(u=>u.id===uid)}
function assert(v,msg){if(!v)throw Error(msg)}
function stamp(){return Date.now()}
function log(t,actor,title,body=''){t.logs.unshift({id:id(),at:stamp(),actor:user(actor)?.name||actor,title,body});t.updated=stamp()}
function seed(){
 const n=stamp(),s={version:4,actor:'jiang',sequence:13,round:0,tickets:[],scenes:[],rules:{keywords:['12315','媒体','报警','工商','卫健'],level1:24,level2:72,first:2,approval:4,payment:12,review:8,risk:0.5,warn:4,mode:'auto',fallback:'jiang',finance:'sun',onDuty:['chen','zhou'],schedule:{chen:{start:'00:00',end:'23:59'},zhou:{start:'00:00',end:'23:59'}},channelOwner:'jiang',notifications:{assigned:true,risk:true,approval:true,payment:true,overdue:true}},orders:[]};
 const people=[['王女士','13800001001','杭州湖滨店','淡斑护理疗程',680000],['林女士','13800001002','上海徐汇店','面部护理套餐',398000],['陈女士','13800001003','杭州湖滨店','定金预付款',50000],['刘女士','13800001004','南京新街口店','光电修护套餐',1280000],['赵女士','13800001005','上海徐汇店','补水护理',128000],['周女士','13800001006','成都春熙店','身体护理套餐',580000]];
 people.forEach((p,i)=>s.orders.push({id:'O'+(i+1),external:'DD202609'+String(i+1).padStart(4,'0'),system:i===1?'淡斑小程序':'A3主系统',member:'M1000'+i,name:p[0],phone:p[1],store:p[2],project:p[3],paid:p[4],refunded:0,staff:['许晴','刘欣','吴桐'][i%3],receptionistId:p[2]==='杭州湖滨店'?'li':p[2]==='上海徐汇店'?'zhang':'jiang',isNew:i===2?'新客':'老客'}));
 const node=(name,who='jiang')=>({id:id(),type:'approval',name,people:[who],mode:'any',hours:4});
 function scene(name,priority,groups,nodes,fallback=false){s.scenes.push({id:id(),name,priority,enabled:true,fallback,published:{version:1,event:'提交处理方案',groups,nodes,at:n,by:'王言'},draft:null})}
 scene('高风险投诉方案',10,[[{field:'level',op:'eq',value:'4'}]],[node('风险处置审批'),node('区域负责人复核','gu'),{id:id(),type:'cc',name:'抄送财务',people:['sun']}]);
 scene('重复投诉方案',20,[[{field:'repeat',op:'eq',value:'true'}]],[node('重复投诉复核'),{id:id(),type:'cc',name:'抄送区域负责人',people:['gu']}]);
 scene('赔偿方案审批',30,[[{field:'compensation',op:'gt',value:'0'}]],[node('赔偿方案审批'),node('区域负责人审批','gu')]);
 scene('普通退款审批',40,[[{field:'type',op:'eq',value:'退款'},{field:'compensation',op:'eq',value:'0'}]],[node('售后负责人审批'),{id:id(),type:'branch',name:'金额分支',condition:{field:'refund',op:'gte',value:'5000'},yes:[node('区域负责人审批','gu')],no:[]}]);
 scene('其他处理方案',999,[],[node('方案核实')],true);
 const samples=[
 [0,4,'处理中','chen','服务效果争议，客户提及12315','客户对护理效果不满意，表示将向12315投诉，要求退款。',30,0,true],
 [1,2,'待首联','chen','淡斑项目退款申请','剩余项目希望退款，请尽快联系客户核实。',4,3,false],
 [2,2,'处理中','chen','定金退款未解决，再次来电','客户反馈上次约定的退款未推进，再次要求退款。',62,5,true],
 [4,1,'待首联','zhang','预约到店等待时间过长','客户等待时间较长，希望门店说明并改善安排。',5,2,false],
 [3,3,'待方案审批','zhou','护理后不适，协商补偿方案','已与客户沟通补偿方案，等待负责人批准。',35,0,false],
 [1,2,'待打款','chen','剩余疗程退款，等待打款','客户已确认退款金额与退款方式。',45,3,false],
 [5,2,'待打款','zhou','套餐退款，收款信息待核验','上次付款未成功，请财务核实。',66,1,false],
 [4,1,'待回访','zhang','门店服务态度反馈','店长已致歉并完成服务安排，等待回访确认。',12,2,false],
 [2,2,'待分派','','业务员代发起定金退款','客户申请退回尚未使用的项目定金。',1,5,false],
 [5,2,'已结案','zhou','未使用套餐退款已完成','客户确认收到退款，对处理结果认可。',120,4,false],
 [0,2,'处理中','li','消费项目沟通存在误解','客户希望重新核实项目使用规则。',7,2,false],
 [3,3,'处理中','chen','护理补偿金额待协商','等待门店提交服务记录，售后继续与客户沟通。',18,0,false]
 ];
 samples.forEach((a,i)=>{const o=s.orders[a[0]],created=n-a[6]*H;const t={id:'KS20260929-'+String(i+1).padStart(3,'0'),name:o.name,phone:o.phone,member:o.member,isNew:o.isNew,store:o.store,order:o.id,project:o.project,amount:o.paid,staff:o.staff,channel:CHANNELS[a[7]],title:a[4],description:a[5],level:a[1],repeat:a[8],riskAck:!a[8]&&a[1]!==4,owner:a[3],creator:i===8?'wu':'chen',state:a[2],created,updated:created,deadline:created+(a[1]===1?24:72)*H,taskDeadline:n+((i%4)-1)*H,participants:[a[3],'chen'].filter(Boolean),sources:[{channel:CHANNELS[a[7]],at:created,content:a[5]}],logs:[],attachments:[],proposal:null,approval:null,payments:[],related:[],firstContact:a[2]==='待首联'||a[2]==='待分派'?null:created+H};log(t,'系统','受理工单',a[5]);t.logs[0].at=created;if(t.firstContact){log(t,a[3]||'chen','首次联系','已核实客户诉求，后续处理方案正在沟通。');t.logs[0].at=t.firstContact;}s.tickets.push(t)});
 for(const i of [4,5,6]){const t=s.tickets[i];t.state='处理中';const p={type:i===4?'退款＋赔偿':'退款',refund:i===4?200000:i===5?100000:150000,compensation:i===4?50000:0,content:'经核实未使用项目，按协商方案退回；客户已知悉金额。',consent:'客户已认可',account:'原支付渠道',version:1};startApproval(s,t,t.owner,p);if(i!==4){while(t.state==='待方案审批'){const who=t.approval.steps[t.approval.index].people.find(x=>!t.approval.steps[t.approval.index].votes.includes(x));approve(s,t,who,true,'方案符合退款条件');}if(i===6)t.payments.push({id:id(),result:'失败',reason:'收款账户状态异常，待补正',at:n-2*H,actor:'孙琳',amount:p.refund});}}
 const closed=s.tickets[9];closed.closed=n-48*H;log(closed,'zhou','工单结案','客户已确认到账，回访认可。');return migrate(s);
}
function context(t,p=t.proposal){return {level:t.level,repeat:t.repeat,channel:t.channel,store:t.store,type:p?.type,refund:p? p.refund/100:undefined,compensation:p?p.compensation/100:undefined,total:p?(p.refund+p.compensation)/100:undefined}}
function matchCondition(c,ctx){let a=ctx[c.field],b=c.value;if(a===undefined||a===null||a==='')return false;if(['gt','gte','lt','lte'].includes(c.op)){a=Number(a);b=Number(b);if(!Number.isFinite(a)||!Number.isFinite(b))return false;return {gt:a>b,gte:a>=b,lt:a<b,lte:a<=b}[c.op]}if(['refund','compensation','total','level'].includes(c.field)&&['eq','ne'].includes(c.op)){const eq=Number(a)===Number(b);return c.op==='eq'?eq:!eq}if(c.op==='in')return String(b).split(/[,，]/).map(x=>x.trim()).includes(String(a));return c.op==='ne'?String(a)!==String(b):String(a)===String(b)}
function matchGroups(groups,ctx){return groups.length>0&&groups.some(g=>g.length>0&&g.every(c=>matchCondition(c,ctx)))}
function matching(s,t,p){if(s.rulesSchema===5){const f=t.flow;if(f&&f.level===t.level)return[{id:f.id,name:f.name,level:f.level,published:clone(f.doc)}];const sc=sceneFor(s,t.level);return sc?[sc]:[];}return s.scenes.filter(x=>x.enabled&&x.published).sort((a,b)=>Number(a.fallback)-Number(b.fallback)||a.priority-b.priority).filter(x=>x.fallback||matchGroups(x.published.groups,context(t,p)))}
function flatten(nodes,ctx){return nodes.flatMap(n=>n.type==='branch'?flatten(matchCondition(n.condition,ctx)?n.yes:n.no,ctx):[clone(n)])}
function canView(s,t,actor){const u=user(actor);if(!u||u.role==='admin')return false;return u.role==='lead'||t.owner===actor||t.creator===actor||t.participants.includes(actor)||(u.role==='store'&&u.store===t.store)||(u.role==='finance'&&(t.state==='待打款'||t.payments.length>0||t.approval?.steps.some(x=>x.people.includes(actor))))}
function taskPeople(s,t){if(t.state==='待分派')return[t.pendingAssignment?.dispatcher||s.rules.fallback];if(t.state==='待方案审批'){const n=t.approval?.steps[t.approval.index];return n?n.people.filter(x=>!n.votes.includes(x)):[]}if(t.state==='待打款')return[t.flow?.doc.finance||s.rules.finance];return ['已结案','已合并'].includes(t.state)?[]:[t.currentAssignee||t.owner]}
function needsRiskReview(t){return (t.level===4||t.repeat)&&t.state==='待回访'&&!t.riskAck}
function isPending(s,t,a){return taskPeople(s,t).includes(a)||(needsRiskReview(t)&&a===s.rules.riskConfig.receiver)}
function canHandle(s,t,a){return canView(s,t,a)&&(t.currentAssignee===a||t.owner===a||user(a)?.role==='lead')}
function requireHandle(s,t,a){assert(canHandle(s,t,a),'当前人员没有办理权限');assert(!['已结案','已合并'].includes(t.state),'该工单已结束')}
function taskDue(s,t,key){const k=key==='level2'?'process':key;const h=t.flow?.doc.stage?.[k]||s.rules[key]||4;t.taskDeadline=stamp()+h*H;const node={process:'proposal',payment:'payment',review:'callback'}[k];if(node&&t.flow?.config)Configuration.activate(s,t,node);}
function scan(s,t,actor,body){const hit=(s.rules.riskConfig?.keywords||s.rules.keywords).filter(k=>body.includes(k));if(hit.length){const old=t.level;t.level=4;if(s.rulesSchema===5&&old!==4){holdForUpgrade(s,t,'命中风险关键词');bindFlow(s,t,'命中 '+hit.join('、'));if(t.flow?.config)t.deadline=deadlineFor(t);}t.riskAck=false;t.gradeReason='命中风险词：'+hit.join('、');t.riskWords=[...new Set([...(t.riskWords||[]),...hit])];log(t,'系统','升级四级',`命中：${hit.join('、')}；保留风险标识，结案前须完成风险复核。`)}if(hit.length&&user(t.owner)?.role==='store'){t.owner=autoOwner(s,t);if(!t.owner)t.state='待分派'}if(t.level>=3&&!t.participants.includes('jiang'))t.participants.push('jiang')}
function inShift(s,uid){const q=s.rules.schedule?.[uid];if(!q)return true;const d=new Date(),x=d.getHours()*60+d.getMinutes(),v=z=>{const[a,b]=z.split(':').map(Number);return a*60+b};const a=v(q.start),b=v(q.end);return a<=b?x>=a&&x<=b:x>=a||x<=b}
function autoOwner(s,t){if(t.flow?.assignment){Configuration.activate(s,t,'contact');return t.currentAssignee&&!t.pendingAssignment?t.currentAssignee:'';}if(t.level===1)return USERS.find(x=>x.role==='store'&&x.store===t.store)?.id||'';if(t.channel==='微信小程序')return s.rules.channelOwner;const pool=s.rules.onDuty.filter(x=>inShift(s,x));return pool.length?pool[(s.round++)%pool.length]:''}
function create(s,a,data){assert(['agent','lead','store','sales'].includes(user(a)?.role),'当前人员不可新增工单');assert(/^1\d{10}$/.test(data.phone),'请输入11位手机号');assert(data.title?.trim()&&data.description?.trim(),'请填写投诉摘要和内容');assert(data.store,'请选择门店');const n=stamp(),o=s.orders.find(x=>x.id===data.order);if(o)assert(o.phone===data.phone,'订单与客户手机号不一致');let t={id:'KS'+new Date(n).toISOString().slice(0,10).replaceAll('-','')+'-'+String(s.sequence++).padStart(3,'0'),name:data.name,phone:data.phone,member:o?.member||data.member||'',isNew:o?.isNew||data.isNew||'待核实',store:o?.store||data.store,order:o?.id||'',project:o?.project||data.project||'待核实',amount:o?.paid||0,staff:o?.staff||data.staff||'',channel:data.channel,title:data.title.trim(),description:data.description.trim(),level:Number(data.level)||1,repeat:!!data.repeat,riskAck:!data.repeat&&Number(data.level)!==4,owner:'',creator:a,state:'待分派',created:n,updated:n,deadline:n+(Number(data.level)===1?s.rules.level1:s.rules.level2)*H,taskDeadline:n+s.rules.first*H,participants:[a],sources:[{channel:data.channel,at:n,content:data.description}],logs:[],attachments:data.attachments||[],proposal:null,approval:null,payments:[],related:[],firstContact:null};if(['store','sales'].includes(user(a).role)){assert(t.store===user(a).store,'只能为本店订单发起');t.channel=user(a).role==='sales'?CHANNELS[5]:CHANNELS[2];t.sources[0].channel=t.channel;}scan(s,t,a,t.title+'\n'+t.description);if(s.configuration){bindFlow(s,t,'工单受理');t.state='待首联';}if(t.level===4)t.deadline=n+s.rules.level2*H;t.owner=t.flow?.config?autoOwner(s,t):(data.owner&&user(a).role==='lead'?data.owner:(s.rules.mode==='auto'?autoOwner(s,t):''));if(t.owner){t.state='待首联';t.participants.push(t.owner)}log(t,a,'受理工单',t.description);if(data.related){const old=s.tickets.find(x=>x.id===data.related);assert(old&&(old.phone===t.phone||(t.member&&old.member===t.member)),'关联工单不属于同一客户');old.repeat=true;old.riskAck=false;old.related.push(t.id);t.related.push(old.id);t.repeat=true;t.riskAck=false;log(old,a,'再次投诉关联',t.id)}if(s.rulesSchema===5){if(!t.flow?.config)bindFlow(s,t,'工单受理');t.deadline=deadlineFor(t);t.taskDeadline=t.created+t.flow.doc.stage.first*H;t.gradeReason=t.riskWords?.length?'命中风险词：'+t.riskWords.join('、'):'受理人员确认';}s.tickets.unshift(t);return t}
function follow(s,t,a,d){requireHandle(s,t,a);assert(d.content?.trim(),'请填写沟通内容');assert(['待首联','处理中','待回访','待方案审批','待打款'].includes(t.state),'当前节点不能跟进');if(d.connected&&t.state==='待首联'){t.firstContact=stamp();t.state='处理中';taskDue(s,t,'level2')}t.nextFollow=d.next||'';log(t,a,d.connected?'有效联系 / 跟进':'联系尝试',`${d.method||'电话'} · ${d.connected?'已接通':'未接通'}\n${d.content}${d.request?'\n客户诉求：'+d.request:''}${d.next?'\n下次跟进：'+d.next:''}`);if((d.method||'电话')==='电话'){t.calls=t.calls||[];const callId='CALL-'+id().toUpperCase();t.calls.push({id:callId,at:stamp(),actor:user(a).name,result:d.connected?'已接通':'未接通'});t.logs[0].body+='\n关联通话：'+callId;}if(d.files)t.attachments.push(...d.files);scan(s,t,a,d.content+'\n'+(d.request||''))}
function assign(s,t,a,who,reason){assert(user(a)?.role==='lead'||t.pendingAssignment?.dispatcher===a,'只有当前分派负责人可分派');assert(!['已结案','已合并'].includes(t.state),'工单已结束');assert((t.pendingAssignment?.node==='payment'?['finance']:['agent','store','lead']).includes(user(who)?.role),'请选择有效处理人');if(user(who).role==='store')assert(user(who).store===t.store,'店长所属门店不匹配');assert(reason.trim(),'请填写分派原因');const old=t.owner;if(!Configuration.assignPending(s,t,who)){t.owner=who;if(t.flow?.config&&['待首联','处理中','待回访'].includes(t.state)){t.currentAssignee=who;t.nodeOwners??={};t.nodeOwners[t.activeNode||'contact']=who;}}t.participants.push(who);if(t.state==='待分派'){t.state=t.firstContact?'处理中':'待首联';if(!t.flow?.config)taskDue(s,t,'first')}log(t,a,'调整负责人',`${user(old)?.name||'未分派'} → ${user(who).name}；${reason}`)}
function nextApproval(s,t){while(t.approval.index<t.approval.steps.length){let n=t.approval.steps[t.approval.index];if(n.type==='cc'){log(t,'系统',n.name,'抄送：'+n.people.map(x=>user(x)?.name||x).join('、'));t.participants.push(...n.people);n.done=true;t.approval.index++;}else{t.state='待方案审批';t.taskDeadline=stamp()+(n.hours||s.rules.approval)*H;return}}t.approval.status='已通过';t.proposal.approved=true;t.state=t.proposal.refund+t.proposal.compensation>0?'待打款':'待回访';taskDue(s,t,t.state==='待打款'?'payment':'review');log(t,'系统','审批通过',t.state==='待打款'?'生成财务打款任务':'进入结果确认')}
function startApproval(s,t,a,p){requireHandle(s,t,a);assert(t.state==='处理中','请先完成首联，或处理退回事项');if(t.flow?.config)assert(t.currentAssignee===a||user(a)?.role==='lead','请由当前处理节点办理人提交方案');assert(!(t.level===1&&p.refund+p.compensation>0),'一级不能提交资金方案，请先升级工单');const limit=t.gradePolicy?.smallLimit??s.rules.grading?.smallLimit;assert(!(t.level===2&&limit&&p.compensation>limit*100),'赔偿超出小额赔付上限，请先升级三级');assert(p.content?.trim(),'请填写处理方案');assert(p.consent==='客户已认可','请先与客户确认方案');assert(Number.isSafeInteger(p.refund)&&Number.isSafeInteger(p.compensation)&&p.refund>=0&&p.compensation>=0,'金额格式不正确');assert(p.type==='退款＋赔偿'||(p.type==='退款'&&p.compensation===0)||(p.type==='赔偿'&&p.refund===0)||(p.type==='普通处理'&&p.refund+p.compensation===0),'方案类型与金额不一致');if(p.refund+p.compensation>0){assert(p.account?.trim(),'请核实收款方式');const o=s.orders.find(x=>x.id===t.order);assert(o,'资金方案必须关联核实后的订单');const reserved=s.tickets.filter(x=>x.id!==t.id&&x.order===t.order&&x.state==='待打款').reduce((v,x)=>v+(x.proposal?.refund||0),0);assert(p.refund<=o.paid-o.refunded-reserved,'退款超过订单可退余额（含其他待打款占用）')}
 p.version=(t.proposal?.version||0)+1;const scenes=matching(s,t,p);assert(scenes.length,'未匹配可用场景，请负责人配置兜底流程');const sc=scenes[0],resolved=t.flow?.config?Configuration.approvals(s,t,a,p):null,steps=resolved?resolved.steps:flatten(sc.published.nodes,context(t,p)).map(n=>({...n,people:[...new Set(n.people.map(x=>x===a?(x==='jiang'?'gu':'jiang'):x))],votes:[],done:false}));assert(steps.some(x=>x.type==='approval'),'审批链缺少审批节点');if(t.approval){t.approvalHistory=t.approvalHistory||[];t.approvalHistory.push(clone(t.approval))}t.proposal=clone(p);t.approval={id:id(),scene:sc.name,sceneId:sc.id,version:sc.published.version,proposalVersion:p.version,path:resolved?.path,organizationVersion:resolved?.organizationVersion,steps,index:0,status:'审批中',initiator:a,at:stamp()};log(t,a,'提交方案',`${sc.name} · V${sc.published.version}\n${p.content}`);nextApproval(s,t);return sc}
function approve(s,t,a,pass,note){assert(t.state==='待方案审批'&&t.approval?.status==='审批中','审批任务已结束或更新');assert(t.approval.proposalVersion===t.proposal.version,'方案版本已变更');const n=t.approval.steps[t.approval.index];assert(n.people.includes(a)&&!n.votes.includes(a),'不是当前待审批人员');assert(a!==t.approval.initiator,'不可审批本人提交的方案');if(!pass)assert(note.trim(),'驳回必须填写原因');log(t,a,pass?'审批同意':'审批驳回',n.name+'；'+(note||'同意'));if(!pass){t.approval.status='已驳回';t.state='处理中';t.proposal.approved=false;taskDue(s,t,'level2');return}n.votes.push(a);if(n.mode==='any'||n.votes.length===n.people.length){n.done=true;t.approval.index++;nextApproval(s,t)}}
function withdraw(s,t,a,reason){requireHandle(s,t,a);assert(['待方案审批','待打款'].includes(t.state),'当前任务不能撤回');assert(!t.payments.some(p=>p.result==='成功'&&p.version===t.proposal.version),'已支付方案不能撤回');assert(reason.trim(),'请填写原因');t.approval.status='已撤回';t.proposal.approved=false;t.state='处理中';log(t,a,'撤回方案',reason);taskDue(s,t,'level2')}
function pay(s,t,a,d){assert(a===(t.flow?.doc.finance||s.rules.finance)&&user(a).role==='finance','不是当前财务任务人员');assert(t.state==='待打款'&&t.proposal?.approved,'不存在有效付款任务');assert(t.approval.proposalVersion===t.proposal.version,'付款方案已更新');assert(!t.payments.some(p=>p.result==='成功'&&p.version===t.proposal.version),'该方案已支付');if(d.result==='退回'){assert(d.reason?.trim(),'请填写退回原因');t.proposal.approved=false;t.approval.status='财务退回';t.state='处理中';log(t,a,'财务退回',d.reason);taskDue(s,t,'level2');return}assert(['成功','失败'].includes(d.result),'请选择付款结果');if(d.result==='成功'){assert(d.reference?.trim()&&d.proof?.length,'请填写流水号并上传凭证');assert(!s.tickets.some(x=>x.payments.some(p=>p.result==='成功'&&p.reference===d.reference)),'付款流水号已登记');assert(d.amount===t.proposal.refund+t.proposal.compensation,'实际付款金额必须等于批准金额');const o=s.orders.find(x=>x.id===t.order);assert(o&&o.refunded+t.proposal.refund<=o.paid,'可退余额不足，请核实其他退款');o.refunded+=t.proposal.refund;t.state='待回访';taskDue(s,t,'review')}else assert(d.reason?.trim(),'请填写失败原因');t.payments.push({id:id(),version:t.proposal.version,at:stamp(),actor:user(a).name,...clone(d)});log(t,a,'打款'+d.result,d.result==='成功'?'流水号：'+d.reference:d.reason)}
function review(s,t,a,d){requireHandle(s,t,a);assert(t.state==='待回访','尚未进入结果确认');if(t.flow?.config)assert(t.currentAssignee===a||user(a)?.role==='lead','请由当前回访节点办理人提交结果');assert(d.note?.trim(),'请填写回访记录');if(d.result==='认可'){assert((!t.repeat&&t.level!==4)||t.riskAck,'请负责人先完成风险复核');t.state='已结案';t.closed=stamp();log(t,a,'工单结案',d.note)}else if(d.result==='不认可'){t.state='处理中';t.riskAck=false;log(t,a,'客户不认可',d.note);taskDue(s,t,'level2')}else{log(t,a,'回访未接通',d.note)}}
function completeNormal(s,t,a,note){requireHandle(s,t,a);assert(t.state==='处理中'&&t.level===1,'当前工单需要提交处理方案');if(t.flow?.config)assert(t.currentAssignee===a||user(a)?.role==='lead','请由当前处理节点办理人提交结果');assert(note.trim(),'请填写处理结果');t.state='待回访';log(t,a,'提交处理结果',note);taskDue(s,t,'review')}
function riskAck(s,t,a,note){assert(user(a)?.role==='lead','只有负责人可复核');assert(needsRiskReview(t),'仅在结果确认环节办理结案风险复核');assert(note.trim(),'请填写复核意见');t.riskAck=true;log(t,a,'结案风险复核',note)}
function escalate(s,t,a,level,note){requireHandle(s,t,a);level=Number(level);assert([2,3,4].includes(level)&&level>t.level,'升级等级应高于当前等级');assert(note.trim(),'请填写升级原因');let old=t.level;holdForUpgrade(s,t,'工单升级');t.level=level;bindFlow(s,t,note);if(old===1&&level<4){if(t.deadline&&t.deadline<stamp())log(t,'系统','原一级时限已超时','保留原超时记录');t.deadline=t.flow?.config?deadlineFor(t):t.created+72*H;}if(t.flow?.config)t.deadline=deadlineFor(t);if(level===4){t.riskAck=false;}if(user(t.owner)?.role==='store'){t.owner=autoOwner(s,t);if(!t.owner)t.state='待分派'}t.gradeReason=note;log(t,a,'投诉升级',`${old}级 → ${t.level}级；${note}`)}
function repeat(s,t,a,note){assert(canView(s,t,a)&&user(a)?.role!=='finance','无权登记再次投诉');assert(note.trim(),'请填写再次投诉内容');assert(t.state!=='已合并','请在主工单登记');if(t.state==='已结案'){return create(s,a,{...t,title:'再次投诉：'+t.title,description:note,repeat:true,related:t.id,owner:'',attachments:[]})}t.repeat=true;t.riskAck=false;t.sources.push({channel:t.channel,at:stamp(),content:note});log(t,a,'再次投诉',note);scan(s,t,a,note);return t}
// V5: 等级主流程与资金审批分支分离。
function defaultScenes(){
 const n=stamp(), titles=['一级普通投诉','二级退款 / 小额赔付','三级严重赔偿','四级高风险投诉'];
 const approval=(name,who)=>({id:id(),type:'approval',name,people:[who],mode:'any',hours:4});
 return titles.map((name,i)=>{const level=i+1;let nodes=level===1?[]:[approval('售后负责人审批','jiang')];if(level>=3)nodes.push(approval('区域负责人审批','gu'));if(level===2)nodes.push({id:id(),type:'branch',name:'退款金额分支',condition:{field:'refund',op:'gte',value:'5000'},yes:[approval('区域负责人审批','gu')],no:[]});return{id:'GRADE-'+level,name,level,priority:level,enabled:true,fallback:false,history:[],draft:null,published:{version:1,event:'受理工单',groups:[[{field:'level',op:'eq',value:String(level)}]],nodes,stage:{first:2,process:level===1?12:24,payment:12,review:8,risk:0.5},supervisor:'jiang',finance:'sun',cc:level>=3?['jiang']:[],totalHours:level===1?24:level===4?null:72,clock:'natural',at:n,by:'系统'}}});
}
function migrate(s){for(const t of s.tickets||[]){delete t.riskAccepted;delete t.riskDeadline;}if(s.rulesSchema===5)return s;s.legacyScenes=clone(s.scenes||[]);s.scenes=defaultScenes();s.rulesSchema=5;s.rules.riskConfig={version:1,keywords:clone(s.rules.keywords),receiver:s.rules.fallback||'jiang',repeatReview:true};s.rules.reminders={warn:4,repeat:2,escalation:s.rules.fallback||'jiang'};s.rules.grading={smallLimit:null,serious:'较严重赔偿，由售后负责人确认',version:1};for(const t of s.tickets){bindFlow(s,t,'规则配置升级',false);t.legacyDeadline=true;if(t.approval)t.approval.legacy=true;}return s;}
function sceneFor(s,level){if(s.configuration){const sc=Configuration.scene(s,level);return {...sc,published:{version:sc.version}};}return s.scenes.find(x=>x.level===Number(level)&&x.enabled&&x.published)}
function bindFlow(s,t,reason,record=true){if(s.configuration){Configuration.bind(s,t);if(record)log(t,'系统','匹配处理场景',t.flow.name+' · V'+t.flow.version+'；'+reason);return;}if(s.rulesSchema!==5)return;const sc=sceneFor(s,t.level);assert(sc,'该等级缺少处理流程，请负责人核实');t.flow={id:sc.id,name:sc.name,level:sc.level,version:sc.published.version,doc:clone(sc.published),at:stamp()};t.gradePolicy=clone(s.rules.grading);t.participants=[...new Set([...t.participants,...sc.published.cc])];if(record)log(t,'系统','匹配处理场景',sc.name+' · V'+sc.published.version+'；'+reason);}
function deadlineFor(t){const h=t.flow?.doc.totalHours;return h>0?t.created+h*H:null}
function holdForUpgrade(s,t,reason){if(['待方案审批','待打款'].includes(t.state)){t.approvalHistory=t.approvalHistory||[];if(t.approval){t.approval.status='升级挂起';t.approvalHistory.push(clone(t.approval));}if(t.proposal)t.proposal.approved=false;t.state='处理中';log(t,'系统','挂起原审批 / 付款任务',reason+'；需重新提交方案');taskDue(s,t,'process');}}
function riskTest(s,body,repeat=false,level=1){const words=s.rules.riskConfig.keywords.filter(k=>String(body).includes(k));const target=words.length?4:Number(level);return{words,level:target,scene:sceneFor(s,target)?.name,actions:[...(words.length?['升级四级','标红','结案前复核']:[]),...(repeat?['重复投诉标红','负责人监督','结案前复核']:[])]};}
function saveRisk(s,d,a){assert(user(a)?.role==='lead'||user(a)?.role==='admin','没有配置权限');const words=String(d.keywords||'').split(/[、,，\n]/).map(x=>x.trim()).filter(Boolean);assert(words.length,'至少保留一个风险词');assert(user(d.receiver)?.role==='lead','请选择风险负责人');s.rules.riskConfig={version:s.rules.riskConfig.version+1,keywords:[...new Set(words)],receiver:d.receiver,repeatReview:true};s.rules.keywords=clone(words);s.rules.fallback=d.receiver;}
function saveTiming(s,d,a){assert(['lead','admin'].includes(user(a)?.role),'没有配置权限');for(const k of ['warn','repeat'])assert(Number(d[k])>0&&Number(d[k])<=72,'提醒间隔需大于0且不超过72小时');assert(user(d.escalation)?.role==='lead','请选择升级接收人');s.rules.reminders={warn:Number(d.warn),repeat:Number(d.repeat),escalation:d.escalation};s.rules.warn=Number(d.warn);}
function trial(s,input,doc,meta){const risk=riskTest(s,input.content,input.repeat,+input.level);assert([1,2,3,4].includes(risk.level),'请选择投诉等级');const sc=sceneFor(s,risk.level),use=meta?.level===risk.level&&doc?doc:sc.published;const p={type:input.type,refund:Math.round(+input.refund*100),compensation:Math.round(+input.compensation*100)};assert(p.refund>=0&&p.compensation>=0,'金额不可为负数');assert(!(risk.level===2&&s.rules.grading.smallLimit&&p.compensation>s.rules.grading.smallLimit*100),'赔偿超过小额标准，请确认三级后试算');assert(!(risk.level===1&&p.refund+p.compensation>0),'一级不能提交资金方案，请先升级并核实等级');assert(p.type==='退款＋赔偿'||p.type==='退款'&&p.compensation===0||p.type==='赔偿'&&p.refund===0||p.type==='普通处理'&&p.refund+p.compensation===0,'方案类型与金额不一致');return{...risk,name:meta?.level===risk.level?meta.name:sc.name,version:meta?.level===risk.level?'草稿':use.version,doc:use,approval:flatten(use.nodes,context({level:risk.level,repeat:input.repeat},p)).filter(x=>x.type==='approval'),total:use.totalHours,repeat:input.repeat};}
function validateScene(sc,doc){assert(sc.name?.trim(),'请填写场景名称');assert([1,2,3,4].includes(sc.level),'场景必须对应投诉等级');assert(doc.event==='受理工单','场景须在受理时生效');assert(doc.totalHours===(sc.level===1?24:sc.level===2||sc.level===3?72:doc.totalHours),'一级24小时、二三级72小时为当前目标');if(sc.level===4)assert(doc.totalHours===null||Number(doc.totalHours)>0,'四级整单时限须为正数或待设定');for(const h of Object.values(doc.stage))assert(Number.isFinite(+h)&&+h>0&&+h<=72,'节点时限须大于0且不超过72小时');assert(user(doc.supervisor)?.role==='lead','请配置有效监督负责人');assert(user(doc.finance)?.role==='finance','请配置财务');if(sc.level>=3)assert(doc.cc.includes('jiang'),'三级、四级必须同步蒋琴');assert(doc.cc.every(x=>!!user(x)),'抄送人员无效');let count=0;function walk(ns){ns.forEach(n=>{assert(n.name?.trim(),'节点名称不可为空');if(n.type==='branch'){assert(['type','refund','compensation','total'].includes(n.condition.field),'分支只允许方案类型或金额');const text=n.condition.field==='type';assert((text?['eq','ne']:['gt','gte','lt','lte','eq']).includes(n.condition.op),'比较方式无效');assert(text?['普通处理','退款','赔偿','退款＋赔偿'].includes(n.condition.value):String(n.condition.value).trim()!==''&&Number.isFinite(+n.condition.value)&&+n.condition.value>=0,'分支取值无效');walk(n.yes);walk(n.no);}else{assert(['approval','cc'].includes(n.type)&&n.people.length,'请选择节点人员');assert(n.people.every(x=>user(x)&&(n.type==='cc'||user(x).role==='lead')),'节点人员权限不符');if(n.type==='approval'){count++;assert(n.hours>0&&n.hours<=72,'审批时限无效');assert(['any','all'].includes(n.mode),'审批方式无效');}}})}walk(doc.nodes);if(sc.level===1)assert(count===0,'一级普通处理不设资金审批');else{assert(doc.nodes.some(n=>n.type==='approval'),'主干必须保留资金审批');if(sc.level>=3)assert(doc.nodes.filter(n=>n.type==='approval').length>=2,'三级、四级需保留两级审批');}return true;}
function publish(s,sc,doc,a){assert(['admin','lead'].includes(user(a)?.role),'没有发布权限');validateScene(sc,doc);assert(!s.scenes.some(x=>x.id!==sc.id&&x.level===sc.level),'该等级已存在主流程');sc.history=sc.history||[];if(sc.published)sc.history.push(clone(sc.published));sc.enabled=true;sc.published={...clone(doc),version:(sc.published?.version||0)+1,at:stamp(),by:user(a).name};sc.draft=null;return sc;}
function ruleTasks(s,t){const out=[],now=stamp();if(['已结案','已合并'].includes(t.state))return out;const recipients=taskPeople(s,t),r=s.rules.reminders;out.push({title:taskLabelFor(t),people:recipients,reason:'当前任务',key:t.id+':task'});const deadline=t.taskDeadline,near=deadline&&deadline-now<=r.warn*H;if(near)out.push({title:deadline<now?'节点超时':'节点临期',people:deadline<now?[...new Set([...recipients,r.escalation])]:recipients,reason:'节点截止 '+new Date(deadline).toLocaleString(),key:t.id+':node'});if(t.deadline&&t.deadline<now)out.push({title:'整单超时',people:[...new Set([...recipients,r.escalation])],reason:'整单目标已超过',key:t.id+':total'});if(needsRiskReview(t))out.push({title:'结案风险复核',people:[s.rules.riskConfig.receiver],reason:t.repeat?'重复投诉结案前复核':'四级投诉结案前复核',key:t.id+':risk'});for(const item of out){if(item.title.includes('超时')){const start=item.title==='整单超时'?t.deadline:t.taskDeadline;const step=r.repeat*H;item.nextAt=start+(Math.floor(Math.max(0,now-start)/step)+1)*step;}}return out;}
function taskLabelFor(t){return t.state==='待方案审批'?t.approval?.steps[t.approval.index]?.name||t.state:t.state;}

const API={needsRiskReview,scan,migrate,sceneFor,bindFlow,riskTest,saveRisk,saveTiming,trial,ruleTasks,H,USERS,CHANNELS,STATES,STORES,FIELDS,user,id,clone,seed,context,matchCondition,matchGroups,matching,flatten,canView,taskPeople,isPending,canHandle,create,follow,assign,startApproval,approve,withdraw,pay,review,completeNormal,riskAck,escalate,repeat,validateScene,publish,log};
if(typeof module!=='undefined')module.exports=API;root.Engine=API;
})(typeof window!=='undefined'?window:globalThis);
